### ISSUE TITLE
Can you please provide image for windows Server Containers 

### ISSUE THREAD

**Issue by asirfan** [k8snetworkplumbingwg/multus-cni#1000]
We may need this tar file targeted at windows Containers - Core or Nano. Can you please provide the same? For one of our project this a very critical requirement.

**Comment by dougbtv** [comment]
We'll need a community maintainer for this effort, someone to volunteer to create it and provide maintenance, feel free to join us at the maintainer's call to engage in the effort, more information can be found here @ https://github.com/k8snetworkplumbingwg/community
