### ISSUE TITLE
[multus-v4]Gather multus-damon config in ConfigMap

### ISSUE THREAD

**Issue by s1061123** [k8snetworkplumbingwg/multus-cni#1003]
Currently multus-daemon have two way of configuration

- ConfigMap
- Command line option (mainly for /etc/cni/net.d config generation, historically)

To simplify configuration for administrator, we should consolidate the config into ConfigMap

**Comment by dougbtv** [comment]
+1. Having a central point for configuration will be more intuitive, and less work for admins. Thanks Tomo for identifying a better design!
