### ISSUE TITLE
questions: multus cni expected behavior when  network restart 

### ISSUE THREAD

**Issue by libzhang** [k8snetworkplumbingwg/multus-cni#1008]
Hi Experts, 
I have a question regarding the expected behavior when doing a network restart. 

1. environment 
 OS: SLES15 SP4
 k8s: rke2 1.24
2.  problem scenario descrpion:
    1) using multus to attach a secondary network macvlan interface to a pod as net1. 
    macvlan master interface is host interface (eth1) 
     2) doing a "systemctl restart network"  on host.

what's the expected behavior in this scenario for the macvlan interface in  pod ?  
will this interface net1 disappear and re-appear in pod ?  or just it is down ? 

from my testing,  the net1 interface in pod is disappeared and never return back after the master interface (eth1) is up again. 
Is it the expected behaviour ?

**Comment by dougbtv** [comment]
So, Multus only acts on CNI ADD/DEL/VERSION etc, it doesn't act on a network restart.

This isn't specifically a multus issue.

However, it's interesting -- what could be done when the veth for macvlan is removed? Can that be automatically repaired. It's an interesting.

The maintainer's have discussed this before regarding bridge CNI.

Keeping open for discussion generation.

**Comment by libzhang** [comment]
Thanks @dougbtv.  Yes, it looks veth pair on master interface(eth1) is removed when host network restart.  and same question is should it be recovered after host interface (eth1) up again ?
