### ISSUE TITLE
CVE Reduction / Base Container Image Change

### ISSUE THREAD

**Issue by jdn5126** [k8snetworkplumbingwg/multus-cni#1017]
**What would you like to be added**:
Scanning the latest multus-cni image returns 47 CVEs, all in the `python:slim` base image.

I did some experimenting and found that switching the base image to a distroless image, namely `gcr.io/distroless/static-debian11`, resolves all of the CVEs and significantly decreases the image size.

A downside of moving to the distroless image is that a shell would no longer be available in the pod, but this should be alright as we can launch an ephemeral container in the pod to debug with a shell. We would also have to rewrite the `entrypoint.sh` script in golang.

I would be happy to take on this effort if y'all approve. I would start by adding a golang entrypoint, then move the dockerfiles to use distroless image.

**Why is this needed**:
to mitigate existing CVEs in base image and decrease the surface area for future CVEs

**Comment by s1061123** [comment]
Thank you for the issue. I understand the situation and agree that changing to distroless reduces them.
Let me work on that.

BTW, ephemeral container could only attach the PID namespace and hard to attach the container mount namespace, so ephemeral container does not help to troubleshooting our case because we may want to check some logs or files (i.e. multus binary in container)...

**Comment by jdn5126** [comment]
Ah I was not aware of that limitation with ephemeral containers, thanks for explaining @s1061123 ! I guess we could package a small binary with multus that could be invoked to print some debug state to help in that case.

What do you think about parameterizing the base image? With `entrypoint.sh` rewritten to golang, the choice of base image can be left up to the installer. If the installer really wants a shell, they can continue to use `python-slim`, and for those more CVE conscious, they can use distroless. And multus can choose whichever default y'all think is best.

Let me know if you would like any help with the implementation, testing, or review, and thank you for taking this up!

**Comment by jdn5126** [comment]
@s1061123 any update on this effort?

**Comment by s1061123** [comment]
Regarding non server (we call thin pluign), we change to distroless in #1054 . We will address server image in further.

**Comment by jdn5126** [comment]
> Regarding non server (we call thin pluign), we change to distroless in #1054 . We will address server image in further.

Oh awesome, thank you! I think #1054 covers everything we needed anyway, as we use thin plugin, but definitely great to add to both. So this will be available in the next 4.x release then, right?
