### ISSUE TITLE
How to integrate multus with calico where we use calico as default CNI

### ISSUE THREAD

**Issue by samar08** [k8snetworkplumbingwg/multus-cni#1019]
I have tried to integrate multus with calico(default CNI) but multus is not working as expected. I am using calico version 3.24.5. Can someone please help me resolve the issue.

**Comment by nicklesimba** [comment]
Hello! Can you please provide what multus version you are using, and provide more details on your procedure and also what was unexpected about multus? Thank you :)

**Comment by samar08** [comment]
Hi, the multus version i am using is 3.7. I want to attach a macvlan network interface to one of my pod. But I am not able to do that. Can you please provide me the working steps to integrate multus with calico (as default CNI).

**Comment by nicklesimba** [comment]
Hello, our community has a reference deployment repository to help with installations of different CNI plugins, here is one for multus and calico. 
https://github.com/k8snetworkplumbingwg/reference-deployment/tree/master/multus-calico
Feel free to ask reference-deployment repository if you have any other deployment related questions.
