### ISSUE TITLE
can someone from the admin team send me an invite to join the slack channel

### ISSUE THREAD

**Issue by samar08** [k8snetworkplumbingwg/multus-cni#1020]
can someone from the admin team send me an invite to join the slack channel. My mail msdevops123@gmail.com . Work email: am-samarasimha.reddy@hpe.com

**Comment by nicklesimba** [comment]
I requested that you be added to the NPWG slack.

**Comment by hectorgpuy** [comment]
Could some1 please add me too? or send me an invite please? my email is hectorgpuy@protonmail.com thanks in advance!

**Comment by maiqueb** [comment]
Can't you generate an invite for yourself via https://github.com/k8snetworkplumbingwg/community#contact ? (there's a link to slack there).

**Comment by abasitt** [comment]
@maiqueb the link doesn't work. can someone please add me too. a.basit3028@gmail.com

![image](https://user-images.githubusercontent.com/59034807/234248114-826a884f-cdee-4723-a98d-420c7dae5d39.png)
