### ISSUE TITLE
Multicast messages not receivable if sender and receiver pods are running on other AWS EKS nodes

### ISSUE THREAD

**Issue by Johannes1509** [k8snetworkplumbingwg/multus-cni#1021]
Hello,
I am trying to establish a multicast communication between pods of an AWS EKS cluster using Multus cni. I use the CLI tool "ssmping" (available for ubuntu) to check if a multicast connection is possible.

If I place the server and the client pod on one node, I can send and receive multicast and unicast messages successfully.

If I place the two pods on separate cluster nodes, then I can send/receive unicast messages but not multicast messages.

What could be the reason that a unicast but no multicast connection is possible?

**Comment by nicklesimba** [comment]
This looks like it may be an AWS EKS issue, and not a multus issue. Multus will only be responsible for creating the network interface, hence multus does not care about the network itself. In this case, multicast traffic is about network issues and AWS EKS manages the network. Please ask AWS EKS about that?

**Comment by NeilJ12** [comment]
hello guy, please I want to know how do you succeed to do multicast on the same nodes with multus.
For your issue maybe if you put a transit gateway it would work
