### ISSUE TITLE
Unable to communicate to the interface associated with the pod from the host node.

### ISSUE THREAD

**Issue by kasisubbarayudu** [k8snetworkplumbingwg/multus-cni#1023]
![second pod](https://user-images.githubusercontent.com/110520224/213979291-7b342e88-cf76-45d0-98cb-515f749187a2.png)

We are using calico networking model. We are able to communicate to the pod's primary interface but unable to get reply from the second interface.
![image](https://user-images.githubusercontent.com/110520224/213979567-eddb3873-d511-4ff7-af55-7523a04ab59f.png)
Pod's route table info:- 
![image](https://user-images.githubusercontent.com/110520224/213979770-33c0860d-1d8f-4070-a5e7-7e8233137b47.png)

**Comment by dougbtv** [comment]
I think this might be a ipvlan issue, definitely reference your setup with this article: https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking

**Comment by maiqueb** [comment]
Can you paste your net-attach-def and pod configuration ?
