### ISSUE TITLE
Build multi-arch thick plugin container image

### ISSUE THREAD

**Issue by willthames** [k8snetworkplumbingwg/multus-cni#1024]
**What would you like to be added**:

Multi-arch builds of the thick plugin - I can see that the github actions build the thin plugin across multiple architectures, and a multi-arch manifest is created. But the thick plugin is only built for amd64.

**Why is this needed**:
So that I can use multus in a multi-architecture kubernetes cluster

**Comment by s1061123** [comment]
Hi, thank you for the issue. Currently we don't have platform to verify that. Appreciated if you test the thick plugin images.

Could you please let me know which platform you can verify? I will create local build image for that and ask you to test.
If it works, then I will add this image to CI pipeline.

**Comment by willthames** [comment]
@s1061123 I can verify arm64

**Comment by f2calv** [comment]
I can also verify ARM64 architecture isn't in the manifest, thick won't install on my rp4. Easy to test with;

```bash
> docker pull --platform linux/arm64 ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
snapshot-thick: Pulling from k8snetworkplumbingwg/multus-cni
no matching manifest for linux/arm64 in the manifest list entries
```
Thanks in advance if you could look into this!

**Comment by nvollmar** [comment]
The `v4.0.0-alpha` tag has a working thick image for arm64, sadly the final release v4.0.0 does not.

**Comment by nvollmar** [comment]
This issue is still unresolved
