### ISSUE TITLE
cni 1.0.0

### ISSUE THREAD

**Issue by liyimeng** [k8snetworkplumbingwg/multus-cni#1026]
Hi, as I understand, 4.0 now is in master. However according to the text here

https://github.com/k8snetworkplumbingwg/multus-cni/blob/e692127d19623c8bdfc4d391224ea542658b584c/deployments/multus-daemonset-thick.yml#L158

We are still on cni 0.3.1. I am wondering when we will bump into cni 1.0.0, what is really blocker here? 

I do notice in #879 that @s1061123 point out 1.0.0 dose not add much new features. but in my case, I have large set of nodes running k3s, which only take cni 1.0.0. Currently I have to maintains my own fork on top on 3.9. 

I don't want to continue this on 4.0, will this possible? when 4.0 will be release? will it come with cni 1.0.0

**Comment by s1061123** [comment]
Not all cni plugin does not support 1.0.0 yet, hence we don't change the value 'cni-version' option for now.
But this does not mean that multus 4.0(i.e. main branch) does not support CNI 1.0.0 Actually multus main branch supports 1.0.0. 

Please change the daemonset yaml arguments and use it, we think that such daemonset config change should be done by users (as a part of configuration). 

We have reference-deployment repo (https://github.com/k8snetworkplumbingwg/reference-deployment) for multus deployment scenarios, so creating k3s deployment scenario in the repo could be one idea, I suppose.

**Comment by liyimeng** [comment]
Thanks @s1061123 
When we will release 4.0?
