### ISSUE TITLE
multus pods crash-looping (thin version) when the default network CNI config is >= 0.4.0 

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/multus-cni#1060]
**What happend**:
The multus pods (deployed in the multi-homing lane) are crash-looping when deployed from the reference [thin plugin version](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml):
```
kubectl get pods -A
NAMESPACE            NAME                                        READY   STATUS             RESTARTS        AGE
kube-system          coredns-787d4945fb-6xslx                    1/1     Running            0               6m4s
kube-system          coredns-787d4945fb-k5hlg                    1/1     Running            0               6m4s
kube-system          etcd-ovn-control-plane                      1/1     Running            0               6m20s
kube-system          kube-apiserver-ovn-control-plane            1/1     Running            0               6m17s
kube-system          kube-controller-manager-ovn-control-plane   1/1     Running            0               6m17s
kube-system          kube-multus-ds-5z29h                        0/1     CrashLoopBackOff   5 (73s ago)     4m40s
kube-system          kube-multus-ds-6tt4b                        0/1     CrashLoopBackOff   5 (85s ago)     4m40s
kube-system          kube-multus-ds-d9jmz                        0/1     CrashLoopBackOff   5 (87s ago)     4m40s
kube-system          kube-scheduler-ovn-control-plane            1/1     Running            0               6m19s
local-path-storage   local-path-provisioner-c8855d4bb-xnjcn      1/1     Running            0               6m4s
ovn-kubernetes       ovnkube-db-79f68fcbc5-qbb7q                 2/2     Running            0               4m42s
ovn-kubernetes       ovnkube-master-6c45dc8c48-qfcpf             2/2     Running            0               4m41s
ovn-kubernetes       ovnkube-node-7s4l6                          3/3     Running            1 (4m23s ago)   4m41s
ovn-kubernetes       ovnkube-node-cs26v                          3/3     Running            1 (4m23s ago)   4m41s
ovn-kubernetes       ovnkube-node-z22xd                          3/3     Running            1 (4m22s ago)   4m41s
ovn-kubernetes       ovs-node-cdb2n                              1/1     Running            0               4m41s
ovn-kubernetes       ovs-node-hgghw                              1/1     Running            0               4m41s
ovn-kubernetes       ovs-node-jx2bm                              1/1     Running            0               4m41s
```

These are the logs from one of those pods:
```
kubectl logs -nkube-system kube-multus-ds-5z29h 
Defaulted container "kube-multus" out of: kube-multus, install-multus-binary (init)
kubeconfig is created in /host/etc/cni/net.d/multus.d/multus.kubeconfig
kubeconfig file is created.
failed to create multus config: Multus cni version is "0.3.1" while master plugin cni version is "0.4.0"
```

**What you expected to happen**:
The multus pods to properly run.

**How to reproduce it (as minimally and precisely as possible)**:
Run the [ovn-kubernetes kind script](https://github.com/ovn-org/ovn-kubernetes/blob/master/contrib/kind.sh) with multi-network enabled:
```bash
./kind.sh --multi-network-enable
```

**Anything else we need to know?**:
This is the [yaml](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml) used to deploy multus in the cluster.

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
This is expected because multus-cni expects that multus cniVersion and delegated CNI version should be same. But for userbility, we may need to think about improvements of that. let me think about that.

**Comment by maiqueb** [comment]
Yeah, that's OK. 

It seems the ovn-k kind automation was relying on a bug then.

When we provision a [pinned version](https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/6c2e09529bcfdf2f5b7b7999df6ee43080d8bd57/deployments/multus-daemonset.yml) of the spec (feat. entrypoint.sh) it works.

@s1061123 I'm unsure if you need to improve this entrypoint thing: the way I see it, everyone should be happier with it gone.
