### ISSUE TITLE
Moving image tags broke existing Multus installations

### ISSUE THREAD

**Issue by werdnum** [k8snetworkplumbingwg/multus-cni#1065]
**What happend**:
When I woke up this morning, my cluster was totally broken. It turns out that the example manifests just reference the `snapshot` or `stable` tag, and the new version doesn't work the same way as the old version. So anyone who had happily been running Multus for however long suddenly found themselves with a broken cluster.

The initial symptom was that there is no such thing as `cp` in the image.

**What you expected to happen**:

Cluster that has been working fine for months does not suddenly break.

Presumably the way to do this would be to have version tags instead of just `stable` and `snapshot`.

**How to reproduce it (as minimally and precisely as possible)**:

Download https://raw.github.com/k8snetworkplumbingwg/multus-cni/33c0d1bd86b22106442c84b8d9e28945cf6182e3/deployments/multus-daemonset.yml

Apply the manifest (maybe you need to set the image tag to `snapshot` to get the breakage).

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
https://hub.docker.com/layers/nfvpe/multus/snapshot/images/sha256-358c13bd4680f1c3f2740443fcaa8f27f07c94c817e0c1650346cfa1e1ec0114?context=explore
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0-rc1+k3s2", GitCommit:"bc6bebc99868a053636b10ac86456f9e70a34091", GitTreeState:"clean", BuildDate:"2023-01-04T22:57:19Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/arm64"}
- Primary CNI for Kubernetes cluster:
Flannel
- OS (e.g. from /etc/os-release):
Ubuntu 22.04
- File of '/etc/cni/net.d/'
I don't think this is relevant
- File of '/etc/cni/multus/net.d'
I don't think this is relevant
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
I don't think this is relevant
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
I don't think this is relevant
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
Hi,

`snapshot` images always up-to-date image from `master` branch hence sometimes we change deployment style. This week, we introduce 'distroless image' for multus container image to master branch, so it requires to update multus-daemonset.yml. 
If you use old multus-daemonset.yml to deploy, it may be failed. Please update `multus-daemonset.yml` to latest master.

In addition, multus-cni currently use 'Github Container Image Registory', not docker hub (nfvpe/multus). So please use multus image from: https://github.com/k8snetworkplumbingwg/multus-cni/pkgs/container/multus-cni

Regarding `stable` image, we don't update it so it does not changed, so you can use previous multus-daemonset.yml to install `stable` image.

**Comment by werdnum** [comment]
Any chance you have the hash of the previous versions of 'snapshot' handy? Can I recommend hardcoding it in the configuration (or using a proper version numbering system) so that there's a plausible upgrade path?

I was using `snapshot` in my cluster because `stable` no longer worked because of the CNI version issue, so I'm really not sure what I was supposed to do - I can't update my deployment manifest atomically with updating to the new image unless there's some kind of appropriate tag to pull in that isn't going to change in incompatible ways.

I ended up uninstalling Multus - the new version, even with the new daemonset configuration, used so much CPU that the cluster became unusable. There were 100 little `multus` processes running and chewing through CPU/RAM, and I couldn't use the thick client because it's not compiled for `arm64`.

**Comment by s1061123** [comment]
`snapshot` image is always build when the pull request/commit is merged, hence we cannot hardcode it to yaml file because image push will be finalized after git merge and we cannot hardcode the hash that is not created yet. So if you want to use specific version from master branch, you need to keep the hash that you want to run because master branch is actively developped. If you want to run specific vesrion, you need to use specific version, such as v3.9.3.

> I ended up uninstalling Multus  - the new version, even with the new daemonset configuration, used so much CPU that the cluster became unusable.

I'm sorry to hear that but thank you for using multus. BTW, if  you don't mind, please share your CPU/RAM stats output of above, for further improvement of multus?

**Comment by dougbtv** [comment]
If you were tracking the stable image, the last one tagged with a version tag is our 4.0 alpha...

https://github.com/k8snetworkplumbingwg/multus-cni/pkgs/container/multus-cni/47662519?tag=v4.0-alpha

https://github.com/k8snetworkplumbingwg/multus-cni/pkgs/container/multus-cni/47662357?tag=v4.0.0-alpha-thick

Ugh, sorry to hear that you had that problem with the snapshot changing to require changes to the yaml :( Bummer. My apologies as well.

We do release tagged images with a `vX.Y.Z` which I'd definitely recommend. Also the `stable` shortcut image tag should be the last z-stream, however, we're in the process of a major version change.

Also fwiw, we are planning on releasing an official 4.0 build in the near future (current plan is this upcoming Thursday, but we do have some outstanding items that need to be addressed beforehand)
