### ISSUE TITLE
Could someone please send me an invite to the Slack channel?

### ISSUE THREAD

**Issue by hectorgpuy** [k8snetworkplumbingwg/multus-cni#1075]
My email is hectorgpuy@protonmail.com thanks in advance!

**Comment by nicklesimba** [comment]
The link still works for me.

**Comment by maiqueb** [comment]
> The link still works for me.

You should try it without any cookies (I suggest opening an incognito / private window).

This is tracked in https://github.com/k8snetworkplumbingwg/community/issues/20

**Comment by dougbtv** [comment]
Permanent invite link: https://join.slack.com/t/npwg-team/shared_invite/zt-1u2vmsn2b-tKdOokdPY73zn9B32JoAOg
