### ISSUE TITLE
FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown

### ISSUE THREAD

**Issue by luozp99** [k8snetworkplumbingwg/multus-cni#1076]
[root@localhost ~]# kubectl describe pod samplepod
Name:         samplepod
Namespace:    default
Priority:     0
Node:         k8s-master/172.20.52.113
Start Time:   Thu, 20 Apr 2023 16:03:58 +0800
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: macvlan-conf
Status:       Pending
IP:
IPs:          <none>
Containers:
  samplepod:
    Container ID:
    Image:         alpine
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/ash
      -c
      trap : TERM INT; sleep infinity & wait
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gpg8z (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-gpg8z:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               12s   default-scheduler  Successfully assigned default/samplepod to k8s-master
  Normal   AddedInterface          11s   multus             Add eth0 [10.244.0.20/24] from cbr0
  Warning  FailedCreatePodSandBox  10s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "b124285607cad64d424e99a9e0d81712edd86d2c052bd2161935f2d1ac741db0" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: [default/samplepod/:multus-cni-network]: error adding container to network "multus-cni-network": [default/samplepod/:multus-cni-network]: error adding container to network "multus-cni-network": [default/samplepod/:macvlan-conf]: error adding container to network "macvlan-conf": Link not found, failed to clean up sandbox container "b124285607cad64d424e99a9e0d81712edd86d2c052bd2161935f2d1ac741db0" network for pod "samplepod": networkPlugin cni failed to teardown pod "samplepod_default" network: DelegateDel: error invoking DelegateDel - "macvlan": error in getting result from DelNetwork: Link not found / DelegateDel: error invoking DelegateDel - "multus": error in getting result from DelNetwork: DelegateDel: error invoking DelegateDel - "macvlan": error in getting result from DelNetwork: Link not found / DelegateDel: error invoking DelegateDel - "multus": error in getting result from DelNetwork: DelegateDel: error invoking DelegateDel - "macvlan": error in getting result from DelNetwork: Link not found]
  Normal   SandboxChanged          10s   kubelet            Pod sandbox changed, it will be killed and re-created.

**Comment by luozp99** [comment]
[root@localhost ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.20.52.1     0.0.0.0         UG    100    0        0 ens192
0.0.0.0         192.168.10.1    0.0.0.0         UG    101    0        0 ens224
10.244.0.0      0.0.0.0         255.255.255.0   U     0      0        0 cni0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.52.0     0.0.0.0         255.255.255.0   U     100    0        0 ens192
192.168.10.0    0.0.0.0         255.255.255.0   U     101    0        0 ens224

**Comment by luozp99** [comment]
[root@localhost ~]# cat multus-network.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth224",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.10.0/24",
        "rangeStart": "192.168.10.200",
        "rangeEnd": "192.168.10.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
      "gateway": "192.168.10.1"
      }
    }'

**Comment by nicklesimba** [comment]
Hi, would you mind explaining what the problem is? Additionally, can you provide the yaml for your pod as well?
