### ISSUE TITLE
Unable to create Pods

### ISSUE THREAD

**Issue by rsidhaarth** [k8snetworkplumbingwg/multus-cni#1077]
**What happend**:

Installed Multus Thick and Whereabouts. Default CNI is Flannel.

I have also mounted the

```
           - name: flannel-subnet
              mountPath: /run/flannel
```

```
        - name: flannel-subnet
          hostPath:
            path: /run/flannel
```

**What you expected to happen**:

Pods needs to get creaed

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/16856248/233794474-3c1d0f63-da80-4d9d-8a50-2109be9f2a0b.png)

**Environment**:

- Multus version : Lastest

- Kubernetes version (use `kubectl version`): 
 
![image](https://user-images.githubusercontent.com/16856248/233794504-5e18ce24-ae66-4469-91c2-b0dc269b42b5.png)

- Primary CNI for Kubernetes cluster: Flanner

- OS (e.g. from /etc/os-release): Talos

- File of '/etc/cni/net.d/'

![image](https://user-images.githubusercontent.com/16856248/233794533-2e9fb79d-4ccb-43c6-8bf9-1cc12b6b1da3.png)

- File of '/etc/cni/multus/net.d' - There is no such directory

- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)

![image](https://user-images.githubusercontent.com/16856248/233794622-b6a83caf-423d-4abf-a9c4-48cc61672996.png)

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)

![image](https://user-images.githubusercontent.com/16856248/233794660-521b2f01-99a9-442f-b002-6898fbd0b44d.png)

- Other log outputs (if you use multus logging)

**Comment by dougbtv** [comment]
Does this happen with all pods or just pods with annotations?

**Comment by weizhoublue** [comment]
same issue happened on macvlan or cilium in a kind cluster

it works well for running pod, but after installing multus and restart pod, the issue happened, some restarting pods may always stuck, some pods may succeed to run after several times of failure

```
error adding container to network "cilium": failed removing interface "eth0" from namespace "/var/run/netns/cni-7770a23d-64b5-1c48-4a7e-986d0e970613": Failed to open current namespace: failed to Statfs "/proc/2562/task/2562/ns/net": no such file or directory
```

**Comment by maxpain** [comment]
The same problem with Cilium
<img width="1435" alt="image" src="https://github.com/k8snetworkplumbingwg/multus-cni/assets/5875582/9f85c3cd-4690-4778-bdb6-21a160204160">

**Comment by cybercoder** [comment]
Same here. I've installed Multus thick on Talos v1.5.3 kubernetes 1.28 and the error happens for kubevirt vms event assigns no NetAttachDefinition to them.
