### ISSUE TITLE
Support Arm64 arch snapshot-thick image on Arm64

### ISSUE THREAD

**Issue by zhlhahaha** [k8snetworkplumbingwg/multus-cni#1079]
Hi, all. I am trying to deploy the multus-cni on Arm64 server. And I find the image, `ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick` that used in `deployments/multus-daemonset-thick.yml`, is not support.

Can we build multi-arch snapshot image? Thanks.

**Comment by nicklesimba** [comment]
Hi, please see https://github.com/k8snetworkplumbingwg/multus-cni/pull/1027 for related discussion.
