### ISSUE TITLE
pod creation stuck at look

### ISSUE THREAD

**Issue by rsidhaarth** [k8snetworkplumbingwg/multus-cni#1082]
**What happend**:

pod stuck in look where it is trying to add the interface

![image](https://user-images.githubusercontent.com/16856248/234684154-ed62de5a-817e-46c8-847f-38426989cf0c.png)

**What you expected to happen**:

pod should get created with secondary interface

**How to reproduce it (as minimally and precisely as possible)**:

I will explain what I did, I created two networks with whereabouts plugin and then created an ceph cluster. And then restarted the nodes (hard restart)

After this, ceph pods stuck in look. So deleted the ceph deployment and then removed the whereabout as well. I created normal network with host-local to test it. And then created pod with newly created host-local network, still it stuck in loop.

**Environment**:

- Multus version: Latest
- Kubernetes version (use `kubectl version`):
![image](https://user-images.githubusercontent.com/16856248/234684358-64feed47-977b-4d5c-a024-ccc3668ccf01.png)
- Primary CNI for Kubernetes cluster: Flannel
- OS (e.g. from /etc/os-release): TalOS
- File of '/etc/cni/net.d/'
![image](https://user-images.githubusercontent.com/16856248/234684484-2b2f2833-0217-48e2-8a20-a2c60e2876c8.png)
- File of '/etc/cni/multus/net.d'
![image](https://user-images.githubusercontent.com/16856248/234684649-9fb6cee0-43e7-4abb-a624-be7278ce44ee.png)
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
![image](https://user-images.githubusercontent.com/16856248/234684939-5f729416-e05b-4178-a5e2-a1bcbb818342.png)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
![image](https://user-images.githubusercontent.com/16856248/234685221-0112aa95-7bdf-4039-8ef6-c4bae0ff7777.png)

- Other log outputs (if you use multus logging)

**Comment by lgarcia11** [comment]
Still relevant
