### ISSUE TITLE
when pod.spec.hostNetwork=true, multus does not seem to process pod

### ISSUE THREAD

**Issue by dbainbri-ciena** [k8snetworkplumbingwg/multus-cni#1091]
I have a pod where I am attempting to attach a secondary network with multus. when the pod has hostNework=false it all works well. when hostNetwork=true it is as if multus is ignoring the annotation and the secondardary network does not get added.

Should multus work in this situation?

**Comment by dougbtv** [comment]
I think with hostNetwork is true, it's kind of outside of the purview of CNI, so... yeah unfortunately doesn't work. Thanks for asking, though!
