### ISSUE TITLE
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox ; error getting pod: Unauthorized

### ISSUE THREAD

**Issue by HILLJAY1019** [k8snetworkplumbingwg/multus-cni#1094]
When I uninstall mutlus, the pod cannot be created and remains in the ContainerCreating state. Will Mutlus change sa or somethingseles?

**pod logs** 
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               116s  default-scheduler  Successfully assigned default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6 to gyh03v.contro.shjt2.qianxin-inc.cn
  Warning  FailedCreatePodSandBox  115s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "bc5e100744cc3e7524cb98ba0e056cb81bad97b85a8c9441602bf92ef4edfff5": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  100s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "eddb508f701984b43bb50a4df0d921e76baed6821314e6a896fef79aa0eacb90": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  89s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5a500e8e09a097cd7b82bb21a9f4cbd0500fffc89204a3cc493f4bc6ec2328e9": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  75s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "a48bfc81916df9c0b918d29ea3bb075e3b7536888f57270d9887365b3e224b2d": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  63s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "03346c6d37f341ad97737beb23dde012866b0285d0cc1d02f92c60ecbb4e03bc": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  49s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "aeaede2f1275bcdb72e9d27df729a2f5f2a9e720b253778dcfce3a09aef1c9f2": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  35s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8672fd67a1eb88fc5cc36a6112bed9a180fabf411d1d1da64513aff422473291": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  23s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f309b0c7c2c37997ecfdbc6460378330aac64b2fd5049bdea1ac7006cfea1905": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized
  Warning  FailedCreatePodSandBox  8s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "033c0a3e7aa82feb678b4143d6fa3e8aa645e12e9058493e14b2f74ba4183da3": Multus: [default/preferred-nodeaffinity-deploy-8599b9d4c8-5czz6/a47656c9-a43f-4f78-b337-fde316150fa9]: error getting pod: Unauthorized

**Comment by nicklesimba** [comment]
I believe this is happening after uninstalling because you are leaving the configuration file on disk. Kubelet will still invoke multus and multus won't have the SA to authenticate in the API. You can resolve this by removing the config file and the binary from disk.
