### ISSUE TITLE
multus interface IP not reachable from pods on different nodes

### ISSUE THREAD

**Issue by satishh1988** [k8snetworkplumbingwg/multus-cni#1097]
deployed k8s cluster on esxi node with one master and 2 worker nodes. we have flannel and multus CNI's deployed for 2nd interface. pods on the same worker node is reachable via the the multus interface IP's. but the pods on 2nd worker node is not reachable via multus interface IP's.

can you please guide here to make this communication happen

multus deployed using the latest multus-daemonset-thick.yml. couldnt get the exact version details.

kubectl -n kube-system exec -it kube-multus-ds-shs9x -c kube-multus -- /usr/src/multus-cni/bin/multus --version
multus: version:(clean), commit:0c37bb043c704a730535a011a19c0bde36c1463b, date:2023-05-02T18:55:22+00:00

**network definition yaml content below**

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus
spec:
  config: '{
            "cniVersion": "0.3.1",
            "type": "macvlan",
            "master": "ens192",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "192.168.50.0/24",
                         "rangeStart": "192.168.50.2",
                         "rangeEnd": "192.168.50.150",
                         "gateway": "192.168.50.1"
                    } ]
                ]
            }
        }'

**pod route and network details:**

[@pod-case-02 /]# ip r s
default via 10.244.1.1 dev eth0 
10.244.0.0/16 via 10.244.1.1 dev eth0 
10.244.1.0/24 dev eth0 proto kernel scope link src 10.244.1.11 
192.168.50.0/24 dev net1 proto kernel scope link src 192.168.50.6 
[root@pod-case-02 /]# 

x@xxx-1:/# kubectl exec -it pod-case-01 -- ip a s net1
3: net1@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 76:98:7c:f0:35:1d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.50.5/24 brd 192.168.50.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::7498:7cff:fef0:351d/64 scope link 
       valid_lft forever preferred_lft forever

x@xxx-1:/# kubectl exec -it pod-case-02 -- ip a s net1
3: net1@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 2a:d1:2c:3a:f7:9a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.50.6/24 brd 192.168.50.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::28d1:2cff:fe3a:f79a/64 scope link 
       valid_lft forever preferred_lft forever

xxx@pod-case-02 /]# ping 192.168.50.5
PING 192.168.50.5 (192.168.50.5) 56(84) bytes of data.
64 bytes from 192.168.50.5: icmp_seq=1 ttl=64 time=0.070 ms
64 bytes from 192.168.50.5: icmp_seq=2 ttl=64 time=0.034 ms
64 bytes from 192.168.50.5: icmp_seq=3 ttl=64 time=0.031 ms

**Comment by nicklesimba** [comment]
This is likely happening because you are using host-local as your IPAM type, we suggest whereabouts instead.

See the documentation: https://www.cni.dev/plugins/current/ipam/host-local/#overview

"It stores the state locally on the host filesystem, therefore ensuring uniqueness of IP addresses on a single host."
