### ISSUE TITLE
error configuring pod networking: Multus: error loading netconf: LoadNetConf: at least one delegate/clusterNetwork must be specified

### ISSUE THREAD

**Issue by kouamdo** [k8snetworkplumbingwg/multus-cni#1099]
hi verybody
Since i'm trying multus because to have another network interface knowing that i'm using cilium as a primary CNI.
when i wanted to create pod , specifying like this :

```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-multus
spec:
  config: '{
  "cniVersion": "0.3.0",
  "type": "multus-shim",
  "additional": "information",
  "delegate": {"isDefaultGateway": true}
    }'
EOF


cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf,macvlan-conf-multus
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
EOF
```

i receive this kind of error : `ERRORED: error configuring pod [default/samplepod] networking: Multus: error loading netconf: LoadNetConf: at least one delegate/clusterNetwork must be specified`

 so i want to have more interface by using cilium as primary cni

So , i have installed cilium 1.13 inside kind in linux amd64

i have this inside  some file : 

```
root@k8s-ashburn:~# docker exec -it test-control-plane cat  /etc/cni/net.d/00-multus.conf  |jq
{
  "cniVersion": "0.3.1",
  "logLevel": "verbose",
  "name": "multus-cni-network",
  "clusterNetwork": "/host/etc/cni/net.d/05-cilium.conf",
  "type": "multus-shim",
  "socketDir": "/host/run/multus/"
}
root@k8s-ashburn:~# docker exec -it test-control-plane cat  /etc/cni/net.d/05-cilium.conf
{
  "cniVersion": "0.3.1",
  "name": "cilium",
  "type": "cilium-cni",
  "enable-debug": false,
  "log-file": "/var/run/cilium/cilium-cni.log"
}
```
so what should i do to fix it ?

thank you

**Comment by kouamdo** [comment]
help @s1061123  , @dougbtv

**Comment by nicklesimba** [comment]
Hi, haven't had a chance to try and reproduce this yet, but the issue may be a relative path issue depending on how things are mounted (try without /host prefix for filepath)

**Comment by kouamdo** [comment]
i have tried According to [parameter](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/configuration.md) , but nothing . i have this kind of error : 

`failed to get clusterNetwork/defaultNetworks: GetDefaultNetworks: failed to get clusterNetwork /etc/cni/net.d/05-cilium in namespace kube-system`
