### ISSUE TITLE
nccl-test between two pods,  with macvlan type on roce-k8s-cluster,but it not work.

### ISSUE THREAD

**Issue by Jokerll** [k8snetworkplumbingwg/multus-cni#1100]
i have two pods, one of them with show_gids:
DEV	PORT	INDEX	GID					IPv4  		VER	DEV
---	----	-----	---					------------  	---	---
mlx5_4	1	4	0000:0000:0000:0000:0000:ffff:ac14:0101	172.20.1.1  	v1	net1
mlx5_4	1	5	0000:0000:0000:0000:0000:ffff:ac14:0101	172.20.1.1  	v2	net1
but the other:
DEV	PORT	INDEX	GID					IPv4  		VER	DEV
---	----	-----	---					------------  	---	---
mlx5_4	1	6	0000:0000:0000:0000:0000:ffff:ac14:0102	172.20.1.2  	v1	net1
mlx5_4	1	7	0000:0000:0000:0000:0000:ffff:ac14:0102	172.20.1.2  	v2	net1.

so first,why INDEX changes?
i execute " ib_write_bw -d mlx5_4 -x 4" on one pod , and "ib_write_bw -d mlx5_4 -x 6 172.20.1.1" on the other pod, it works.
then i run nccl-test, i chang /etc/environment to "export NCCL_IB_GID_INDEX=5"  and  "export NCCL_IB_GID_INDEX=7" on  two pods,but it does not work ,why?please help.

alg-test-master-0:46312:46312 [0] NCCL INFO Bootstrap : Using net1:172.20.1.1<0>
alg-test-master-0:46312:46312 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
alg-test-master-0:46312:46312 [0] NCCL INFO cudaDriverVersion 11070
NCCL version 2.13.4+cuda11.3
alg-test-master-0:46312:46318 [0] NCCL INFO NET/IB : Using [0]mlx5_4:1/RoCE [RO]; OOB net1:172.20.1.1<0>
alg-test-master-0:46312:46318 [0] NCCL INFO Using network IB
alg-test-master-1:12114:12114 [0] NCCL INFO cudaDriverVersion 11070
alg-test-master-1:12114:12114 [0] NCCL INFO Bootstrap : Using net1:172.20.1.2<0>
alg-test-master-1:12114:12114 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
alg-test-master-1:12114:12119 [0] NCCL INFO NET/IB : Using [0]mlx5_4:1/RoCE [RO]; OOB net1:172.20.1.2<0>
alg-test-master-1:12114:12119 [0] NCCL INFO Using network IB
alg-test-master-1:12114:12119 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,00000000,ffffffff
alg-test-master-0:46312:46318 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,00000000,ffffffff,00000000
alg-test-master-0:46312:46318 [0] NCCL INFO Channel 00/02 :    0   1
alg-test-master-0:46312:46318 [0] NCCL INFO Channel 01/02 :    0   1
alg-test-master-0:46312:46318 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
alg-test-master-1:12114:12119 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
alg-test-master-0:46312:46318 [0] NCCL INFO Channel 00/0 : 1[51000] -> 0[8e000] [receive] via NET/IB/0
alg-test-master-0:46312:46318 [0] NCCL INFO Channel 01/0 : 1[51000] -> 0[8e000] [receive] via NET/IB/0
alg-test-master-0:46312:46318 [0] NCCL INFO Channel 00/0 : 0[8e000] -> 1[51000] [send] via NET/IB/0
alg-test-master-0:46312:46318 [0] NCCL INFO Channel 01/0 : 0[8e000] -> 1[51000] [send] via NET/IB/0
alg-test-master-1:12114:12119 [0] NCCL INFO Channel 00/0 : 0[8e000] -> 1[51000] [receive] via NET/IB/0/GDRDMA
alg-test-master-1:12114:12119 [0] NCCL INFO Channel 01/0 : 0[8e000] -> 1[51000] [receive] via NET/IB/0/GDRDMA
alg-test-master-1:12114:12119 [0] NCCL INFO Channel 00/0 : 1[51000] -> 0[8e000] [send] via NET/IB/0/GDRDMA
alg-test-master-1:12114:12119 [0] NCCL INFO Channel 01/0 : 1[51000] -> 0[8e000] [send] via NET/IB/0/GDRDMA
alg-test-master-1:12114:12121 [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 7.
alg-test-master-0:46312:46320 [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 5.

alg-test-master-1:12114:12121 [0] misc/ibvwrap.cc:283 NCCL WARN Call to ibv_reg_mr_iova2 failed with error Cannot allocate memory
alg-test-master-1:12114:12121 [0] NCCL INFO transport/net_ib.cc:871 -> 2
alg-test-master-1:12114:12121 [0] NCCL INFO include/net.h:28 -> 2
alg-test-master-1:12114:12121 [0] NCCL INFO transport/net.cc:600 -> 2
alg-test-master-1:12114:12121 [0] NCCL INFO proxy.cc:968 -> 2
alg-test-master-1:12114:12121 [0] NCCL INFO proxy.cc:996 -> 2

alg-test-master-1:12114:12121 [0] proxy.cc:1097 NCCL WARN [Proxy Service 1] Failed to execute operation Connect from rank 1, retcode 2

alg-test-master-1:12114:12121 [0] transport/net_ib.cc:593 NCCL WARN Error: trying to connect already connected sendComm
alg-test-master-1:12114:12121 [0] NCCL INFO include/net.h:26 -> 3
alg-test-master-1:12114:12121 [0] NCCL INFO transport/net.cc:515 -> 3
alg-test-master-1:12114:12121 [0] NCCL INFO proxy.cc:968 -> 3

alg-test-master-1:12114:12121 [0] proxy.cc:1097 NCCL WARN [Proxy Service 1] Failed to execute operation Connect from rank 1, retcode 3

alg-test-master-1:12114:12119 [0] misc/socket.cc:521 NCCL WARN Net : Connection closed by remote peer 172.20.1.2<42229>
alg-test-master-1:12114:12119 [0] NCCL INFO misc/socket.cc:529 -> 6
alg-test-master-1:12114:12119 [0] NCCL INFO misc/socket.cc:541 -> 6
alg-test-master-1:12114:12119 [0] NCCL INFO proxy.cc:859 -> 6

alg-test-master-1:12114:12119 [0] proxy.cc:862 NCCL WARN Proxy Call to rank 1 failed (Connect)
alg-test-master-1:12114:12119 [0] NCCL INFO transport/net.cc:269 -> 6
alg-test-master-1:12114:12119 [0] NCCL INFO transport.cc:124 -> 6
alg-test-master-1:12114:12119 [0] NCCL INFO init.cc:773 -> 6
alg-test-master-1:12114:12119 [0] NCCL INFO init.cc:1045 -> 6
alg-test-master-1:12114:12119 [0] NCCL INFO group.cc:43 -> 6 [Async thread]
alg-test-master-1:12114:12114 [0] NCCL INFO group.cc:59 -> 6
alg-test-master-1: Test NCCL failure common.cu:1107 'remote process exited or there was a network error'

**Comment by nicklesimba** [comment]
It looks like this is a GPU/hardware lab issue. Closing this out because I don't see how a description of how this relates to multus.
