### ISSUE TITLE
multus release 4.0.0 onwards: causing init failure with failed to create shim task .. "cp": executable file not found

### ISSUE THREAD

**Issue by sar772004** [k8snetworkplumbingwg/multus-cni#1103]
**What happend**:
multus crashed in starting up

(HYP-1-HOST):~ > kubectl describe pod -n  kube-system kube-multus-ds-rsfz5
Name:             kube-multus-ds-rsfz5
Namespace:        kube-system
Priority:         0
Service Account:  multus
Node:             hyp-2.<snipped>
Start Time:       Thu, 25 May 2023 16:09:46 -0400
Labels:           app=multus
                  controller-revision-hash=54cfff589c
                  name=multus
                  pod-template-generation=1
                  tier=node
Annotations:      <none>
Status:           Pending
IP:               5.23.1.2
IPs:
  IP:           5.23.1.2
Controlled By:  DaemonSet/kube-multus-ds
Init Containers:
  install-multus-binary:
    Container ID:  docker://b87273ef707247f4c7bdabdc5a1016a875b024fd3653b90ba5765e9e08f6e66b
    Image:         ghcr.io/k8snetworkplumbingwg/multus-cni:stable
    Image ID:      docker-pullable://ghcr.io/k8snetworkplumbingwg/multus-cni@sha256:825aa0a2572184b1475736f95927c52823e00e3db9930f3d41ce0f6e4bacfc49
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      /usr/src/multus-cni/bin/multus
      /host/opt/cni/bin/multus
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      **_**Message:      failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "cp": executable file not found in $PATH: unknown**_**
      Exit Code:    127

**What you expected to happen**:
Should not crash on stable version

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
(HYP-1-HOST):~ > cat /regressbed/ws/gash/configs/srlinuxk8s/deployment/multus-daemonset.yml| grep image:
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable

(HYP-1-HOST):~ > kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
(HYP-1-HOST):~ > docker images | grep multus
ghcr.io/k8snetworkplumbingwg/multus-cni                                  stable                                     ed70b5729dce   8 hours ago     168MB
ghcr.io/k8snetworkplumbingwg/multus-cni                                  snapshot                                   6a36ad217d3d   7 days ago      168MB

(HYP-1-HOST):~ > cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"

**Comment by samip5** [comment]
It seems commit https://github.com/k8snetworkplumbingwg/multus-cni/commit/dcf92c8e9475ce861d2584314c5021ac80189229 might be the issue, as baseimage was changed.

**Comment by nicklesimba** [comment]
Please try updating to the latest multus-daemonset.yaml. You may be on an older version that references the cp command, like @samip5 suggested.

**Comment by sar772004** [comment]
You are right, will close this issue

**Comment by samip5** [comment]
> Please try updating to the latest multus-daemonset.yaml.

The thick deployment still references cp commands. Should it not?

**Comment by justinmans** [comment]
镜像tag 改一下，用下指定版本的tag 就ok了
