### ISSUE TITLE
Clean up the multus cni configuration file on the host when uninstalling multus

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/multus-cni#1105]
**What would you like to be added**:

Clean up the multus cni configuration file on the host when uninstalling multus.

**Why is this needed**:

When multus is uninstalled, Creating a pod will use the remaining multus cni configuration file on the host, resulting in the pod not being created.

```shell
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               17s   default-scheduler  Successfully assigned kube-system/calico-kube-controllers-856b65b4c6-htqtt to controller-node-1
  Warning  FailedCreatePodSandBox  17s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "71fb567393357642e3109902ae8f0e56043dcd2ef0c884af295dba5a316fefb6": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): failed to send CNI request: Post "http://dummy/cni": dial unix /run/multus/multus.sock: connect: connection refused
  Warning  FailedCreatePodSandBox  5s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "95b4cb532c4c162403756297b58f94486ef8a60ca78babfd55a191bfa8f46c8a": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): failed to send CNI request: Post "http://dummy/cni": dial unix /run/multus/multus.sock: connect: connection refused
```

We need to add prestop to the multus pod to clean up the configuration file on the host when the pod is deleted. I believe v3.9* also has this problem, maybe we need cherry-pick for it.

**Comment by cyclinder** [comment]
refer to https://github.com/cilium/cilium/blob/5bbdb830fb6e19598e7a91d961e948a443968ddd/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L220

**Comment by nicklesimba** [comment]
K8s does not support a way to officially uninstall CNI plugins so we do not support this

**Comment by cyclinder** [comment]
> K8s does not support a way to officially uninstall CNI plugins so we do not support this

I understand this, it would be nice if multus daesonSet was able to clean up the CNI config file on the host before uninstalling. Because residual multus CNI configuration files will cause the pod to fail to start.
