### ISSUE TITLE
Unable to install Multus deamonset

### ISSUE THREAD

**Issue by kouamdo** [k8snetworkplumbingwg/multus-cni#1106]
I'm trying to install multus release-v3 inside by cluster using ;
`kubectl apply -f https://github.com/k8snetworkplumbingwg/multus-cni/raw/release-v3/deployments/multus-daemonset.yml`

i have tried the same command before , and it was fine. But for now ,i'm not able to know the reason of  the failure.

and i have this kind of error :

![image](https://github.com/k8snetworkplumbingwg/multus-cni/assets/39982727/40881626-d936-49c2-b33e-6fc437764ecb)

**Environment**:

- Multus version  : v3
- Kubernetes version: v1.27.2
- Primary CNI for Kubernetes cluster: calico
- OS : Ubuntu 20.04.6 LTS
- File of '/etc/cni/net.d/' : multus.d/multus.kubeconfig
- File of '/etc/cni/multus/net.d' : multus.d/multus.kubeconfig
- NetworkAttachment info : 
```
 apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
```

please , where does the problem coming from?

**Comment by nicklesimba** [comment]
Please check the image field in your multus-daemonset.yaml. If you're using the stable release, it will be pointing to latest release version, which is v4, not v3. If this is the case, please change the tag to one such as v3.0

**Comment by samip5** [comment]
That manifest from `https://github.com/k8snetworkplumbingwg/multus-cni/raw/release-v3/deployments/multus-daemonset.yml` does indeed seem to be using the tag `:stable` so it's trying to use the version that doesn't have cp command available anymore.
