### ISSUE TITLE
Does multus-cni support k8s service already? Especially for Nodeport type

### ISSUE THREAD

**Issue by spark711231** [k8snetworkplumbingwg/multus-cni#1112]
Hi, I have installed multus-cni in my k8s cluster successfully. I am using calico for default network CNI and setup macvlan(bridge mode) mapping to my k8s host 2nd NIC. Then, create two pods for pod's 2nd network communication checking. Everything is working as expected. pod-1 ping pod-2 via 2nd NIC is accessable.

I am wondering if it is possible to expose service NodePort type to pod's second NIC. In other word, user can reach k8s host 2nd NIC(IP:port) from outside of k8s host. If so, how should I achieve that?

Any suggestion or comment is welcome and thanks for your reply.

Here is my multus-cni yaml file for kind: NetworkAttachmentDefinition
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-config
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "log_level": "info",
      "master": "ens8",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "gateway": "192.168.1.1"
      }
    }'
```

**Comment by s1061123** [comment]
Currently multus does not support NodePort service yet and there is no any plan to implement. Several reason we have, such as

- primal reason: multus interface, does not support Kubernetes service yet(not only nodeport, others too)
- security reason: someone uses multus for isolated network. Once if we introduced NodePort then, of course, any pod, including the one that does not have macvlan interface, could get access to the network. This may be unexpected behavior to the user.
- network reason: (based on above case), if the node does not have macvlan network nic, this host NodePort cannot forward the traffic to the network.
