### ISSUE TITLE
Multus thick plugin for arm64 platform

### ISSUE THREAD

**Issue by MGlants** [k8snetworkplumbingwg/multus-cni#1123]
**What would you like to be added**:
Thick plugin doesn't have container for arm64 version
**Why is this needed**:
Control planes and worker nodes runing on arm

**Comment by julianowick** [comment]
That would be very nice for arm/amd mixed clusters like the one we have. I noticed that the thin version provides arm64 images, but it did not work for me, neither in arm nor in amd nodes. I got some permission denied error on the /run/multus/multus.sock file. Anyway, I would be happy if this arm image could be released!

**Comment by nicklesimba** [comment]
Hi, please see #1027 for related discussion.

**Comment by werdnum** [comment]
Looks like that PR is stuck with no progress. I was about to open a new identical issue because I couldn't see any relevant open issues. Worth keeping this open to track that ongoing work?
