### ISSUE TITLE
Host-device interfaces stuck in deleted pod network namespace

### ISSUE THREAD

**Issue by AMacedoP** [k8snetworkplumbingwg/multus-cni#1134]
We recently had a production outage where all our pods, including the multus daemonset, had to be restarted and we noticed that pods using a host-device secondary interface couldn't start because the interface was missing. After troubleshooting we found that the interfaces were still binded to the deleted pod network namespace and multus didn't move it back because the pod was deleted before multus was up, so we had to restart all the nodes where this happened to get the interfaces back in the default namespace.

Is there an automated way to get the interfaces back?

You can reproduce the problem by creating pods with secondary interfaces, scaling down the daemonset and then force deleting the pod

Multus cni version: v3.8

**Comment by nicklesimba** [comment]
Which process are you taking to restart the pod? (oc delete pod vs. ps kill etc)
