### ISSUE TITLE
multus-daemonset-crio.yml broken  unable to start container process  stat /entrypoint.sh: no such file or directory"

### ISSUE THREAD

**Issue by jsalatiel** [k8snetworkplumbingwg/multus-cni#1140]
**What happend**:
Trying to deploy multus using //raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.0.2/deployments/multus-daemonset-crio.yml. Container can not start. 
```
Warning  Failed     1s                 kubelet            Error: container create failed: time="2023-08-14T13:35:26-03:00" l
evel=error msg="runc create failed: unable to start container process: exec: \"/entrypoint.sh\": stat /entrypoint.sh: 
no such file or directory"
```

**What you expected to happen**:
It should start just fine.

**How to reproduce it (as minimally and precisely as possible)**:
Minimal cluster and kubectl apply multus-daemonset-crio.yml 

**Anything else we need to know?**:
Is multus-daemonset-crio.yml  still required for clusters using crio? Or should I just use multus-daemonset.yml ?

**Environment**:

- Multus version: 4.0.2
- Kubernetes version (use `kubectl version`): v1.26.5
- Primary CNI for Kubernetes cluster: antrea
- OS (e.g. from /etc/os-release): AlmaLinux release 9.2 (Turquoise Kodkod)

**Comment by s1061123** [comment]
Hi, thank you for the issue report, @jsalatiel .

multus-daemonset-crio.yml is historically created due to the configration difference, but I suppose it is no longer required. So you could use multus-daemonset.yml for that.
Could you please try that and let us know the results? thanks!
