### ISSUE TITLE
multus can not work well with IPV4/IPV6 dual stack

### ISSUE THREAD

**Issue by pengbinbin1** [k8snetworkplumbingwg/multus-cni#1141]
**What happend**:
I have a cluster setup with Kube-ovn as my main CNI. I am trying to add Multus and SRIOV-CNI to allow specific pods to have multiple interfaces. The multus version is v3.7.2 What's more, the ipam is developed by myself.The main NAD config like 
`_config: '{ "name":"sriov-network", "cniVersion":"0.3.1","plugins":[ {"type":"sriov","ipam":{"type":"ipamwrapper-cni"}}]}'_`
When my ipam is configured to IPV4, all going well, but when i configured my ipam to IPV4/IPV6 dual stack, the pod's status is  Containercreating all the time.And describe this pod,we can see taht when the multus add IPv6 to container "**Permission denied**" occured, what is wrong?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
v3.7.2
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by pengbinbin1** [comment]
![20230815111637](https://github.com/k8snetworkplumbingwg/multus-cni/assets/28950491/d60524a3-85b2-45dc-a041-0fe283e557e9)

**Comment by s1061123** [comment]
> When my ipam is configured to IPV4, all going well, but when i configured my ipam to IPV4/IPV6 dual stack, the pod's status is Containercreating all the time.And describe this pod,we can see taht when the multus add IPv6 to container "Permission denied" occured, what is wrong?

From multus point of view, nothing is different between IPv4 config case and IPv4/v6 dual stack config case, because multus just passing to these config to delegate CNI (i.e. "sriov" and "ipamwrapper-cni" in your case). So above error is happen in delegate CNI or some other case. Could you ask these community for that?
