### ISSUE TITLE
Released versions points to snapshot image

### ISSUE THREAD

**Issue by kolomparrudi** [k8snetworkplumbingwg/multus-cni#1153]
Hi,

I have downloaded latest stable release (4.0.2) and used deployments/multus-daemonset.yml to install it, but I surprised, the docker image points to a generic snapshot image: ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot

When I verified 4.0.1, it points to the same image!

Thanks,
Laszlo

**Comment by mapleji-jiang** [comment]
I also have the version question.

When the multus has issue with latest commits, I tried to checkout to the latest tag, while the code date is May, which is a little old, and some functionality seems is not compatible with other k8s plugins.

any principle for the tags update for multus?
if there is new issue with latest code, is there any way that we can use a old commit/tag to move forward?

BR,
Maple
