### ISSUE TITLE
multus should not generate empty 00-multus.conf when failed to access the primary CNI

### ISSUE THREAD

**Issue by xiangfeiz** [k8snetworkplumbingwg/multus-cni#1155]
**What happend**:
Create a k8s cluster with calico CNI.

Deploy multus on the cluster.

Deploy a network function on the cluster which adds multiple network interfaces. Node VM is rebooted once.

Node is shown as not ready due to "cni plugin not initialized".

Pods other than those from DaemonSet are shown as Unknown due to "NetworkNotReady".

**What you expected to happen**:
CNI and other pod on the cluster should be Running.

**How to reproduce it (as minimally and precisely as possible)**:
As "What happened"

**Anything else we need to know?**:
The following error is seen in multus pod log:

2023-09-06T00:29:25Z [error] failed to access the primary CNI configuration from /host/etc/cni/net.d/10-calico.conflist: failed to read the cluster primary CNI config /host/etc/cni/net.d/10-calico.conflist: open /host/etc/cni/net.d/10-calico.conflist: no such file or directory

multus config is empty:

root@snc0322385760-k6jjc-g7hqp [ /etc/cni/net.d ]# ls -l
total 8
rw------ 1 root root 0 Sep 6 00:29 00-multus.conf
rw-rr- 1 root root 676 Sep 6 00:29 10-calico.conflist
rw------ 1 root root 2673 Sep 6 00:29 calico-kubeconfig

The issue can be fixed by restarting multus pod.

**Environment**:

- Multus version 4.0.1+vmware.1-tkg.1 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5+vmware.2", GitCommit:"83112f368344a8ff6d13b89f120d5e646cd3bf19", GitTreeState:"clean", BuildDate:"2023-06-26T06:42:01Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
- Primary CNI for Kubernetes cluster: calico
- OS (e.g. from /etc/os-release): photon
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by xiangfeiz** [comment]
/var/log/calico/cni/cni.log
[cni.log](https://github.com/k8snetworkplumbingwg/multus-cni/files/12565230/cni.log)
install_cni log from calico pod
[install_cni.log](https://github.com/k8snetworkplumbingwg/multus-cni/files/12565231/install_cni.log)
multus pod log
[multus.log](https://github.com/k8snetworkplumbingwg/multus-cni/files/12565232/multus.log)

**Comment by nicklesimba** [comment]
> Multus version 4.0.1+vmware.1-tkg.1

This image is not maintained by us, so your multus version is not supported. Maybe you may try reaching out to VMware. Or if you provide support for this in a PR alongside a description, it may get merged.
