### ISSUE TITLE
The tagged - e.g. v4.0.1, v4.0.2 - versions manifests install pods from shifting images

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/multus-cni#1170]
**What happend**:
When we use the manifest from a tagged version - e.g. [v4.0.2](https://github.com/k8snetworkplumbingwg/multus-cni/blob/f03765681fe81ee1e0633ee1734bf48ab3bccf2b/deployments/multus-daemonset-thick.yml#L188) - the version of multus we are installing is **not** pinned, since this "snapshot" tag keeps getting overwritten everytime a PR is merged. 

In essence, the `snapshot` and `latest` tags are essentially the same. Same thing happens with their `thick` counterparts.

**What you expected to happen**:
A manifest present on a "tagged" commit should point to a pinned image, not to one that varies over time.

**How to reproduce it (as minimally and precisely as possible)**:
Install a versioned manifest. 

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by maiqueb** [comment]
/cc @oshoval 

Thanks for bringing this to my attention Or. 
Do you want to add anything ?

**Comment by oshoval** [comment]
Worth to consider including examples or even a temp wordaround as sed line to replace image tag with `v4.0.2-thick`
also to consider mentioning this fix, https://github.com/k8snetworkplumbingwg/multus-cni/pull/1161#issuecomment-1732866519 as it is a blocker until a new release exists

**Comment by oshoval** [comment]
Nope
here a ref for a temp wa if desired
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/282

**Comment by dougbtv** [comment]
I think two parts...

* first: change from `snapshot` to `stable` so you at least get the latest tagged image
* secondly: Should we have a new commit in each tag that adds the specific tagged image, so you're operating from that tag and tagged image?

**Comment by sdwilsh** [comment]
This problem is getting more problematic with time.  I was going crazy because as I restarted nodes calico would stop working because multus couldn't find `calico` in `/opt/cni/bin`, which made no sense in `v4.0.2` because that directory didn't exist until 1dd4edded22e225ea66931434663bd825ede4c38.  All of my problems went away once I pinned the image to `v4.0.2-thick`
