### ISSUE TITLE
CIS benchmark and compliance for Multus v4.0.2

### ISSUE THREAD

**Issue by sakshisharma84** [k8snetworkplumbingwg/multus-cni#1172]
As part of CIS security compliance check, we made an observation for Multus that all permissions are assigned to the ClusterRole "multus" on secrets https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset-thick.yml#L61.

Could you please check and suggest if this could be remediated?

Rule Name | Rule Description | Remediation
-- | -- | --
Minimize access to secrets | The Kubernetes API stores secrets, which may be service account tokens for the Kubernetes API or credentials used by workloads in the cluster. Access to these secrets should be restricted to the smallest possible group of users to reduce the risk of privilege escalation. | Where possible, remove get, list and watch access to secret objects in the cluster.

**Comment by s1061123** [comment]
As far as I know of, these line is to get/list/watch for net-attach-def (CRD in 'k8s.cni.cncf.io` apiGroup), hence it does not have secret objects ("k8s.cni.cncf.io" apiGroup does not have secret objects).

```
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
```

So could you please let me know which actual line allows users to access secret objects? thanks.
