### ISSUE TITLE
Multiple interface configuration 

### ISSUE THREAD

**Issue by safaa-zahir** [k8snetworkplumbingwg/multus-cni#1181]
We have 3 nodes in our cluster, each one have 2 network cards (one normal, one high speed) each one is configured to use a different IP, one normal IP 172.19.0.0 while high speed interface uses another IP, does Multus cni can be configured in a way that if the traffic is coming from another node then use {high speed interface} if not use normal interface

The use case: nodes in our cluster needs to use high speed network connectivity to connect with each other

Please help me investigate this

**Comment by nforced** [comment]
This is good to know, as I assume many people are looking at the project for the very same reason.
Is there anyone how can answer to this here?

**Comment by TristanB1994** [comment]
I would be interested in this for adding a WireGuard interface to pods
