### ISSUE TITLE
Failed to list/watch pods in v4.0.2

### ISSUE THREAD

**Issue by jdn5126** [k8snetworkplumbingwg/multus-cni#1185]
Hi all, I feel like I must be missing something obvious here. I used the reference deployment for the thick plugin in https://github.com/k8snetworkplumbingwg/multus-cni/blob/v4.0.2/deployments/multus-daemonset-thick.yml, but I built my own Multus image as follows:
```
docker buildx create --use --name pipeline_builds
docker buildx build --no-cache --platform=linux/amd64 -t $REPO:v4.0.2-linux_amd64-thick  -f images/Dockerfile.thick --push .
```

I am seeing the following log errors after deploying:
```
W1109 23:47:55.914854  514945 reflector.go:533] k8s.io/client-go/informers/factory.go:150: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:kube-system:multus" cannot list resource "pods" in API group "" at the cluster scope
E1109 23:47:55.914887  514945 reflector.go:148] k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:kube-system:multus" cannot list resource "pods" in API group "" at the cluster scope
```

If I add `list` and `watch` permissions to the `multus` ClusterRole, then I don't see the errors anymore, but I am wondering if this behavior is expected in v4.0.2. Everything otherwise seems to be working fine.

**Comment by jdn5126** [comment]
When I use `ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2-thick`, I do not see these errors, so that makes me think that the image build process is different than what I did above.

Is the `v4.0.2-thick` image not built from the `v4.0.2` GitHub tag and `docker`?

**Comment by jdn5126** [comment]
Ah, this turned out to be an image caching issue on my end, sorry for the noise. I originally built the image from the `master` branch, and then unintentionally used the same image tag for the image built from v4.0.2 tag.

**Comment by sdwilsh** [comment]
It's maybe worth noting that the `multus-daemonset-thick.yml` (found [here](https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/v4.0.2/deployments/multus-daemonset-thick.yml) for v4.0.2) has the same problem which uses the tag `snapshot-thick` which I'm guessing is also built off of master.  I used `kustomize` to update the image tag to `v4.0.2-thick` to get the error to go away.
