### ISSUE TITLE
Having a hard time to understand the spec to delegate the IP assignments (and mac address) to pod

### ISSUE THREAD

**Issue by tardich** [k8snetworkplumbingwg/multus-cni#1193]
I'm currently using this format to define my network attachments definitions:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-eth0-0
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
       "type": "whereabouts",
       "range": "192.168.101.0/24",
       "range_start": "192.168.101.121",
       "range_end": "192.168.101.121",
       "routes": []
    }
  }'
```
But I'd like to be able to specify the mac address and maybe completely delegate the ip and mac assignments to the pod using it so the network attachment definition becomes more generic.

I tested this:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-eth0-0
spec:
  config: '{
    "cniVersion": "0.3.1",
    "plugins": [
        "type": "macvlan",
        "master": "eth0",
        "mode": "bridge",
        "ipam": {
           "type": "whereabouts",
           "range": "192.168.101.0/24",
           "range_start": "192.168.101.121",
           "range_end": "192.168.101.121",
           "routes": []
        },{
        "capabilities": { "mac": true },
        "type": "tuning"
        }
    ]
  }'
```
and setting the deployment as:

```
spec:
  template: 
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlan-eth0-0","mac": "8e:6e:c9:e6:40:e1"}]'
```

and this works. But if I want to replace the other portions in the ipam section to put this back to the deployment as well, what do I need to do? I can't find out the information...

**Comment by tardich** [comment]
In fact, I'm able to set the ip address for a single pod (that is, making sure not to fill up the range field (nor both range_start and range_end fields) from ipam range field) but if I have a deployment with three pods, where in the network attachement I'd be using the above three fields to get predictability (making sure that, no matter what, a three-replicas deployment would always get one of the three IP's), I can't find a way to declare it in the pod networks annotation. The ips fields seem too generic for it as the notation is in CIDR format where I may not be able to "declare" the right IP range without including too many and anyway, I'd have to exclude the unwanted IP's in the network attachment definition anyway, making it hard to have something really generic

**Comment by s1061123** [comment]
We, multus-cni, only invokes CNI. So if you want to configure flexible way (i.e. not only to specifying IP in annotation directly, also applicabile to deployment to scale), you need to have such IPAM CNI plugin because multus-cni does not provide any IPAM functionality. If you want to add such functionality in whereabouts CNI, please ask whereabouts CNI community to discuss about the feature.
