### ISSUE TITLE
Support of Virtual IP or floating IP

### ISSUE THREAD

**Issue by vishal-yadav** [k8snetworkplumbingwg/multus-cni#1196]
**What would you like to be added**:
Multus CNI plugin should support Virtual IP or Floating IP.

**Why is this needed**:
This is required to achieve IP failover in case active-standby mode. The active member "owns" or responds to that IP address at any given time. Should the active member fail, then "ownership" of the floating IP address would be transferred to a standby member to promote it as the new active member. Specifically, the member to be promoted issues a gratuitous ARP, announcing the new MAC address–to–IP address association.

Note: Sometimes back I read somewhere that multus doesn't support this option but not sure about the current situation.

**Comment by dougbtv** [comment]
Unfortunately Vishal, this kind of failure detection for the interface would need to happen between CNI ADD and CNI DEL, and currently Multus primarily operates during that time period, and having something richer during the container lifecycle isn't possible today with the way that CNI and Multus work.

Thanks for sharing your use case.

You might be able to kind of "roll your own" with something like  keepalived (maybe)
