### ISSUE TITLE
not able to see multiple interfaces other than default & loop back 

### ISSUE THREAD

**Issue by pranjal10t** [k8snetworkplumbingwg/multus-cni#1197]
**What happend**:
**How to reproduce it (as minimally and precisely as possible)**:

1. created  net-attach-def & POD ( as below ) 

##################################

## IPVLAN L2

cat <<EOF | kubectl apply -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-conf-l2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "ipvlan-conf",
      "type": "ipvlan",
      "master": "enp0s3",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.2.0/24",
        "rangeStart": "192.168.2.100",
        "rangeEnd": "192.168.2.116",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.2.1"
      }
    }'
EOF
---------------------------------------------------------------------------------------------------------------------------------
## POD with 
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  annotations:
    k8s.v1.cni.cncf.io/networks:  ipvlan-conf-l2
spec:
  containers:
  - name: samplepod1
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
EOF
=======================================================================

**What you expected to happen**:

Not able to see any new interfaces inside container , other than eth0 & lo . 

root@mario:~# kubectl exec -it samplepod1 -- ifconfig 
eth0      Link encap:Ethernet  HWaddr 36:54:4F:5E:XX:XX 
          inet addr:10.0.0.192  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::3454:4fff:fe5e:a591/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1006 (1006.0 B)  TX bytes:1006 (1006.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

root@mario:~# 
root@mario:~# 
root@mario:~# kubectl exec -it samplepod1 -- ip r s
default via 10.0.0.249 dev eth0 mtu 1450 
10.0.0.249 dev eth0 scope link 

**Anything else we need to know?**:

install k8s + docker :-
curl https://raw.githubusercontent.com/RX-M/classfiles/master/k8s-no-cni.sh | sh

cilium:-
wget https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
tar zxvfC cilium-linux-amd64.tar.gz /usr/local/bin
cilium install

install multus:-
clone this GitHub repository.
git clone https://github.com/k8snetworkplumbingwg/multus-cni.git && cd multus-cni
install plugin 
cat ./deployments/multus-daemonset.yml | kubectl apply -f -

status of pod:-
root@mario:~/multus-cni# kubectl get pod -A 
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   cilium-958xd                      1/1     Running   0          7m51s
kube-system   cilium-operator-f5dcdcc8d-lc96q   1/1     Running   0          7m51s
kube-system   coredns-5dd5756b68-dgk2m          1/1     Running   0          25m
kube-system   coredns-5dd5756b68-xjngn          1/1     Running   0          25m
kube-system   etcd-mario                        1/1     Running   0          25m
kube-system   kube-apiserver-mario              1/1     Running   0          25m
kube-system   kube-controller-manager-mario     1/1     Running   5          25m
kube-system   kube-multus-ds-r2s7v              1/1     Running   0          4m3s
kube-system   kube-proxy-mpp5c                  1/1     Running   0          25m
kube-system   kube-scheduler-mario              1/1     Running   5          25m

root@mario:~# uname -a 
Linux mario 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@mario:~# 

**Environment**:

- Multus version 
root@mario:/home/mario# kubectl -n kube-system exec -it kube-multus-ds-ppp7q -c kube-multus -- /usr/src/multus-cni/bin/multus --version
multus: version:(clean), commit:7ea924b8f156fb0633ff494c80fe7dd0d3f2bf7d, date:2023-08-31T18:17:18+00:00

  image path and image ID (from 'docker images')
  mario@mario:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:01 2023
 OS/Arch:           linux/amd64
 Context:           default
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied
mario@mario:~$ 
 
- Kubernetes version (use `kubectl version`):
root@mario:/home/mario# kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4

- Primary CNI for Kubernetes cluster:
cloned this GitHub repository.
git clone https://github.com/k8snetworkplumbingwg/multus-cni.git && cd multus-cni
install plugin 
cat ./deployments/multus-daemonset.yml | kubectl apply -f -

- OS (e.g. from /etc/os-release):
run on OS:- 
root@mario:~# kubectl exec -it samplepod1 -- ip r s
default via 10.0.0.249 dev eth0 mtu 1450 
10.0.0.249 dev eth0 scope link 
root@mario:~# kubectl exec -it samplepod1 -- ip r s dev lo
root@mario:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@mario:~# 

- File of '/etc/cni/net.d/'
root@mario:/home/mario# ls -ltrh /etc/cni/net.d/
total 16K
-rw-r--r-- 1 root root  145 Dec 12 17:44 05-cilium.conf.cilium_bak
-rw-r--r-- 1 root root  191 Dec 13 05:08 05-cilium.conflist
drwxr-xr-x 2 root root 4.0K Dec 15 09:15 multus.d
-rw------- 1 root root  402 Dec 15 09:15 00-multus.conf.cilium_bak

- File of '/etc/cni/multus/net.d'
root@mario:~/multus-cni# ls -ltrh /etc/cni/net.d/
total 16K
-rw-r--r-- 1 root root  145 Dec 12 17:44 05-cilium.conf.cilium_bak
-rw-r--r-- 1 root root  191 Dec 13 05:08 05-cilium.conflist
drwxr-xr-x 2 root root 4.0K Dec 15 09:15 multus.d
-rw------- 1 root root  402 Dec 15 09:15 00-multus.conf.cilium_bak

root@mario:~/multus-cni# ls -ltrh /etc/cni/multus/net.d
ls: cannot access '/etc/cni/multus/net.d': No such file or directory

- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
ot@mario:~/multus-cni# kubectl get net-attach-def -o yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"ipvlan-conf-l2","namespace":"default"},"spec":{"config":"{ \"cniVersion\": \"0.3.1\", \"name\": \"ipvlan-conf\", \"type\": \"ipvlan\", \"master\": \"enp0s3\", \"mode\": \"l2\", \"ipam\": { \"type\": \"host-local\", \"subnet\": \"192.168.2.0/24\", \"rangeStart\": \"192.168.2.100\", \"rangeEnd\": \"192.168.2.116\", \"routes\": [ { \"dst\": \"0.0.0.0/0\" } ], \"gateway\": \"192.168.2.1\" } }"}}
    creationTimestamp: "2023-12-15T09:00:10Z"
    generation: 1
    name: ipvlan-conf-l2
    namespace: default
    resourceVersion: "22508"
    uid: 188321d3-03af-4fc8-bba8-a6770d6b16c9
  spec:
    config: '{ "cniVersion": "0.3.1", "name": "ipvlan-conf", "type": "ipvlan", "master":
      "enp0s3", "mode": "l2", "ipam": { "type": "host-local", "subnet": "192.168.2.0/24",
      "rangeStart": "192.168.2.100", "rangeEnd": "192.168.2.116", "routes": [ { "dst":
      "0.0.0.0/0" } ], "gateway": "192.168.2.1" } }'
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    creationTimestamp: "2023-12-15T08:47:46Z"
    generation: 1
    name: ipvlan-def
    namespace: default
    resourceVersion: "21168"
    uid: a3287297-cd47-4e62-b7ac-5695ce0952f7
  spec:
    config: '{ "cniVersion": "0.3.1", "type": "ipvlan", "master": "enp0s3", "mode":
      "l2", "ipam": { "type": "host-local", "subnet": "192.168.2.0/24", "rangeStart":
      "192.168.2.201", "rangeEnd": "192.168.2.205", "gateway": "192.168.2.1" } }'
kind: List
metadata:
  resourceVersion: ""
root@mario:~/multus-cni# 

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
root@mario:~/multus-cni# kubectl get pod samplepod1 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-def
  creationTimestamp: "2023-12-15T08:48:42Z"
  name: samplepod1
  namespace: default
  resourceVersion: "23130"
  uid: 8f1e1c3c-e5d6-4bbf-8ac5-64b989682ca0
spec:
  containers:
  - args:
    - -f
    - /dev/null
    command:
    - tail
    image: nicolaka/netshoot
    imagePullPolicy: Always
    name: samplepod1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7xzqf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: mario
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-7xzqf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-15T08:48:42Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-15T09:16:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-15T09:16:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-15T08:48:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://704dad9165ee25efdaccd1fac5b094390ef07939199d409fe02ae7f01c226fbd
    image: docker.io/nicolaka/netshoot:latest
    imageID: docker.io/nicolaka/netshoot@sha256:a7c92e1a2fb9287576a16e107166fee7f9925e15d2c1a683dbb1f4370ba9bfe8
    lastState:
      terminated:
        containerID: containerd://7b6d133419f2d6ac332cf7204c1237183024f2df9416eeee36521a623909ecf6
        exitCode: 255
        finishedAt: "2023-12-15T09:12:00Z"
        reason: Unknown
        startedAt: "2023-12-15T08:49:35Z"
    name: samplepod1
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2023-12-15T09:16:56Z"
  hostIP: 192.168.2.29
  phase: Running
  podIP: 10.0.0.36
  podIPs:
  - ip: 10.0.0.36
  qosClass: BestEffort
  startTime: "2023-12-15T08:48:42Z"

- Other log outputs (if you use multus logging)

**Comment by pranjal10t** [comment]
@pranjal10t

**Comment by dougbtv** [comment]
Looks like the cillium CNI conf is the first in the list -- cillium renamed your multus config.

Next time, install cillium first, then, install Multus.

**Comment by pranjal10t** [comment]
Next time, install cillium first, then, install Multus.

I did the same , how do u know cilium was not installed before multus ??
