### ISSUE TITLE
IP Range Multiple Allocation in DHCP

### ISSUE THREAD

**Issue by mslee89** [k8snetworkplumbingwg/multus-cni#1227]
I want multiple IP ranges assigned to each application from one DHCP or more. Or just a specific IP range. Here's a brief description.
  
- One DHCP has multiple IP ranges, including 1.1.1.0/24, 2.2.2.0/24, and 3.3.3.0/24.
- There are also several applications in Kubernetes.

A Application should be assigned 1.1.1.0/24 and 3.3.3.0/24, and B Application should be assigned only 2.2.2.0/24 services.
Is it possible to do these settings in Multus? So far, I have used the host-local of IPAM, but I want to change it to DHCP and use it.

There doesn't seem to be anything I can set up on the site provided below.
https://www.cni.dev/plugins/current/ipam/dhcp/

**Comment by dougbtv** [comment]
@mslee89 the DHCP IPAM CNI plugin is indeed the reference plugin to use for DHCP. Remember, that the DHCP CNI plugin also requires a daemon. I'm not sure if it solves everything you're looking for, but it will solve  the DHCP IP address assignment.

You might also consider https://github.com/k8snetworkplumbingwg/whereabouts for assigning IP addresses as well.
