### ISSUE TITLE
MACSEC communication between nodes in K8s environment 

### ISSUE THREAD

**Issue by takuyaK8s** [k8snetworkplumbingwg/multus-cni#1233]
I would like to perform inter-node communication using MACSEC communication in the K8s environment, but after testing with Flannel, it was not possible.

I would like to use Multi-CNI with Multus, set up a VLAN configuration with BirdgeCNI Plugin using Flannel and BirdgeCNI Plugin configuration, and use MACSEC communication for inter-node communication.Is it possible?

Also, please let me know if you have any experience with MACSEC or encrypted communication.

**Comment by dougbtv** [comment]
Thanks for your interest in this technology along with  Multus.

We believe that this would be a technology implemented as either on the host, or as a terminal CNI plugin  and not directly  within  Multus.

That is, the CNI plugins that Multus called (as an example, bridge CNI) would utilize this technology.
