### ISSUE TITLE
Is it possible to provide images with different architecture for multus-cni:latest-thick image?

### ISSUE THREAD

**Issue by hongzhen-ma** [k8snetworkplumbingwg/multus-cni#1240]
https://github.com/k8snetworkplumbingwg/multus-cni/pkgs/container/multus-cni/185176114?tag=latest-thick

There's only two kinds of architecture images for multus-cni:latest-thick, one is amd64 and the other is unknown.At most cases, the arm64 image is also needed.
So  is it possible to provide images with different architecture for multus-cni:latest-thick image?

<img width="766" alt="image" src="https://github.com/k8snetworkplumbingwg/multus-cni/assets/67130442/96a3f94a-3160-4fff-9314-941aeafbc9c6">

**Comment by linuxmaniac** [comment]
duplicate of #1136

**Comment by hongzhen-ma** [comment]
@linuxmaniac  thanks

**Comment by hongzhen-ma** [comment]
All the linked issues are closed. But still there's no arm64 image for multus-cni:latest-thick
