### ISSUE TITLE
delegate CNI doesn't see serviceaccount token of multus daemon from chroot execution

### ISSUE THREAD

**Issue by nvetel** [k8snetworkplumbingwg/multus-cni#1258]
Hello,

I'm using multus thick v4.0.2 and a delegate CNI that needs to request the API: the [userspace CNI](https://github.com/intel/userspace-cni-network-plugin)

I have errors because my delegate CNI searches for the file _/var/run/secrets/kubernetes.io/serviceaccount/token_ but doesn't find it.

I tried to understand what happens exactly, and it seems to me that the issue here is related to the "chroot envrionment" used to run the delegate CNI that can't read the expected files.

The daemon has a serviceaccount mounted in _/var/run/secrets/kubernetes.io/serviceaccount_ that can be used to interact with the API. The userspace CNI get the pod attached to retrieve annotations, and write one to record a status as multus does with _k8s.v1.cni.cncf.io/network-status_, but since it is executed in _chroot /hostroot_, it doesn't see the serviceaccount wich is not on the host, but on the multus pod.

Is this the expected behaviour ?
If yes, how the delegate CNI is supposed to have access to the API to fetch pods if needed ?

**Comment by dougbtv** [comment]
> my delegate CNI searches for the file /var/run/secrets/kubernetes.io/serviceaccount/token

Since this is executed either on the host (via thin plugin) or within a chroot (within the thick plugin) it won't find paths that are specifically inside the container.

It's curious to me that the userspace CNI plugin is looking for a kubernetes service account token?

**Comment by nvetel** [comment]
Thanks @dougbtv for the feedback on that topic.

In just wanted to make a summary of the userspace CNI's needs with the API.

The userspace CNI needs to read the pod to get annotations and pod UID (for emptydir volume only) needed to know the volume used as a shared directory for the socketfile.
It will also write a userspace-data annotation as a result of its configuration in the same fashion as multus.
It seems that multus has been a source of inspiration with those annotations, as well as the multus kubeconfig reuse !

Anyway, a kubeconfig generation has to be provided in the userspace CNI, or any other CNI that needs to use the API then.

**Comment by bc185174** [comment]
Any update on solution to this? Hit the issue in v4.0.2 and on master.
