### ISSUE TITLE
What's the proper way to rotate the multus kubeconfig for multus 3.7

### ISSUE THREAD

**Issue by lubronzhan** [k8snetworkplumbingwg/multus-cni#1263]
### Discussed in https://github.com/k8snetworkplumbingwg/multus-cni/discussions/1262

<div type='discussions-op-text'>

<sup>Originally posted by **lubronzhan** April 16, 2024</sup>
We is still using old multus, without the thick image, as mentioned here
https://github.com/k8snetworkplumbingwg/multus-cni/issues/852. So if the kubeconfig of multus expires, the multus will fail to connect to apiserver to update pod info.

Question, what's the proper way to rotate the token for now? restarting multus pod + pod that needs the second nic?

We will try upgrade to thick image later.

Thank you</div>

**Comment by dougbtv** [comment]
Here's an example for you: https://github.com/openshift/multus-cni/blob/master/images/entrypoint.sh#L502-L508

But, it could maybe be patched in the release-v3 branch
