### ISSUE TITLE
Basic helm chart as source of the provided yamls

### ISSUE THREAD

**Issue by micw** [k8snetworkplumbingwg/multus-cni#1269]
Hello,

I have seen that there are multiple attempts to create (and maintain) a helm chart for multus. Unfortunately, all of them seems to be outdated (maybe except the bitname one but this seems to be very customized and dot following the current example yamls in this project).

What do you think about a _basic_ helm chart that is part of this project and contains just the stuff that is currently in the examples in "deployments"? So instead of maintaining the yaml examples, this project could maitain the helm chart. The examples then can simply be generated out of the helm chart. This way, there's no additional maintenance overhead but there would be an "official" helm chart.

If you're open to this, I'd create a PR for a initial chart, containing what's already in the example yamls.

Kind regards,
Michael.

**Comment by micw** [comment]
To show what I mean, I have started with an initial helm chart and a script that generates the content of `multus-daemonset.yml`: https://github.com/micw/multus-cni/tree/feature/helm-chart/deployments

Please let me know what you think.

**Comment by dougbtv** [comment]
@micw we'd love your contributions against the helm charts -- it's one of those places where there's always more contributions necessary, you can find the charts @ https://github.com/k8snetworkplumbingwg/helm-charts

And if you would like to interact with us about the changes, feel free to join our maintainer calls, connection info @ https://github.com/k8snetworkplumbingwg/community

**Comment by ianb-mp** [comment]
Just to contribute my 2c worth...

> you can find the charts @ https://github.com/k8snetworkplumbingwg/helm-charts

As discussed [here](https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/56#issuecomment-2084304394) that repo looks abandoned.

Having a helm chart is only 1/2 of the picture - it's also necessary to make it available via a chart repository. sriov-network-operator solves this by pushing the chart to GHCR as an OCI registry asset which seems nicer than using gh-pages to host the chart.
