### ISSUE TITLE
do multus-cni:snapshot-thick has a arm64 image ?

### ISSUE THREAD

**Issue by bobz965** [k8snetworkplumbingwg/multus-cni#1271]
hi multus-cni  teams,  do [ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick](http://ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick)  have a arm64 image? thanks

**Comment by nvollmar** [comment]
See https://github.com/k8snetworkplumbingwg/multus-cni/pull/1136

I started to build my own images for arm64 and publish them here if you want to use them: https://hub.docker.com/r/aluveitie/multus-cni/

At the moment I'm just building, testing and publishing releases.

**Comment by bobz965** [comment]
> See #1136
> 
> I started to build my own images for arm64 and publish them here if you want to use them: https://hub.docker.com/r/aluveitie/multus-cni/
> 
> At the moment I'm just building, testing and publishing releases.

thanks
