### ISSUE TITLE
thin_entrypoint should generate multus kubeconfig with manual option

### ISSUE THREAD

**Issue by abasitt** [k8snetworkplumbingwg/multus-cni#1295]
Older version of multus e.g. 3.9.3 with older script of thin_entry.sh generates a multus.d directory and multus.kubeconfig file with a non-auto installation e.g. # "--multus-conf-file=/tmp/multus-conf/70-multus.conf"

The new version 4.0.2 with new thin_entrypoint doesn't generate multus.d and multus.kubeconfig if the installation type is non-auto. We still want multus to generate multus.kubeconfig even though if the configfile is used manually.

I believe adding below lines [here ](https://github.com/k8snetworkplumbingwg/multus-cni/blob/9f5c0239a804a90bf8913c9a386ca50eff9ce0cc/cmd/thin_entrypoint/main.go#L584)would fix it. 
`caHash, saTokenHash, err = opt.createKubeConfig(nil, nil)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to create multus kubeconfig: %v\n", err)
			return
		}`

**Comment by dougbtv** [comment]
Any interest in trying a PR for it? I think this is reasonable to expect that functionality in 4.0.

Please add testing to ensure that the kubeconfig generates and what not. Thank you!

**Comment by abasitt** [comment]
Thank you, will give it a try. :)

**Comment by abasitt** [comment]
@dougbtv I modified the function and did the local testing to make sure it works correctly, but I am struggling to write the unit testing because of the constant [here ](https://github.com/k8snetworkplumbingwg/multus-cni/blob/aff99fccc5fe3b21aec84bb56a6d1bbaf8ffc45b/cmd/thin_entrypoint/main.go#L62). 
I wouldn't want to write a dummy file that can mess up with actual tokens in that location. Any suggestions ?.

**Comment by dougbtv** [comment]
Abdul -- not exactly sure what you're asking, mind submitting the change as you have it and we can look at the code? Thanks!
