### ISSUE TITLE
feature request: CNI file permissions more restrictive (600)

### ISSUE THREAD

**Issue by missa-wndrvr** [k8snetworkplumbingwg/multus-cni#1301]
**What would you like to be added**:
Ensuring the file permission of the multus-conf-file is set to 600 when copied to host.

**Why is this needed**:
CNI-related CIS Benchmarks include:
```
1.1.9	Ensure that the Container Network Interface file permissions are set to 600 or more restrictive
1.1.10	Ensure that the Container Network Interface file ownership is set to root:root
```
Currently:
```
root@user: stat -c '%a %n' /etc/cni/net.d/05-multus.conf
644 /etc/cni/net.d/05-multus.conf
```

**Comment by dougbtv** [comment]
Any chance you'd mind submitting a PR to ensure this mode? Sounds like a fair change to me
