### ISSUE TITLE
Thin plugin readiness check does not apply to config generation.

### ISSUE THREAD

**Issue by yifeng-cerebras** [k8snetworkplumbingwg/multus-cni#1306]
**What happend**:
In case of node reboot, multus thin plugin failed to detect the master cni (cilium) even though we specified the readiness file for cilium. 
We are using "auto" policy so it tries to [find the first conf](https://github.com/k8snetworkplumbingwg/multus-cni/blob/41013e7580396629a02213019baad1d0c84a6a2c/cmd/thin_entrypoint/main.go#L319) while cilium is not ready.

For thick plugin, it has the [right implementation that readiness file missing will also block config generation](https://github.com/k8snetworkplumbingwg/multus-cni/blob/748930239d6543875ab9a6efab15409be74b1512/cmd/multus-daemon/main.go#L75-L87).
Probably something similar can be done for thin plugin.

**What you expected to happen**:
Readiness file check also apply to config generation for thin plugin with auto policy.

**How to reproduce it (as minimally and precisely as possible)**:
Delete main cni plugin and restart thin multus pod.

**Anything else we need to know?**:
We chose to use thin plugin as we discovered a more critical issue for thick. 
When pods are initializing, force kill the daemon multus pod will cause pod stuck at init stage forever even after multus daemon pod recovered.
Probably worth another bug report. cc: @michaely-cb

**Environment**:
- Multus version 
  latest master
- Kubernetes version (use `kubectl version`): 1.24.4
- Primary CNI for Kubernetes cluster: cilium
- OS (e.g. from /etc/os-release): rocky8.5

**Comment by dougbtv** [comment]
> We chose to use thin plugin as we discovered a more critical issue for thick.

we'd like to know more about this, as well

**Comment by dougbtv** [comment]
If you can provide a procedure that we can use to both reproduce and test this, that would be very helpful
