### ISSUE TITLE
Please cut a new release tag

### ISSUE THREAD

**Issue by mamccorm** [k8snetworkplumbingwg/multus-cni#1307]
Hi there,

Sorry for the duplicate request, but some time ago we opened this, but doesn't look like theres been any activity:
 - https://github.com/k8snetworkplumbingwg/multus-cni/issues/1253

There have still been plenty of commits. Is there a reason we've not cut a release tag in 14 months, while there is still on-going tev work / commits to main branch?

Can we look at getting one cut to avail of the latest changes? and feel free to dup this against the other issue

**Comment by srishtih** [comment]
Given how much the image has changed since the last official release, it would be great to have a new version with all the features added since then. Any info on a release plan would be really appreciated.

**Comment by dougbtv** [comment]
we are indeed overdue, we're supposed to release every 6 months otherwise if there's no other pressing reason -- however, we're going to wait for a couple PRs before we tag a release...

especially: https://github.com/k8snetworkplumbingwg/multus-cni/pull/1299

**Comment by sdwilsh** [comment]
@dougbtv, it looks like that PR is merged.  Is there an ETA for a new version?

**Comment by sdwilsh** [comment]
I think this can be closed now: https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v4.1.0
