### ISSUE TITLE
getcwd error in thick plugin

### ISSUE THREAD

**Issue by bc185174** [k8snetworkplumbingwg/multus-cni#1308]
**What happend**:

No pods are being assigned IPs. Multus is frequently logging:

```
2024-07-11 14:24:14.962 [INFO][192098] k8s.go 598: Teardown processing complete. ContainerID="c011cf5a6a0cfe50c6061b3373844c9d65bc1a31e664677f99d61a93be8b0e03"
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

**What you expected to happen**:

No error and pod to be assigned IP.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy latest version multus from master branch

**Anything else we need to know?**:

Tried using v4.0.2 but get service account errors due to the exec running chroot on host (should really avoid doing this, its a security nightmare).

**Environment**:

- Multus version: master
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`): 1.28.9
- Primary CNI for Kubernetes cluster: Calico
- OS (e.g. from /etc/os-release): Ubuntu
- File of '/etc/cni/net.d/': N/A
- File of '/etc/cni/multus/net.d': N/A
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`): N/A
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`): N/A
- Other log outputs (if you use multus logging): N/A

**Comment by dougbtv** [comment]
> Tried using v4.0.2 but get service account errors due to the exec running chroot on host (should really avoid doing this, its a security nightmare).

This is essentially required for a CNI thick plugin, as it's a replacement for running directly on the host -- where you do have full access to the host

**Comment by dougbtv** [comment]
I think we need to pod spec and net-attach-def to replicate it? Otherwise, I'd think we'd hit it in our e2e tests, we'd love a reproducer, thanks
