### ISSUE TITLE
Update readme install section

### ISSUE THREAD

**Issue by ah8ad3** [k8snetworkplumbingwg/multus-cni#1315]
**What would you like to be added**:
I would like to update install link from main readme from 
`cat ./deployments/multus-daemonset-thick.yml | kubectl apply -f -`
 to
 `kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml`

**Why is this needed**:
It is easier to install the `multus-cni` this way. Without cloning it. IMO

But feel free to close this issue if you think this is not necessary.

**Comment by dougbtv** [comment]
That's fair enough, I think we might also do that in the quickstart guide? I'm unsure. But feel free to file a PR to change the README, appreciate it.
