### ISSUE TITLE
When will there be another release?

### ISSUE THREAD

**Issue by seastco** [k8snetworkplumbingwg/multus-cni#1316]
Last multus release v4.0.2 was over a year ago. I see plenty of changes merged into master since then. I'd like some of these changes, but are they not "production ready"?

**Comment by dougbtv** [comment]
Appreciate the reminder! We were overdue for a regular maintenance release but had decided to publish a release following some fixes in the last maintainer's call -- and... :drum: drum roll please...

https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v4.1.0

is available! appreciate the issue :+1:

**Comment by seastco** [comment]
woo, thank you!
