### ISSUE TITLE
Multus 4.0.2 delegates to itself, breaking networking

### ISSUE THREAD

**Issue by EyeCantCU** [k8snetworkplumbingwg/multus-cni#1324]
**What happend**:

The very first network configuration file is selected as the delegate. This file is always `00-multus.conf` in `/etc/cni/net.d/`.  `10-calico.conflist` is then correctly appended to `00-multus.conf`

When restarting the multus pod, it appends the configuration for `00-multus.conf` to all delegates (now including itself), breaking networking. Restart after restart, the file gets larger and larger due to this

**What you expected to happen**:

Multus would not delegate to itself

**How to reproduce it (as minimally and precisely as possible)**:

- Install RKE2
- Deploy Calico with Tigera operator
- Fetch daemonset config: `curl -O https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset.yml`
- Sub in 4.0.2: `sed -i 's+ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot+ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2+' multus-daemonset.yml``
- Apply the daemonset: `kubectl apply -f multus-daemonset.yml`
- At this point, we have a working setup
- Restart the `kube-multus` pod <- this is where things break

Multus will have delegated to itself breaking networking

**Anything else we need to know?**:

Rancher provides a patch that addresses this: https://github.com/rancher/image-build-multus/blob/v4.0.2-build20231009/self_delegation_bug.patch

Would this be possible to apply in a 4.0.3 patch release?

**Environment**:

- Multus version, image path, and image ID (from 'docker images'): `ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2`
- Kubernetes version (use `kubectl version`): 1.31.0
- Primary CNI for Kubernetes cluster: Calico

**Comment by mamccorm** [comment]
There may already be a similar fix for this in the v4.1 release, but due to dependencies it'd be great to get this back-ported to v4.0.2. As there's no branch for v4.0.2, here's a proposal:
 - https://github.com/k8snetworkplumbingwg/multus-cni/compare/v4.0.2...mamccorm:multus-cni:fix/append-cni-configs

**Comment by dougbtv** [comment]
Looks like it's fixed up, thanks for the report
