### ISSUE TITLE
Install reference CNI plugins as part of Multus daemonset-style installation

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/multus-cni#192]
**What would you like to be added**: Installation of reference CNI plugins via Multus daemonset style installation

**Why is this needed**: It'll make the quick-start guide easier to use as the reference plugins will already be available.

**Comment by micw** [comment]
One option could be to add coreos-flannel-cni as init-container to the daemonset and run line 5-8 of https://github.com/coreos/flannel-cni/blob/master/install-cni.sh

**Comment by micw** [comment]
I have created a pull-request for this. With this change I can easily setup a while kubernetes cluster with multus+flannell without manual steps

**Comment by micw** [comment]
I have created a PR to the reference CNI binaries to provide a Docker-Image that contains this binaries (https://github.com/containernetworking/plugins/issues/244) - if that's accepted we can switch to that image.

**Comment by c0ffee** [comment]
seems like there is not much movement on the containernetworking side, why did this one get closed?

**Comment by e0ne** [comment]
@dougbtv  As I know, Multus is only one consumer of CNI plugins in a pod. It makes sense to upload image to k8snetworkplumbingwg's repo until we'll have any agreement with containernetworking team

**Comment by dougbtv** [comment]
Current Nvidia Dockerfile: https://github.com/Mellanox/k8s-images/tree/master/container-networking-plugins
Created: https://github.com/k8snetworkplumbingwg/plugins

The new NPWG repo can be used for this purpose, and to resolve this issue, we'll add some docs to Multus.

**Comment by maxpain** [comment]
Any updates?
