### ISSUE TITLE
system:node can't list namespaces

### ISSUE THREAD

**Issue by Miouge1** [k8snetworkplumbingwg/multus-cni#301]
Some pods are stuck in `ContainerCreating` and show the following error
```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e3d4a705961e37b849a3138a48f8ccfbb5f2dd9a74b3e70c69d0f4a327f90076" network for pod "netchecker-server-864bd4c897-46kfh": NetworkPlugin cni failed to set up pod "netchecker-server-864bd4c897-46kfh_default" network: Multus: Err in tearing down failed plugins: Multus: error in invoke Conflist add - "cni0": error in getting result from AddNetworkList: namespaces "default" is forbidden: User "system:node:k8s-55149838-190425041-2" cannot get resource "namespaces" in API group "" in the namespace "default"
```

Adding `get`, `list`, `watch` permissions for `namespaces` in the `system:node` `ClusterRole` removes this error message, but the default value for `system:node` doesn't seem to work.

**Comment by s1061123** [comment]
Could you please let me know "how to install multus (daemonset yaml file or just copy?)", "multus CNI config (in /etc/cni/net.d)"?

**Comment by dougbtv** [comment]
Also do you have any information on what Kubernetes version you're using?

**Comment by Miouge1** [comment]
This was on v1.13 installed with Kubespray v2.9.0

**Comment by psiwczak** [comment]
Having same issue after the upgrade from v1.12.5.

**Comment by s1061123** [comment]
I install kubernetes (v1.14.0) with kubespray v2.9.0/CentOS (`kube_network_plugin=calico` + `kube_network_plugin_multus=true`) but cannot see the such error (succeed to launch following yaml pod, *1), so need more information for the issue. In addition, kubeadm does not happen the issue.

I guess I miss something to repro the issue and I need your info for that. Could you please let me know following information?

- net-attach-def yaml
- pod yaml file
- kubespray config
- how to install multus (if you don't use kubespray to install multus)

```
# *1: yaml file tested with kubespray 2.9.0 + k8s v1.14.0 + CentOS 7.6.1810
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-eth1
spec: 
  config: '{
                "cniVersion": "0.3.0",
		"name": "test",
                "plugins": [ 
                {
                        "type": "vlan",
                        "master": "eth1",
		        "vlanId": 1,
                        "ipam": {
                                "type": "static",
                                "addresses": [ { "address": "172.16.1.10/24", "gateway": "172.16.1.1" } ],
                                "routes": [ { "dst": "0.0.0.0/0" } ]
                        }
                },
                {
                        "type": "route-overwrite",
                        "flushgateway": false
                }]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-01
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "vlan-eth1"
            }
    ]'
spec:
  containers:
  - name: pod-case-01
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
```

**Comment by s1061123** [comment]
@Miouge1 @psiwczak One q for your setting. Do you use `/etc/kubernetes/kubelet.conf` for `kubeconfig` in `/etc/cni/net.d/*multus.conf`?

**Comment by dougbtv** [comment]
@Miouge1 and @psiwczak -- we just located this issue while looking through some backlog -- have either of you tried this with a recent version of Kubespray? We'd love to get some information on it.
