### ISSUE TITLE
checkpoint deviceIDs in wrong order on cmdDel

### ISSUE THREAD

**Issue by pkdas** [k8snetworkplumbingwg/multus-cni#367]
**What happend**:
Created 3 networks using SRIOV and SRIOVDP, net1, net2, net3 on a POD my-pod1.
Multus debug log shows:
2019-08-28T21:51:12-04:00 [debug] getPodEntries(): podEntires [{PodUID:76d02df2-c9ff-11e9-a0c4-246e9666b9d4 ContainerName:my-pod1 ResourceName:my/sriov DeviceIDs:[0000:18:02.4 0000:18:02.0 0000:18:02.3] AllocResp     :[10 63 10 21 80 67 73 68 69 86 73 67 69 95 86 67 67 65 80 95 83 82 73 79 86 18 38 48 48 48 48 58 49 56 58 48 50 46 51 44 48 48 48 48 58 49 56 58 48 50 46 52 44 48 48 48 48 58 49 56 58 48 50 46 48]}]
 745 2019-08-28T21:51:12-04:00 [debug] getCheckpoint(): created checkpoint instance with file: /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint

Add a second POD, my-pod2 with 2 networks using SRIOV and SRIOVDP net1, net2 
2019-08-28T21:51:55-04:00 [debug] getPodEntries(): podEntires [{PodUID:76d02df2-c9ff-11e9-a0c4-246e9666b9d4 ContainerName:my-pod1 ResourceName:my/sriov DeviceIDs:[0000:18:02.3 0000:18:02.4 0000:18:02.0] AllocResp     :[10 63 10 21 80 67 73 68 69 86 73 67 69 95 86 67 67 65 80 95 83 82 73 79 86 18 38 48 48 48 48 58 49 56 58 48 50 46 51 44 48 48 48 48 58 49 56 58 48 50 46 52 44 48 48 48 48 58 49 56 58 48 50 46 48]} {PodUID:901ce43f     -c9ff-11e9-a0c4-246e9666b9d4 ContainerName:my-pod2 ResourceName:my/sriov DeviceIDs:[0000:18:02.1 0000:18:02.2] AllocResp:[10 50 10 21 80 67 73 68 69 86 73 67 69 95 86 67 67 65 80 95 83 82 73 79 86 18 25      48 48 48 48 58 49 56 58 48 50 46 50 44 48 48 48 48 58 49 56 58 48 50 46 49]}]

NOTE that the DeviceIDs list  of the first POD changed from
DeviceIDs:[0000:18:02.4 0000:18:02.0 0000:18:02.3]
to
DeviceIDs:[0000:18:02.3 0000:18:02.4 0000:18:02.0] 
The device manager checkpoint file got updated when my-pod2 is created but the entries for my-pod1 got shuffled .

Now when  my-pod1 is deleted
multus deletes ne3, net2, net1 in that order but with deviceIds in but picks device Ids in this order 0000:18:02.0 0000:18:02.4 0000:18:02.3 which is different from the order when it is added.

On cmdAdd my-pod1/net1 uses  deviceId 0000:18:02.4 
On cmdDel my-pod1/net1 uses  deviceId 0000:18:02.3 

On cmdAdd my-pod1/net2 uses  deviceId 0000:18:02.0 
On cmdDel my-pod1/net2 uses  deviceId 0000:18:02.4

On cmdAdd my-pod1/net3 uses  deviceId 0000:18:02.3
On cmdDel my-pod1/net3 uses deviceId becomes 0000:18:02.0

**What you expected to happen**:
On cmdAdd my-pod1/net1 uses  deviceId 0000:18:02.4 
On cmdDel my-pod1/net1 uses  deviceId 0000:18:02.4 

On cmdAdd my-pod1/net2 uses  deviceId 0000:18:02.0 
On cmdDel my-pod1/net2 uses  deviceId 0000:18:02.0

On cmdAdd my-pod1/net3 uses  deviceId 0000:18:02.0
On cmdDel my-pod1/net3 uses deviceId becomes 0000:18:02.0

**How to reproduce it (as minimally and precisely as possible)**:
Random, occurs pretty often. Looks like DeviceManager is shuffling the DeviceIDs of the already allocated PODs when a new POD gets allocated DeviceManager resources

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by pkdas** [comment]
The order of deviceId in DeviceIDs allocated for a POD should not matter as long as it does not change.
If multus can read the deviceIDs and sorted order then cmdAdd and cmdDel deviceId allocated for a network will remain consistent

**Comment by pkdas** [comment]
Ubuntu 16.04.4 LTS, K8S version 1.11.11
Multus version release 3 - does not look like anything changed in checkpoint/checkpoint.go

**Comment by pkdas** [comment]
I believe this problem will also occur when checkpoint file is not used. It appears the DeviceManager
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go
writes in unsorted order

**Comment by ahalim-intel** [comment]
From sriov-cni perspective, on deletion it is not depend on the deviceID from Multus since sriov-cni caches each interface information during CmdAdd and uses that as a 'source of truth' during CmdDel. And from multus perspective as long as Multus invokes Del on Pod interfaces in right order sriov-cni will execute the delete using same deviceID that it had during Add for that interface. 

As a side note, Multus also caches delegate conf. So, the Pod deviceID query will happen in fallback scenario on deletion. Even if a different deviceID is injected in the delegate object during deletion sriov-cni will ignore that.

Please do let us know, if this is not the case.

**Comment by pkdas** [comment]
The delegate conf lookup is ok.  The SRIOV-CNI only caches DPDK device config. I don't think SRIOV CNI caches non-DPDK. If VF PCIe-addr is wrong, the VF id is wrong and VLAN will not get cleared on the right VF.  This may not be problem for MLNX ConnectX5 but i40e requires VLAN to cleared to 0 before a new VLAN can be applied. So if the old VLAN is not cleared on VF, the new VLAN will not get applied.

**Comment by ahalim-intel** [comment]
The sriov-cni caches all interface configs (dpdk and non-dpdk). I'd suggest do some more tests with the latest branch and see if you genuinely hit any of these issues that you suspect there might be.
