### ISSUE TITLE
Rename net1 to eth1

### ISSUE THREAD

**Issue by brysk** [k8snetworkplumbingwg/multus-cni#385]
Hello Multus Folks,

Can you please tell if it's possible to rename secondary interfaces name from netX to ethX?

For example:

eth0 - kube cluster net
eth1 - sriov interface
eth2 - sriov interface

Thanks

**Comment by brysk** [comment]
Another question would be if it's possible to have eth0 plugged into network different than kube cluster net but for example OVS CNI.

eth0 - OVS CNI
eth1 - SRIOV CNI
eth2 - kube cluster net

awaiting your feedback, thanks

**Comment by s1061123** [comment]
@brysk , using 'interface' in annotation, you can change interface name of net-attach-def.
Please see example and its specification as follows:
spec (see 4.1.2.1.5 "interface"): https://github.com/K8sNetworkPlumbingWG/multi-net-spec/blob/master/%5Bv1%5D%20Kubernetes%20Network%20Custom%20Resource%20Definition%20De-facto%20Standard.md

example: https://github.com/intel/multus-cni/blob/master/examples/npwg-demo-1/12_pod_case2.yml

For now, you cannot configure cluster network name (i.e. eth0). Is there any clear use case for that?

**Comment by brysk** [comment]
thanks @s1061123 

One of the customers has a requirement to have eth0 connected to public network. Otherwise they would need to reconfigure their product quite a lot so I was thinking about eth0 attached to OVS bridge.
