### ISSUE TITLE
Additional interfaces are not created in pod

### ISSUE THREAD

**Issue by michaelspedersen** [k8snetworkplumbingwg/multus-cni#392]
Hi,

I am trying to set up Multus on a Kubernetes cluster, but while everything (daemonset, pods, network definitions) looks to be configured and running correctly, I am not seeing any additional interfaces in my pods.

Going through the steps, I started with a "clean" kubernetes cluster (v1.12.2), and did the following:
```
# Deploy Flannel
$ kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

Checking with `kubectl`, both the Flannel daemonset and pod deploys and runs as expected. Checking on the node, the Flannel configuration is available as well:
```
$ cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=100.96.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true


$ cat /etc/cni/net.d/10-flannel.conflist
{
  "name": "cbr0",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
```

With Flannel deployed, I deploy the Multus daemonset as follows:
```
$ kubectl apply -f images/multus-daemonset-pre-1.16.yml
```

Once again checking with `kubectl`, both daemonset and pod deploys and runs. Checking the log of the Multus pod shows that a configuration has been generated:
```
$ kubectl logs kube-multus-ds-amd64-(...) -n kube-system
Generating Multus configuration file ...
Config file created @ /host/etc/cni/net.d/00-multus.conf
Entering sleep... (success)

# Checking the configuration on the node
$ cat /etc/cni/net.d/00-multus.conf
{ "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "cbr0", "cniVersion": "0.3.1", "plugins": [ { "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true } },
{ "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }
```

Before going further, I deploy a basic pod to check the network configuration:
```
# Pod definition
apiVersion: v1
kind: Pod
metadata:
  name: simplepod
spec:
  containers:
  - name: simplepod
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    
# Interfaces in the running pod
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if38: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default
    link/ether 0a:58:64:60:00:1d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.96.0.29/24 scope global eth0
       valid_lft forever preferred_lft forever
```

At this point, I use the examples provided as part of the [SRIOV Network Device Plugin](https://github.com/intel/sriov-network-device-plugin) to set up the `net-attach-def` CRD:
```
$ kubectl apply -f deployments/crdnetwork.yaml
```

I then add a couple of network definitions for flannel and macvlan:
```
# Flannel-net
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel-net
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "flannel",
    "delegate": {
      "isDefaultGateway": true
    }
  }'

# Macvlan-conf
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.55.1.0/24",
        "rangeStart": "10.55.1.200",
        "rangeEnd": "10.55.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.55.1.1"
      }
    }'
```

The definitions are added and are visible through `kubectl`:
```
$ kubectl get net-attach-def
NAME           AGE
flannel-net    1h
macvlan-conf   1h
```

At this point I create a pod with both of the above networks / interfaces, but none of them are visible in the running pod:
```
# Pod definition
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  annotations:
    k8s.v1.cni.cncf.io/networks: flannel-net, macvlan-conf
spec:
  containers:
  - name: testpod
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]

# Interfaces in the running pod
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if42: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default
    link/ether 0a:58:64:60:00:21 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.96.0.33/24 scope global eth0
       valid_lft forever preferred_lft forever
```

Looking at the annotations for the pod, the `network-status` is missing, which also indicates that the pod isn't being configured properly:
```
$ kubectl get pod testpod -o jsonpath='{.metadata.annotations}'
map[k8s.v1.cni.cncf.io/networks:flannel-net, macvlan-conf kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"flannel-net, macvlan-conf"},"name":"testpod","namespace":"default"},"spec":{"containers":[{"args":["while true; do sleep 300000; done;"],"command":["/bin/bash","-c","--"],"image":"centos/tools","imagePullPolicy":"IfNotPresent","name":"testpod"}]}}
```

At this point I have tried deploying several times, using both the daemonset and binary approach. The result is the same either way (no additional interfaces).

Am I missing steps during the deployment, or are there ways to get additional (debug) information about Multus after it has been deployed?

Thanks in advance.

**Comment by Asara** [comment]
I am having the same issue.  When adding the interface as a delegate in the multus config, the delegates are added to every pod, but when supplying the configuration via annotations, the networks never come up. I also see no attempt at their creation/connection when setting debug logs on multus. 

This is using multus 3.3 with k8s 1.16.

**Comment by dougbtv** [comment]
Can you provide the generated configuration on-disk? That is, the contents of the `/etc/cni/net.d/00-multus.conf` -- or whatever file is alphabetically first in that directory. 

The fact that it didn't have a status annotation to me seems that Multus didn't run at all. Thanks!

**Comment by dougbtv** [comment]
You may also want to enable debugging, check out: https://github.com/intel/multus-cni/blob/master/doc/configuration.md#logging

**Comment by michaelspedersen** [comment]
Hi @dougbtv, and thanks for the response.

I found the culprit for my issues: Kubelet was configured with the wrong network plugin.
After doing the following change I am able to add interfaces through Multus:
```
[Before] --network-plugin=kubenet
[After]  --network-plugin=cni
```

I'll let you decide if the issue should be closed or kept open, as @Asara mentioned a slightly different issue.
