### ISSUE TITLE
Can a Pod know about mapping between interface names and resource pool name?

### ISSUE THREAD

**Issue by devdattakulkarni** [k8snetworkplumbingwg/multus-cni#405]
We have two NetworkAttachmentDefinition objects used by one Pod. Multus creates two interfaces (net1 and net2), besides the default network (eth0). Is it possible for POD to know the mapping between interfaces and NetworkAttachmentDefinition resource pool name? If not, is it possible to define own interface names in a NetworkAttachment definition object, which can then be used when associating a VF to a Pod?

Specifically, referring to the following example, the Pod's net0 interface is configured to be a VF
https://github.com/intel/sriov-network-device-plugin#deploy-sr-iov-workloads-when-multus-is-used

The NetworkAttachmentDefinition object name used is: sriov-net1
The resourceName used is: intel_sriov_netdevice

It is possible for the Pod to know that net0 is mapped to intel_sriov_netdevice? 

Currently it seems that a Pod can know about the device information through an environment variable as noted here:
https://github.com/intel/sriov-network-device-plugin#pod-device-information

Is something similar available to know the mapping between the allocated interface and the resourceName?

If not, it is possible to control the name of the interface (net0, net1, etc.) through NetworkAttachmentDefinition?

**Comment by s1061123** [comment]
@pliurh @zshi-redhat PTAL? I suppose it is strongly related to SR-IOV DP.

**Comment by zshi-redhat** [comment]
@devdattakulkarni Hi, I think you can first get pci address of `net1`, then from env var, map the pci address to resource name. although the resource name from env var is not exact same as name exposed in kubelet node status.

Or if you have resource pool name is 1:1 mapped to a net-attach-def name, then multus network status published in pod annotation can tell which net-attach-def mapped to which interface name (`net1`..).

for example, below is the multus network status published in pod annotation:
```
Namespace:    default
Priority:     0
Node:         dev-worker-0/192.168.111.15
Start Time:   Thu, 14 Nov 2019 01:18:05 -0500
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks:
                [ { "name": "sriov-intel", "ips": ["192.168.10.12/24", "2001::12/64"], "default-route": ["192.168.10.1", "2001::1"] } ]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.129.0.104"
                    ],
                    "dns": {}
                },{
                    "name": "sriov-net",  <== net-attach-def name
                    "interface": "net1",    <== interface name
                    "ips": [
                        "192.168.10.12",
                        "2001::12"
                    ],
                    "mac": "0a:fd:78:0f:8a:d9",
                    "dns": {},
                    "default-route": [
                        "192.168.10.1",
                        "2001::1"
                    ]
                }]
```

Pod annotation can be mapped to pod/container as a file via downward API, your application can get the network status from this mapped file without accessing kube API.
