### ISSUE TITLE
Use bridge cni plugin with L2-Only but error in invoke Delegate add

### ISSUE THREAD

**Issue by xzcccc** [k8snetworkplumbingwg/multus-cni#419]
Hi,

I have a k8s Cluster with calico.
I have deployed Multus successfully and I can create a POD with the 2nd network interface with macvlan/ptp/bridge plugin, however, when I use the bridge with L2-only, the pod can't create successfully, it just post as followed: 

`
Warning  FailedCreatePodSandBox  2m23s (x76 over 11m)  kubelet, k8s-office-02  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "f70391d455c0e7d814609ec406bc4f64a17ed7ba5fd11d63d2259251915a249f" network for pod "virt-launcher-vmi-multus-multiple-net-bridge-stfxc": NetworkPlugin cni failed to set up pod "virt-launcher-vmi-multus-multiple-net-bridge-stfxc_default" network: Multus: Err adding pod to network "BL2": Multus: error in invoke Delegate add - "bridge": no plugin name provided, failed to clean up sandbox container "f70391d455c0e7d814609ec406bc4f64a17ed7ba5fd11d63d2259251915a249f" network for pod "virt-launcher-vmi-multus-multiple-net-bridge-stfxc": NetworkPlugin cni failed to teardown pod "virt-launcher-vmi-multus-multiple-net-bridge-stfxc_default" network: Multus: error in invoke Delegate del - "bridge": no plugin name provided]
`

Here is some details about my environment:

1. k8s version
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

2. Multus daemon-set:
```
$ kubectl get po -n kube-system | grep -i multus
kube-multus-ds-amd64-hbrlf                 1/1     Running   0          6d20h
kube-multus-ds-amd64-pddn7                 1/1     Running   0          6d20h

$ kubectl get network-attachment-definitions
NAME             AGE
bridge-conf      47h
bridge-l2-conf   47h
flannel-conf     6d19h
macvlan-conf     6d19h
ptp-conf         6d19h
```
3. bridge-l2-conf:
```
$ kubectl get network-attachment-definitions bridge-l2-conf -o yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  creationTimestamp: "2019-12-02T03:30:55Z"
  generation: 3
  name: bridge-l2-conf
  namespace: default
  resourceVersion: "2083664"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/bridge-l2-conf
  uid: 3109230d-b57f-43a5-bd6e-3cf1c64826f4
spec:
  config: '{ "cniVersion": "0.3.1", "name": "BL2", "type": "bridge", "bridge": "brL2",
    "ipam": {} }'

$ cat  bridge-l2-conf.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-l2-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "BL2",
      "type": "bridge",
      "bridge": "brL2",
      "ipam": {}
    }'

```

4. pod state:
```
kubectl get po
NAME                                                 READY   STATUS              RESTARTS   AGE
virt-launcher-vmi-multus-multiple-net-bridge-stfxc   0/2     ContainerCreating   0          20m
virt-launcher-vmi-multus-multiple-net-pqpbb          2/2     Running             0          2d18h
```

5. work node /var/lib/cni
```
$ ls -al /var/lib/cni/networks/
total 20
drwxr-xr-x 5 root root 4096 Dec  2 10:48 .
drwxr-xr-x 6 root root 4096 Nov 27 14:37 ..
drwxr-xr-x 2 root root 4096 Dec  2 11:42 bridge-conf
drwxr-xr-x 2 root root 4096 Dec  1 16:16 macvlan-conf
drwxr-xr-x 2 root root 4096 Nov 29 16:04 ptp-conf 
```

I wonder if there's any difference between bridge and bridge-layer2-only, or is there something wrong with my configuration?

Thanks!

**Comment by yanovich** [comment]
I've had the same issue on microk8s on ubuntu 20.04. Building from source and installing latest cni plugins helped.
