### ISSUE TITLE
Coredns pods are still in pending state after installing multus cni in master node

### ISSUE THREAD

**Issue by laxman356** [k8snetworkplumbingwg/multus-cni#428]
So far...
1) Installed Kubernetes.
2) Brought up master cluster.
3) Installed Multus CNI... Pods are up and running.
4) But, the coredns pods are stuck in pending state.

root@single-node:~# kubectl get pods -A
NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE
kube-system   coredns-6955765f44-dhb5g              0/1     Pending   0          4m31s
kube-system   coredns-6955765f44-ntdl2              0/1     Pending   0          4m31s
kube-system   etcd-single-node                      1/1     Running   0          4m26s
kube-system   kube-apiserver-single-node            1/1     Running   0          4m26s
kube-system   kube-controller-manager-single-node   1/1     Running   0          4m26s
kube-system   kube-multus-ds-amd64-qmkdr            1/1     Running   0          67s
kube-system   kube-proxy-p4gpx                      1/1     Running   0          4m30s
kube-system   kube-scheduler-single-node            1/1     Running   0          4m25s

5) Installed weave net cni and then the coredns pods came up.

root@single-node:~# kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS    RESTARTS   AGE
kube-system            coredns-6955765f44-djxhk                     1/1     Running   0          136m
kube-system            coredns-6955765f44-gpbx5           1/1     Running   0          136m
kube-system            etcd-single-node                             1/1     Running   0          136m
kube-system            kube-apiserver-single-node                   1/1     Running   0          136m
kube-system            kube-controller-manager-single-node          1/1     Running   0          136m
kube-system            kube-proxy-nxmpc                             1/1     Running   0          136m
kube-system            kube-scheduler-single-node                   1/1     Running   0          136m
kube-system            weave-net-kx86v                              2/2     Running   0          135m
kubernetes-dashboard   dashboard-metrics-scraper-76585494d8-jw7bl   1/1     Running   0          132m
kubernetes-dashboard   kubernetes-dashboard-b7ffbc8cb-xvjkf         1/1     Running   0          132m

**Comment by dougbtv** [comment]
@laxman356 I think we need to have you change up the order during the installation a bit...

Instead... Install Weave CNI as step 2. Then proceed and install Multus CNI after that and it will keep your default CNI plugin as Weave and then the coreDNS pods should come up correctly.

**Comment by NAYANSEN90** [comment]
Multus delegates the job to another CNI say weave or flannel. They are in charge of the actual networking. CoreDNS requires a network to work. As @dougbtv mentioned install weave/flannel first and then use Multus CNI. Multus will then use this plugin as the master plugin.
