### ISSUE TITLE
multus cni   plugin

### ISSUE THREAD

**Issue by lxf762607303** [k8snetworkplumbingwg/multus-cni#432]
When one pod generates three ips, how to configure multus cin plug-in and how to write the config file

**Comment by lxf762607303** [comment]
When one pod generates three ips, how to configure multus cin plug-in and how to write the config file


“data:
  cni-conf.json: |
    {
      "name": "multus-demo",
      "type": "multus",
      "delegates": [
        {
          "type": "macvlan",
          "master": "ens33",
          "mode": "vepa",
          "isGateway": true,
          "ipMasq": false,
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.166.0/24",
            "rangeStart": "192.168.166.21",
            "rangeEnd": "192.168.166.29",
            "routes": [
              { "dst": "0.0.0.0/0" }
            ],
            "gateway": "192.168.166.2"
         }
        },
        {
          "type": "flannel",
          "masterplugin": true,
          "delegate": {
            "isDefaultGateway": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }”
data:
  cni-conf.json: |
    {
      "name": "multus-demo",
      "type":vxlan
}
}"
When I looked at the dscribe information for the pod, the message showed up as follows


Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "41bf89d16ed75a2dd873057207c5641b63791e9565ce5042eb5d144f28e3aa34" network for pod "nginx-deployment-76bf4969df-kvplc": NetworkPlugin cni failed to set up pod "nginx-deployment-76bf4969df-kvplc_default" network: Multus: [default/nginx-deployment-76bf4969df-kvplc]: error adding container to network "": delegateAdd: error invoking DelegateAdd - "macvlan": error in getting result from AddNetwork: failed to find plugin "macvlan" in path [/opt/cni/bin /opt/cni/bin], failed to clean up sandbox container "41bf89d16ed75a2dd873057207c5641b63791e9565ce5042eb5d144f28e3aa34" network for pod "nginx-deployment-76bf4969df-kvplc": NetworkPlugin cni failed to teardown pod "nginx-deployment-76bf4969df-kvplc_default" network: delegateDel: error invoking DelegateDel - "flannel": error in getting result from DelNetwork: invalid version "": the version is empty / delegateDel: error invoking DelegateDel - "macvlan": error in getting result from DelNetwork: invalid version "": the version is empty]

**Comment by dougbtv** [comment]
Looks like the `macvlan` plugin isn't found in the path `/opt/cni/bin` -- can you make sure it's installed? That plugin comes from the https://github.com/containernetworking/plugins repo where you can build and copy the binary.
