### ISSUE TITLE
second interface using multus is not reachable 

### ISSUE THREAD

**Issue by jenifermajella02** [k8snetworkplumbingwg/multus-cni#471]
Hi ,

I am using single node cluster with calico as the plugin.
I tried creating 2 pods with 2 interfaces each. The second interface is created using multus. Here is my yaml.

kind: NetworkAttachmentDefinition
apiVersion: "k8s.cni.cncf.io/v1"
metadata:
  name: eth2
spec: 
  config: '{
    "name": "eth2",
    "plugins": [
      {
        "type": "bridge",
        "master": "eth0",
        "ipam": {
          "type": "static",
          "addresses": [
            {
                "address": "10.0.30.32/24",
                "gateway": "10.0.30.1"
            }
          ],
          "dns": {
            "nameservers" : ["10.0.30.1"]
          }
        }
      },
      {
        "type": "sbr"
      }
    ]
  }'

---
apiVersion: v1
kind: Pod
metadata:
   name: sample
   annotations:
     k8s.v1.cni.cncf.io/networks: '[
            { "name" : "eth2",
              "interface": "eth1" }
    ]'
spec:
   containers:
   - name: sample
     image: sample_kgeneric:v0.16
     command: ["python", "/root/Main.py" ,"trap : TERM INT; sleep infinity & wait"]
---------------------------------------------------------------------------------------------

Another yaml is:

kind: NetworkAttachmentDefinition
apiVersion: "k8s.cni.cncf.io/v1"
metadata:
  name: eth1
spec: 
  config: '{
    "name": "eth1",
    "plugins": [
      {
        "type": "bridge",
        "master": "eth0",
        "ipam": {
          "type": "static",
          "addresses": [
            {
                "address": "10.0.30.30/24",
                "gateway": "10.0.30.1"
            }
          ],
          "dns": {
            "nameservers" : ["10.0.30.1"]
          }
        }
      },
      {
        "type": "sbr"
      }
    ]
  }'

---
apiVersion: v1
kind: Pod
metadata:
   name: ut
   annotations:
     k8s.v1.cni.cncf.io/networks: '[
            { "name" : "eth1",
              "interface": "eth1" }
    ]'
spec:
   containers:
   - name: ut
     image: ut:v0.1
     command: ["/root/loop.sh", "-d" ,"trap : TERM INT; sleep infinity & wait"]

---------------------------------------------------------------------------------------------
I logged inside a pod and tried to ping the second interface of another pod.
The second interface is not reachable.  Anyone can sort out the issue?

Note: I have tried the same with flannel pluggin too. Same result. couldnt ping between second interface.

**Comment by Elegant996** [comment]
Could you provide the command you're using to ping? If I recall `ping -I eth1 google.com` would fail but `ping -I 10.244.0.250 google.com` would succeed which had to do with how interfaces are handled. Thanks!
