### ISSUE TITLE
 error in getting result from DelNetwork: invalid version "": the version is empty

### ISSUE THREAD

**Issue by lynic** [k8snetworkplumbingwg/multus-cni#476]
I use following yaml for network, which didn't include the "cniVersion", for creating, it works fine, but failed to remove the interface from pod.
```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_neta
spec:
  config: |
    {
      "type": "sriov",
      "name": "upf-core"
    }
```

**What happend**:
 error in getting result from DelNetwork: invalid version "": the version is empty

**What you expected to happen**:
interface was remove from pod and rename back.

**How to reproduce it (as minimally and precisely as possible)**:
Use that yaml to create a network and create  a pod with that network.

**Anything else we need to know?**:

**Environment**:

- Multus version 3.4
- Kubernetes version (use `kubectl version`): 1.17
- Primary CNI for Kubernetes cluster: calico

**Comment by mukesh-dua** [comment]
You need to have "cniVersion: 0.3.1" in your config section.

**Comment by lynic** [comment]
> You need to have "cniVersion: 0.3.1" in your config section.

I start multus daemonset with "--cni-version=0.3.1", I thought it would be the default value in the networkattachmentdefinition , but seems it doesn't work like that.
I saw some old multus users still haven't set this value in their networkattachmentdefinition, could we support his case?
