### ISSUE TITLE
How about a "multusctl" utility?

### ISSUE THREAD

**Issue by tliron** [k8snetworkplumbingwg/multus-cni#488]
**What would you like to be added**:

It would be great if we had a `multusctl` utility to simplify and enhance the experience of using and installing Multus.

Of course it's possible to use `kubectl` for everything, but why not do better?

**Why is this needed**:

Some examples of what I have in mind:
```
# Install Multus without having to use "kubectl apply ..."
# The --wait switch can block until everything is running

multusctl install --wait

# Create a NetworkAttachmentDefinition
# Allows using YAML in addition to JSON, and automatically
# stringifies it for inclusion in the custom resource spec

multusctl create myattachment --config=config.yaml

# This will list all NetworkAttachmentDefinition custom resources
# and for each show all pods that have annotated an attachment to them
# Even better: support KubeVirt and show which VirtualMachineInstance
# custom resources attach to them

multusctl list
```
If the team is interested in this feature, I'm willing to contribute some time towards getting the ball rolling. I have experience in creating "-ctl" tools for other Kubernetes projects.

**Comment by dougbtv** [comment]
@tliron this is interesting, and looks pretty slick, a nice UX enhancement. Would you like to join our next maintainers meeting to discuss the creation of such a utility? 

Agenda doc @ https://docs.google.com/document/d/17-vkuoObBFBb6feXNA7tjTaKr-rs8ea0VTnqvlEdCv8/edit#

**Comment by tliron** [comment]
@dougbtv I went ahead and [created it](https://github.com/tliron/multusctl). :)

Please consider it a prototype -- it actually relies on code I wrote for other projects, and as such could not be included as is in Multus. However, with some work it would be easy enough to make it entirely independent of other projects.

It doesn't have `create` yet, but it can `install` and `uninstall` Multus without requiring any assets, including support for `install --wait` that blocks until Multus is up and running. The `list` command will show network attachment definitions in a namespace with names of pods that attach to each one.

I can demo it at the maintainers meeting and we can discuss if it can be an addition to Multus.

**Comment by electrocucaracha** [comment]
Hey @tliron, I just noticed this proposal which it's a great utility but I was wondering if this could be offered as [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/). Using that approach the commands can be executed as follow:

`kubectl multus install --wait`

**Comment by tliron** [comment]
Absolutely. It would be using [Krew](https://github.com/kubernetes-sigs/krew/). I haven't done the wiring for that, but should be trivial.

**Comment by tliron** [comment]
@electrocucaracha On further look, no need to use Krew. It's enough the name the executable "kubectl-multus" and have in the execution path, so kubectl will immediately pick it up as a plugin. Integrating with Krew is useful if we want to make it easier for people to install it.

**Comment by tliron** [comment]
Has there any progress about considering this tool? I'm happy to do the initial work, but I want to be sure that the Multus core team would accept some ownership on its ongoing maintenance.

**Comment by tliron** [comment]
^^ bump ^^

I am willing to help out and contribute this tool to the project, but I need help guidance core team members.

**Comment by dougbtv** [comment]
Woot! Any shot you can make the maintainer's meeting next week? Thursday
morning. Tomo also has a kubectl add-on that might make a good home (but I
need his input too).

Thanks Tal!

**Comment by s1061123** [comment]
Suppose that we can put multusctl in our org, k8snetworkplumbingwg as new
repository because multusctl is more than kubectl plugin. How about to
bring this topic in NPWG this week, not maintainers meeting?

**Comment by tliron** [comment]
Just let me know what you decide and send me an invite to the meeting!

**Comment by s1061123** [comment]
I decide to propose it as a one project under NPWG, https://github.com/k8snetworkplumbingwg as multus-cni itself.

I add your proposal in next meeting agenda, so let's discuss about it in NPWG meeting.
https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit

**Comment by tliron** [comment]
Bumped to remove stale label.

**Comment by tliron** [comment]
In progress, not stale.

**Comment by tliron** [comment]
Not stale.

**Comment by tliron** [comment]
The project has been approved. This is its new home: https://github.com/k8snetworkplumbingwg/multusctl
