### ISSUE TITLE
Unable to get the additional interface

### ISSUE THREAD

**Issue by nitinbedazzled** [k8snetworkplumbingwg/multus-cni#491]
I am new to kubernetes and learning new things.
So while trying multus-cni for the first time and decided to NOT to use the daemonset mode as wanted to see how things work.

System specification:-
root@Cluster-Manager:~/multus-cni# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

root@Cluster-Manager:~/multus-cni# kubectl get nodes
NAME              STATUS   ROLES    AGE   VERSION
cluster-manager   Ready    master   16d   v1.18.2
workernode1       Ready    <none>   16d   v1.18.2
workernode2       Ready    <none>   16d   v1.18.2

Cluster already had a default plugin as Calico installed.
Setup has been created using the kubeadm.

now i tried to deploy the Multus

Picked up the latest build from https://github.com/intel/multus-cni/releases v3.4.1 and placed it (followed on all the nodes)
root@Cluster-Manager:~# ls /opt/cni/bin/multus
/opt/cni/bin/multus

updated the config file as well on all the nodes (This is the only .conf file present in the folder):-
root@Cluster-Manager:~# cat /etc/cni/net.d/10-calico.conf
{
  "name": "multus-cni-network",
  "type": "multus",
  "logFile": "/var/log/multus.log",
  "logLevel": "debug",
  "capabilities": {
    "portMappings": true
  },
  "delegates": [
    {
      "cniVersion": "0.3.1",
      "name": "default-cni-network",
      "plugins": [
        {
          "name": "k8s-pod-network",
          "cniVersion": "0.3.1",
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "mtu": 1500,
          "ipam": {
            "type": "calico-ipam"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
}

Also created the kubeconfig file as well for the same.

CRD was also created and with resource description as following :-

root@Cluster-Manager:~# kubectl describe net-attach-def macvlan-conf
Name:         macvlan-conf
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2020-04-24T12:15:23Z
  Generation:          2
  Managed Fields:
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:config:
    Manager:         kubectl
    Operation:       Update
    Time:            2020-04-24T13:14:40Z
  Resource Version:  1120904
  Self Link:         /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/macvlan-conf
  UID:               0941d2d6-3e07-4a18-8899-3751738aafd5
Spec:
  Config:  { "cniVersion": "0.3.0", "type": "macvlan", "master": "enp0s8", "mode": "bridge", "ipam": { "type": "host-local", "subnet": "102.168.1.0/24", "rangeStart": "102.168.1.200", "rangeEnd": "102.168.1.216", "routes": [ { "dst": "0.0.0.0/0" } ], "gateway": "102.168.1.1" } }
Events:    <none>

Deployed a Pod using the same and following is the output

root@Cluster-Manager:~# cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
EOF

root@Cluster-Manager:~# kubectl exec -it samplepod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if69: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether ca:38:a6:cc:32:16 brd ff:ff:ff:ff:ff:ff
    inet 200.168.3.155/32 scope global eth0
       valid_lft forever preferred_lft forever

No third interface from the macvlan was created.

On looking at the logs i observed the following 

Apr 24 19:56:20 Cluster-Manager kubelet[17882]: W0424 19:56:20.972744   17882 cni.go:202] Error validating CNI config list {"cniVersion":"","name":"multus-cni-network","plugins":[{"capabilities":{"portMappings":true},"delegates":[{"cniVersion":"0.3.1","name":"default-cni-network","plugins":[{"cniVersion":"0.3.1","datastore_type":"kubernetes","ipam":{"type":"calico-ipam"},"kubernetes":{"kubeconfig":"/etc/cni/net.d/calico-kubeconfig"},"log_level":"info","mtu":1500,"name":"k8s-pod-network","policy":{"type":"k8s"},"type":"calico"},{"capabilities":{"portMappings":true},"snat":true,"type":"portmap"}]}],"kubeconfig":"/etc/cni/net.d/multus.d/multus.kubeconfig","logFile":"/var/log/multus.log","logLevel":"debug","name":"multus-cni-network","type":"multus"}]}: [plugin multus does not support config version ""]
Apr 24 19:56:20 Cluster-Manager kubelet[17882]: W0424 19:56:20.972795   17882 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
Apr 24 19:56:25 Cluster-Manager kubelet[17882]: W0424 19:56:25.990696   17882 cni.go:202] Error validating CNI config list {"cniVersion":"","name":"multus-cni-network","plugins":[{"capabilities":{"portMappings":true},"delegates":[{"cniVersion":"0.3.1","name":"default-cni-network","plugins":[{"cniVersion":"0.3.1","datastore_type":"kubernetes","ipam":{"type":"calico-ipam"},"kubernetes":{"kubeconfig":"/etc/cni/net.d/calico-kubeconfig"},"log_level":"info","mtu":1500,"name":"k8s-pod-network","policy":{"type":"k8s"},"type":"calico"},{"capabilities":{"portMappings":true},"snat":true,"type":"portmap"}]}],"kubeconfig":"/etc/cni/net.d/multus.d/multus.kubeconfig","logFile":"/var/log/multus.log","logLevel":"debug","name":"multus-cni-network","type":"multus"}]}: [plugin multus does not support config version ""]
Apr 24 19:56:25 Cluster-Manager kubelet[17882]: W0424 19:56:25.990837   17882 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
Apr 24 19:56:31 Cluster-Manager kubelet[17882]: W0424 19:56:31.020989   17882 cni.go:202] Error validating CNI config list {"cniVersion":"","name":"multus-cni-network","plugins":[{"capabilities":{"portMappings":true},"delegates":[{"cniVersion":"0.3.1","name":"default-cni-network","plugins":[{"cniVersion":"0.3.1","datastore_type":"kubernetes","ipam":{"type":"calico-ipam"},"kubernetes":{"kubeconfig":"/etc/cni/net.d/calico-kubeconfig"},"log_level":"info","mtu":1500,"name":"k8s-pod-network","policy":{"type":"k8s"},"type":"calico"},{"capabilities":{"portMappings":true},"snat":true,"type":"portmap"}]}],"kubeconfig":"/etc/cni/net.d/multus.d/multus.kubeconfig","logFile":"/var/log/multus.log","logLevel":"debug","name":"multus-cni-network","type":"multus"}]}: [plugin multus does not support config version ""]
Apr 24 19:56:31 Cluster-Manager kubelet[17882]: W0424 19:56:31.023413   17882 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d

I am not sure where the configuration is wrong, since the following error is observed
-  plugin multus does not support config version ""

Would look forward to the pointers to fix and proceed further.

**Comment by dougbtv** [comment]
Do you experience the same problems when installing using the daemonset? Would be interested about the results for a comparison.

**Comment by dougbtv** [comment]
Also on the config version -- make sure that the "name" and "version" fields are filled in on the CNI configurations in NetworkAttachmentDefinitions

**Comment by nitinbedazzled** [comment]
@dougbtv.. i tried with the Flannel as the default network and daemon set and it worked. 
But when i tried the same with the hard way i still failed to get the interface with the macvlan. 

Following is the config file : 
 cat /etc/cni/net.d/00-multus.conf
{
  "name": "multus-cni-network",
  "type": "multus",
  "readinessindicatorfile": "/var/run/flannel/subnet.env",
  "delegates":
  [
    {
      "cniVersion": "0.2.0",
      "name": "cbr0",
      "plugins":
      [
        {
          "type": "flannel",
          "delegate":
          {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities":
          {
            "portMappings": true
          }
        }
      ]
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
}

Following is the NetworkAttaachmentDefinition Used
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  creationTimestamp: "2020-05-04T11:24:11Z"
  generation: 1
  managedFields:
  - apiVersion: k8s.cni.cncf.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:config: {}
    manager: kubectl
    operation: Update
    time: "2020-05-04T11:24:11Z"
  name: macvlan-conf
  namespace: default
  resourceVersion: "17429"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/macvlan-conf
  uid: 639d13b5-76e3-4b38-93d2-c24f6122bbd7
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "enps08", "mode":
    "bridge", "ipam": { "type": "host-local", "subnet": "192.168.1.0/24", "rangeStart":
    "192.168.1.200", "rangeEnd": "192.168.1.216", "routes": [ { "dst": "0.0.0.0/0"
    } ], "gateway": "192.168.1.1" } }'





Following are the logs from journalctl : 

May 05 19:00:02 multus-wn1-hw kubelet[5710]: W0505 19:00:02.684248    5710 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
May 05 19:00:07 multus-wn1-hw kubelet[5710]: W0505 19:00:07.700815    5710 cni.go:202] Error validating CNI config list {"cniVersion":"","name":"multus-cni-network","plugins":[{"delegates":[{"cniVersion":"0.2.0","name":"cbr0","plugins":[{"delegate":{"hairpinMode":true,"isDefaultGateway":true},"type":"flannel"},{"capabilities":{"portMappings":true},"type":"portmap"}]}],"kubeconfig":"/etc/cni/net.d/multus.d/multus.kubeconfig","name":"multus-cni-network","readinessindicatorfile":"/var/run/flannel/subnet.env","type":"multus"}]}: [plugin multus does not support config version ""]
May 05 19:00:07 multus-wn1-hw kubelet[5710]: W0505 19:00:07.701926    5710 cni.go:171] Error loading CNI config list file /etc/cni/net.d/10-flannel.conflist: error parsing configuration list: invalid character '"' after object key:value pair
May 05 19:00:07 multus-wn1-hw kubelet[5710]: W0505 19:00:07.702367    5710 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
