### ISSUE TITLE
Enhance Multus Lifecycle Management using Multus-Operator

### ISSUE THREAD

**Issue by sb1975** [k8snetworkplumbingwg/multus-cni#494]
Have we thought about the possibility of building a Multus-Operator to handle the Lifecycle Management of Multus itself please ?
It doesnt come by default as part of Kubernetes APIs and hence having a operator to handle this would be very useful.

**Comment by dougbtv** [comment]
This sounds very interesting! Would love to hear more about what lifecycle improvements and stories you'd like to hear. Let's keep the conversation rolling

Maybe related to #488
