### ISSUE TITLE
ipam dhcp issue: dhcp allocate timeout due when interface name is specified

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/multus-cni#495]
Happened when using bond-cni, where ifname is specified, but not named as `netX` 

```
Multus: [sriov-test-bonding/bond-pod]: error adding container to network "bond-net1": delegateAdd: error invoking DelegateAdd - "bond": error in getting result from AddNetwork: error calling DHCP.Allocate: error looking up "net3": Link not found
```

I also have a container networking plugins issue filed for a similar issue @ https://github.com/containernetworking/plugins/issues/470

But, what's interesting to me about this one is that it happens when the interface name is changed.

**Comment by aneeshkp** [comment]
This is DHCP plugin changes, the PR pending to be reviewed https://github.com/containernetworking/plugins/pull/501
