### ISSUE TITLE
Multus major release plan for 4.0

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/multus-cni#510]
Maintainers have decided that we'll work towards a 4.0 release.

Some of the items that we'll address in this release include:

- [x] Possible refactor /cmd /pkg directories
- [ ] Introduce error injection into unit testing (from fake kube client)
- [ ] Remove duplicated network-status / networks-status
- [ ] Remove https://github.com/intel/multus-cni/blob/master/types/types.go#L134
- [x] vender k8s package to 1.18.3 (or recent release), now using 1.13…
- [ ] update go.mod to change from `.v3` to `.v4`

Let's create a devel-4.0 branch to work on these items for.

Please comment with other items that are ready to be removed per deprecation plans, or other items that could be covered with a major release cut.

**Comment by s1061123** [comment]
https://github.com/intel/multus-cni/pull/511 takes care of vendor k8s package update.
