### ISSUE TITLE
Cannot Create Multiple Interface on Pod (K8S with Calico)

### ISSUE THREAD

**Issue by sarpkoksal** [k8snetworkplumbingwg/multus-cni#513]
Hi,

I am trying add an additional interface with Multus to my pod in K8S. I have K8S with version 1.12 and I am using Calico in K8S. I deployed Multus with the instrucstions in the following link: https://github.com/k8snetworkplumbingwg/reference-deployment/blob/master/multus-calico/multus-daemonset.yml (by the way Calico was already installed in my K8S before so I didnt installed Calico recently with these instructions)
After I deployed Multus, I tried to create and CNI and pod with the instructions in the following link: https://intel.github.io/multus-cni/doc/quickstart.html
However, I cannot see the additional interface that I created in the pod and also there is no any log in the multus daemon sets in order check status. Daemon set of Multus is running. What can be the problem? Do I need to set some extra configuration on  Calico or Kubelet because I didnt make any new configuration on Calico or Kubelet. I would be so happy if someone can help.

Kind regards,

Sarp

**Comment by mukesh-dua** [comment]
Sarp, what version of Calico are you using to test this functionality? In addition, can you share the Net-attach-def that you might have used here to attach secondary Calico interface?

**Comment by s1061123** [comment]
1) Could you please share the following information?

- multus version
- pod yaml
- net-attach-def yaml
- multus CNI config (might be in /etc/cni/net.d or somewhere, see your kubernetes configuration)

2) 1.12 is slightly old Kubernetes. Currently multus is following Kubernetes so we would likely to support most recent three  minor releases (1.18, 1.17, 1.16) of Kubernetes. Could you please update Kubernetes to latest and test it?

https://kubernetes.cn/docs/setup/release/version-skew-policy/
