### ISSUE TITLE
Namespace default network

### ISSUE THREAD

**Issue by MarcusNoble** [k8snetworkplumbingwg/multus-cni#516]
**What would you like to be added**:

I'd like to be able to specify the default network used by all pods within a namespace, but still overrideable with annotations.

**Why is this needed**:

When using AWS EKS we switch the default AWS CNI for Weave Net so we don't run out of IP in our subnet (due to AWS CNI attaching secondary IPs to the instance). The problem with this is the control plane still runs on the AWS CNI network and is out of our control so connectivity to any mutation/validation webhooks will fail as the control plane cannot rout to pods in the Weave network. Generally speaking I'd like to be able to run all pods in kube-system with the AWS CNI as their default network (possibly other namespaces too) without having to annotate all pods deployed into it.

**Comment by s1061123** [comment]
how about to use "defaultNetworks" configuration ?

https://github.com/intel/multus-cni/blob/master/doc/configuration.md

**Comment by MarcusNoble** [comment]
I did look at that but I'm not sure that solves what I'm trying to do (or i'm not understanding it correctly).

I have the following conf:

```json
{
  "cniVersion": "0.3.1",
  "name": "multus-cni-network",
  "type": "multus",
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "confDir": "/etc/cni/net.d",
  "logFile": "/var/log/multus.log",
  "logLevel": "debug",
  "capabilities": {
    "portMappings": true
  },
  "clusterNetwork": "aws-cni",
  "defaultNetworks": ["weave-net"],
  "systemNamespaces": ["kube-system"],
  "multusNamespace": "kube-system"
}
```

But this applies `aws-cni` to all pods and `weave-net` to those pods not in `kube-system`. What I really want to be able to do is used `aws-cni` for all pods in `kube-system` and use `weave-net` for all other pods (not use both CNI).

Is this possible?

**Comment by s1061123** [comment]
one q. which namespace `aws-cni` and `weave-net` are in?

**Comment by MarcusNoble** [comment]
`kube-system`

**Comment by s1061123** [comment]
So I believe you'd like to change 'eth0', correct?

I don't know it works in your use-case, but now we have such annotation.

https://github.com/intel/multus-cni/blob/master/doc/configuration.md#specify-default-cluster-network-in-pod-annotations

**Comment by MarcusNoble** [comment]
Oh! I hadn't spotted that. Yeah, I can use that as a workaround but it still needs adding to each pod. I think what I'd like to see if the ability to also annotate namespaces and have that taken into consideration when setting the networks. Does that sound like something worth adding?

**Comment by MarcusNoble** [comment]
Here's a very quick and dirty approach to what I'm suggesting: https://github.com/intel/multus-cni/pull/523
If this is something the project will benefit from I'd be happy to work on the PR some more to clean it up.

**Comment by s1061123** [comment]
Are you going to propose new annotations? If so, I strongly recommend to discuss about it in NPWG, Networking Plumbing Working Group in Kubernetes.

https://github.com/k8snetworkplumbingwg/community

**Comment by MarcusNoble** [comment]
I had planned to use the same annotations as used on pods but happy to take it to the WG if needed. :)

**Comment by s1061123** [comment]
Now multus is following following spec. Just FYI.
https://github.com/k8snetworkplumbingwg/multi-net-spec

**Comment by MarcusNoble** [comment]
Doesn't look like there's any mention of overriding the default network like this: https://github.com/intel/multus-cni/blob/master/doc/configuration.md?rgh-link-date=2020-06-11T07%3A49%3A22Z#specify-default-cluster-network-in-pod-annotations

Does that mean `v1.multus-cni.io/default-network` is likely to be dropped or proposed as part of the spec?

**Comment by s1061123** [comment]
`v1.multus-cni.io/default-network` is only implemented for multus before spec is published, but other features are in spec because multus is official reference plugin for the spec.

**Comment by adrianchiris** [comment]
> Oh! I hadn't spotted that. Yeah, I can use that as a workaround but it still needs adding to each pod. 
could you use a pod admission controller to inject the `default-network` per a pre-configured namespace <-> net-attach-def CR mapping ?

**Comment by mukesh-dua** [comment]
@Marcus, I think this will be a really nice to have feature. I believe you are trying some sort of namespace level isolation. A word of caution - you would still need the primary interface (w/ default network interface) in your pods created in new namespaces to communicate with kube-dns and stuff. Though, depending on the secondary interface/CNI used here, you might be able to solve this problem by making the intercommunication through at fabric layer.

**Comment by shinebayar-g** [comment]
> **Why is this needed**:
> 
> When using AWS EKS we switch the default AWS CNI for Weave Net so we don't run out of IP in our subnet (due to AWS CNI attaching secondary IPs to the instance). The problem with this is the control plane still runs on the AWS CNI network and is out of our control so connectivity to any mutation/validation webhooks will fail as the control plane cannot rout to pods in the Weave network. 

@MarcusNoble We're on EKS and we faced similar problem with VPC CNI. Are you still using Multus? How does your setup looks like?

**Comment by MarcusNoble** [comment]
No, we gave up on Multus and are just using the aws-cni with a secondary IP rage associated.
