### ISSUE TITLE
Multus on RKE

### ISSUE THREAD

**Issue by mkl262** [k8snetworkplumbingwg/multus-cni#539]
I installed Multus on a cluster created using RKE and configured it with the flannel CNI.
I used the default network CIDR in RKE which configures the DNS server IP as 10.43.0.10 and the cluster network as 10.42.0.0/16. Because they are in different CIDRs, when I add a macvlan interface to a pod with a default route, multus only routes 10.42.0.0/16 via eth0, so the pod cant access the DNS server IP.
Is there a way to add a route to eth0 to the 10.43.0.10 IP ?

**Comment by dougbtv** [comment]
I think that you can use the route override CNI for just this!

https://github.com/redhat-nfvpe/cni-route-override
