### ISSUE TITLE
If multus cannot see template - it fails

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/multus-cni#543]
Not sure if this is a bug but I figured I would raise it just in case.

**What happend**:
Adding a new node to an existing cluster with kubeadm caused multus to fail with the follow log message:
WARN: {Location /host/etc/cni/net.d/templates/00-multus.conf does not exist}  

**What you expected to happen**:
If multus does not find this template, i expected it to create it.

**How to reproduce it (as minimally and precisely as possible)**:
kubeadm join ....
Check multus logs and you should see the warning message and multus daemonset failure.

**Anything else we need to know?**:

**Environment**:
Ubuntu 16.04

- Multus version 
v3.3 - docker-pullable://nfvpe/multus@sha256:4701349ffa451e30c054a41cde132e85765977c88260f146c67a8023a312960a
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Primary CNI for Kubernetes cluster:
flannel:v0.12.0-amd64
docker-pullable://quay.io/coreos/flannel@sha256:6d451d92c921f14bfb38196aacb6e506d4593c5b3c9d40a8b8a2506010dc3e10
- OS (e.g. from /etc/os-release):
Ubuntu 16.04
- File of '/etc/cni/net.d/'
Nothing multus related here
- File of '/etc/cni/multus/net.d'
Nothing multus related here
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
NA
- Other log outputs (if you use multus logging)
WARN: {Location /host/etc/cni/net.d/templates/00-multus.conf does not exist}

**Comment by dougbtv** [comment]
Thanks a bunch for the report -- this is definitely a valid issue.

As a work-around, I'd suggest that you copy the 00-multus.conf from an existing node.

However, we probably need some documentation, or a workflow to enable this cluster lifecycle event. The quickstart-style installation is reallly... just a quick-start it doesn't really account for cluster lifecycle events such as adding a node.

That being said, this is something we should consider in the future.
