### ISSUE TITLE
failed to "KillPodSandbox"delegateDel: error invoking ConflistDel - \"k8s-pod-network\": conflistDel: error converting the raw bytes into a conflist: error parsing configuration list: no 'plugins' key"

### ISSUE THREAD

**Issue by wavezhang** [k8snetworkplumbingwg/multus-cni#570]
**What happend**:

I Specify default cluster network in Pod annotations following guide here  https://github.com/intel/multus-cni/blob/master/doc/configuration.md#specify-default-cluster-network-in-pod-annotations

When I delete pod, there are errors like following:

```
error killing pod: failed to "KillPodSandbox" for "xxxxx" with KillPodSandboxError: "rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"xxxxxx\" network: delegateDel: error invoking ConflistDel - \"k8s-pod-network\": conflistDel: error converting the raw bytes into a conflist: error parsing configuration list: no 'plugins' key"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Multus version 
3.4.1
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
1.17.9
- Primary CNI for Kubernetes cluster:
calico
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by dougbtv** [comment]
Can you provide the NetworkAttachmentDefinition that you used? And if possible enable logging and include the logs? Thanks!

Logging info here @ https://github.com/intel/multus-cni/blob/master/doc/configuration.md#logging

Also, if you don't mind include the contents of `/etc/cni/net.d/00-multus.conf`. 

I looks like some configuration, somewhere, isn't parsing correctly. 

Thanks!

**Comment by thuyettv1** [comment]
I have the same problem. If i specify sriov is default network, error appear when delete pod. If i use flannel as default network, error dont appear.

**Comment by chestack** [comment]
this is because that delegates configured in 00-multus.conf but `v1.multus-cni.io/default-network` is used in pod annotation.

```
		// check plugins field and enable ConfListPlugin if there is
		for _, v := range in.Delegates {
			if len(v.ConfList.Plugins) != 0 {
				v.ConfListPlugin = true
			}
		}
```

two workarounds:
1. use "clusterNetwork" instead of delegates in 00-multus.conf, something like
`{
    "cniVersion": "0.3.1",
    "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
    "logFile": "/var/log/multus.log",
    "logLevel": "debug",
    "name": "multus-cni-network",
    "type": "multus",
    "confDir": "/etc/cni/net.d",
    "multusNamespace": "secure-container",
    "clusterNetwork": "flannel"
}`

2. update your net-attach-def CR to use plugins, something like
`apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: kuryr-test
  namespace: secure-container
spec:
  config: '{
"cniVersion": "0.3.1",
"name": "kuryr",
"debug":true,
"plugins":[
  {"type": "kuryr-cni"}
]
}'`
