### ISSUE TITLE
pod not able to resolve other services in the cluster if multus interface in the pod is made as default. 

### ISSUE THREAD

**Issue by vbalaganes** [k8snetworkplumbingwg/multus-cni#584]
Hi , 

I brought up a pod with calico ip in eth0 & multus ip in eth1.
Calico IP is assigned to eth0 interface by K8s by default. [No annotations]
Multus IP is assigned to eth1 through annotation.
I made the Multus Interface (eth1) as default interface for the pod by providing 'default-route' in annotation as below.

      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name" : "multusnw",
              "interface": "eth1",
              "default-route": ["10.96.17.1"] }
        ]'

After this Iam not able to resolve other service fqdns available in the cluster through eth1.
Do I need to update any other ? 
In etc/resolv.conf file of the pod & in the node , i can see only K8s service network (internal network) not the multus network.
Since Multus Network is not in the list how to proceed for service discovery

**Comment by thien-enouvo** [comment]
I got the same issue.

**Comment by dougbtv** [comment]
Can you show us a `ip route` in the pod? I think that you might also have to add static routes, possibly.

Using static: https://github.com/containernetworking/plugins/tree/master/plugins/ipam/static

Or route-override:  https://github.com/containernetworking/plugins/tree/master/plugins/ipam/static
