### ISSUE TITLE
Pods across nodes are not communicating-GCP (GKE and Openshift)

### ISSUE THREAD

**Issue by Ieneya** [k8snetworkplumbingwg/multus-cni#599]
Hi,
Two things I tried for creating a cluster  , in both the problem exists.

First method:
I created a cluster using GKE , deployed Multus and pods got multiple networks. For network attachment i tried macvlan , and used whereabouts ipam to avoid IP conflicts. 
As a result , the pod's got net1 interface with unique mac address and with no IP conflicts.If the pods are in same node, ping worked . But across nodes communication not happened.

In doubtful,may be macvlan filters the traffic , So I tried IPvlan too , and pods got same mac address for net1 interface , but the same problem exists.

How could I check further and resolve it?

Second method:
I used openshift container platform on top of GCP , and deployed pods with attached network of macvlan , And I tried IPvlan also.But the same problem as before , if the pods are in different nodes , communication not happened via ping.

How to resolve this?

Many Thanks.

**Comment by dougbtv** [comment]
macvlan on a public cloud may result in traffic that's filtered by the provider.

@s1061123 recommends that you may want to try the ipvlan, as mac filtering may be implemented by GCE/GKE.

**Comment by dougbtv** [comment]
Could you open a ticket with Google and see if they have any further information? If you find anything out, it'd be really helpful for the community.

**Comment by s1061123** [comment]
I suppose that GCP's (virtual?) switch between nodes do some process to filtering 'unnecessary packet', which is not VM's IP/MAC'. and that might be the reason.

We are not good at GCP so could you ask to Google?

**Comment by dougbtv** [comment]
If you have any more information, please feel free to reopen the issue! Thank you.
