### ISSUE TITLE
Run Multus with Contrail alternative Flannel

### ISSUE THREAD

**Issue by thanhlong9x** [k8snetworkplumbingwg/multus-cni#601]
Hi, I have a problem about integrating Tungsten with Multus. I see the issue mentioned here https://review.opencontrail.org/c/Juniper/contrail-controller/+/58387. But could not find any instructions to do it. Looking forward to help with this issue. Thank you everyone.

**Comment by s1061123** [comment]
From multus-cni side, we don't have any specific process for integration with Contrail, however, Contrail side must have something as looked above url.

How about to ask Contrail community about it? Let me close this issue.
If you have any more information, please feel free to reopen the issue! Thank you.
