### ISSUE TITLE
Network Attachment Definition with multiple Host Devices

### ISSUE THREAD

**Issue by adpempx** [k8snetworkplumbingwg/multus-cni#637]
Hi,

I am trying to create a network Attachment definition and I'd like to configure 2 host devices inside the same configuration, like:

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: host-devices
  annotations:
    k8s.v1.cni.cncf.io/resourceName: host-devices
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "host-device",
          "pciBusID": "0000:06:00.0"
        },
        {
          "type": "host-device",
          "pciBusID": "0000:09:00.0"
        }
      ]
    }

But it does not work, I see just 1 network interface inside container namespace.
I think "plugins" is not the right way.

Could you please help me?
Thanks

**Comment by dougbtv** [comment]
I think you're right on with your analysis -- not to use a conflist but, you need two net-attach-defs in this case,

so annotate your pod with:

```
  annotations:
    k8s.v1.cni.cncf.io/networks: host-devices-a,host-devices-b
```

And then have two net-attach-defs like so:

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
name: host-devices-a
annotations:
k8s.v1.cni.cncf.io/resourceName: host-devices
spec:
config: |
{
"cniVersion": "0.3.0",
"type": "host-device",
"pciBusID": "0000:06:00.0"
}
```


```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
name: host-devices-b
annotations:
k8s.v1.cni.cncf.io/resourceName: host-devices
spec:
config: |
{
"cniVersion": "0.3.0",
"type": "host-device",
"pciBusID": "0000:09:00.0"
}
```
