### ISSUE TITLE
Get same ip of `net1` for pods on different nodes.

### ISSUE THREAD

**Issue by Panlichen** [k8snetworkplumbingwg/multus-cni#640]
**What happened**:

I use kubeadm to create a k8s cluster with two nodes, then I deploy multus daemonset, a macvlan crd, and 2 pods on each node. What's wierd is that the have the same IP for `net1`.

The two nodes are from [CloudLab](https://www.cloudlab.us), each withTwo Dual-port Mellanox ConnectX-4 25 GB NIC (PCIe v3.0, 8 lanes). Before installing k8s, ifconfig output on both nodes are similar:

```shell
$ ifconfig -a
eno49: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 128.110.154.232  netmask 255.255.252.0  broadcast 128.110.155.255
        inet6 fe80::9af2:b3ff:fecc:32d0  prefixlen 64  scopeid 0x20<link>
        ether 98:f2:b3:cc:32:d0  txqueuelen 1000  (Ethernet)
        RX packets 768735  bytes 259326590 (259.3 MB)
        RX errors 0  dropped 10  overruns 0  frame 0
        TX packets 66335  bytes 11248516 (11.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno50: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::9af2:b3ff:fecc:32d1  prefixlen 64  scopeid 0x20<link>
        ether 98:f2:b3:cc:32:d1  txqueuelen 1000  (Ethernet)
        RX packets 31436  bytes 16288046 (16.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24557  bytes 3466178 (3.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
ens1f0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 9c:dc:71:49:a8:50  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens1f1: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 9c:dc:71:49:a8:51  txqueuelen 1000  (Ethernet)
        RX packets 9  bytes 540 (540.0 B)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 18  bytes 2781 (2.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

After install k8s and multus daemonset, the crd I use to create macvlan is

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno50",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.56.217.0/24",
        "rangeStart": "10.56.217.171",
        "rangeEnd": "10.56.217.181",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.56.217.1"
      }
    }'

```

I create two pods with:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
  nodeName: node-0

---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
  nodeName: node-1
```

With a simple script, those two pods has the same IP: (detail pod yaml can be seen below)

```yaml
$ /users/Poanpan/mydata/cascade-docker/scripts/get-pod-net1-ip.sh
samplepod "node-0"
net1      Link encap:Ethernet  HWaddr 5A:AB:23:6C:2E:BD  
          inet addr:10.56.217.171  Bcast:10.56.217.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:42 (42.0 B)

samplepod1 "node-1"
net1      Link encap:Ethernet  HWaddr 2E:01:15:69:15:94  
          inet addr:10.56.217.171  Bcast:10.56.217.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:60 (60.0 B)  TX bytes:42 (42.0 B)
```

I don't know why, is it about the `master` parameter in crd yaml? 

Here is the kubeadm command I use:

```shell
sudo kubeadm init --apiserver-advertise-address=192.168.1.1 --pod-network-cidr=10.244.0.0/16 --node-name node-0 
```

I have to use the "internal network" for my experment due to the CloudLab [policy](https://gitlab.flux.utah.edu/emulab/emulab-devel/-/wikis/faq/Using%20the%20Testbed/Control%20Network), so I set the `master` parameter to `eno50`.

**What you expected to happen**:

I want those two pods has different IPs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use kubeadm to create cluster. (init and join)
2. Install flannel as basical CNI.
3. Install mulutus daemonset.
4. Create macvlan crd.
5. Create my pods.

**Anything else we need to know?**:

The hostname and /etc/hosts on the machine, maybe this helps:

```shell
$ hostname
node-0.2nodes-l1link.cascade-pg0.utah.cloudlab.us

$ cat /etc/hosts
127.0.0.1       localhost loghost localhost.2nodes-l1link.cascade-pg0.utah.cloudlab.us
192.168.1.2     node-1-l1link node-1-0 node-1
192.168.1.1     node-0-l1link node-0-0 node-0
```

I also have a similar [issue](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/338) in sriov-network-device-plugin.

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
  
  - stable
  
- Kubernetes version (use `kubectl version`):

  - v1.20.5

- Primary CNI for Kubernetes cluster:

  - flannel

- OS (e.g. from /etc/os-release):

  - ```shell
    $ cat /etc/os-release
    NAME="Ubuntu"
    VERSION="18.04.1 LTS (Bionic Beaver)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 18.04.1 LTS"
    VERSION_ID="18.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=bionic
    UBUNTU_CODENAME=bionic
    ```

- File of '/etc/cni/net.d/'

  - ```shell
    $ ls /etc/cni/net.d/
    00-multus.conf  10-flannel.conflist  multus.d
    ```

- File of '/etc/cni/multus/net.d'

  - no such directory

  - but

    ```shell
    $ ls /etc/cni/net.d/multus.d
    multus.kubeconfig
    ```

    

- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)

  - ```shell
    $ kubectl get net-attach-def -o yaml
    apiVersion: v1
    items:
    - apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"macvlan-conf","namespace":"default"},"spec":{"config":"{ \"cniVersion\": \"0.3.0\", \"type\": \"macvlan\", \"master\": \"eno50\", \"mode\": \"bridge\", \"ipam\": { \"type\": \"host-local\", \"subnet\": \"10.56.217.0/24\", \"rangeStart\": \"10.56.217.171\", \"rangeEnd\": \"10.56.217.181\", \"routes\": [ { \"dst\": \"0.0.0.0/0\" } ], \"gateway\": \"10.56.217.1\" } }"}}
        creationTimestamp: "2021-03-28T12:09:21Z"
        generation: 1
        managedFields:
        - apiVersion: k8s.cni.cncf.io/v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:spec:
              .: {}
              f:config: {}
          manager: kubectl-client-side-apply
          operation: Update
          time: "2021-03-28T12:09:21Z"
        name: macvlan-conf
        namespace: default
        resourceVersion: "1209"
        uid: eb614add-7346-4f9c-bb6a-7f10a88fbb3d
      spec:
        config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eno50", "mode":
          "bridge", "ipam": { "type": "host-local", "subnet": "10.56.217.0/24", "rangeStart":
          "10.56.217.171", "rangeEnd": "10.56.217.181", "routes": [ { "dst": "0.0.0.0/0"
          } ], "gateway": "10.56.217.1" } }'
    kind: List
    metadata:
      resourceVersion: ""
      selfLink: ""
    ```

  - 

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)

  - ```shell
    $ kubectl get pod samplepod -o yaml
    apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/network-status: |-
          [{
              "name": "",
              "interface": "eth0",
              "ips": [
                  "10.244.0.2"
              ],
              "mac": "e2:21:dd:85:d1:82",
              "default": true,
              "dns": {}
          },{
              "name": "default/macvlan-conf",
              "interface": "net1",
              "ips": [
                  "10.56.217.171"
              ],
              "mac": "5a:ab:23:6c:2e:bd",
              "dns": {}
          }]
        k8s.v1.cni.cncf.io/networks: macvlan-conf
        k8s.v1.cni.cncf.io/networks-status: |-
          [{
              "name": "",
              "interface": "eth0",
              "ips": [
                  "10.244.0.2"
              ],
              "mac": "e2:21:dd:85:d1:82",
              "default": true,
              "dns": {}
          },{
              "name": "default/macvlan-conf",
              "interface": "net1",
              "ips": [
                  "10.56.217.171"
              ],
              "mac": "5a:ab:23:6c:2e:bd",
              "dns": {}
          }]
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"macvlan-conf"},"name":"samplepod","namespace":"default"},"spec":{"containers":[{"command":["/bin/ash","-c","trap : TERM INT; sleep infinity \u0026 wait"],"image":"alpine","name":"samplepod"}],"nodeName":"node-0"}}
      creationTimestamp: "2021-03-28T12:09:40Z"
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:metadata:
            f:annotations:
              .: {}
              f:k8s.v1.cni.cncf.io/networks: {}
              f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:spec:
            f:containers:
              k:{"name":"samplepod"}:
                .: {}
                f:command: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:enableServiceLinks: {}
            f:nodeName: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
        manager: kubectl-client-side-apply
        operation: Update
        time: "2021-03-28T12:09:40Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:metadata:
            f:annotations:
              f:k8s.v1.cni.cncf.io/network-status: {}
              f:k8s.v1.cni.cncf.io/networks-status: {}
        manager: multus
        operation: Update
        time: "2021-03-28T12:09:42Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:status:
            f:conditions:
              .: {}
              k:{"type":"ContainersReady"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
              k:{"type":"Initialized"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
              k:{"type":"PodScheduled"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
              k:{"type":"Ready"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
            f:containerStatuses: {}
            f:hostIP: {}
            f:phase: {}
            f:podIP: {}
            f:podIPs:
              .: {}
              k:{"ip":"10.244.0.2"}:
                .: {}
                f:ip: {}
            f:startTime: {}
        manager: kubelet
        operation: Update
        time: "2021-03-28T12:09:44Z"
      name: samplepod
      namespace: default
      resourceVersion: "1257"
      uid: a49103b9-10f6-4043-994b-5018c5829265
    spec:
      containers:
      - command:
        - /bin/ash
        - -c
        - 'trap : TERM INT; sleep infinity & wait'
        image: alpine
        imagePullPolicy: Always
        name: samplepod
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-xspwh
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: node-0
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      volumes:
      - name: default-token-xspwh
        secret:
          defaultMode: 420
          secretName: default-token-xspwh
    status:
      conditions:
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:40Z"
        status: "True"
        type: Initialized
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:43Z"
        status: "True"
        type: Ready
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:43Z"
        status: "True"
        type: ContainersReady
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:40Z"
        status: "True"
        type: PodScheduled
      containerStatuses:
      - containerID: docker://9391de2e92095359b0ebc4792983d49f4d7d380d36ce77bd93a78e20a39160ef
        image: alpine:latest
        imageID: docker-pullable://alpine@sha256:826f70e0ac33e99a72cf20fb0571245a8fee52d68cb26d8bc58e53bfa65dcdfa
        lastState: {}
        name: samplepod
        ready: true
        restartCount: 0
        started: true
        state:
          running:
            startedAt: "2021-03-28T12:09:43Z"
      hostIP: 192.168.1.1
      phase: Running
      podIP: 10.244.0.2
      podIPs:
      - ip: 10.244.0.2
      qosClass: BestEffort
      startTime: "2021-03-28T12:09:40Z
    ```

  - ```shell
    $ kubectl get pod samplepod1 -o yaml
    apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/network-status: |-
          [{
              "name": "",
              "interface": "eth0",
              "ips": [
                  "10.244.1.4"
              ],
              "mac": "f6:62:84:b0:e1:85",
              "default": true,
              "dns": {}
          },{
              "name": "default/macvlan-conf",
              "interface": "net1",
              "ips": [
                  "10.56.217.171"
              ],
              "mac": "2e:01:15:69:15:94",
              "dns": {}
          }]
        k8s.v1.cni.cncf.io/networks: macvlan-conf
        k8s.v1.cni.cncf.io/networks-status: |-
          [{
              "name": "",
              "interface": "eth0",
              "ips": [
                  "10.244.1.4"
              ],
              "mac": "f6:62:84:b0:e1:85",
              "default": true,
              "dns": {}
          },{
              "name": "default/macvlan-conf",
              "interface": "net1",
              "ips": [
                  "10.56.217.171"
              ],
              "mac": "2e:01:15:69:15:94",
              "dns": {}
          }]
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"macvlan-conf"},"name":"samplepod1","namespace":"default"},"spec":{"containers":[{"command":["/bin/ash","-c","trap : TERM INT; sleep infinity \u0026 wait"],"image":"alpine","name":"samplepod"}],"nodeName":"node-1"}}
      creationTimestamp: "2021-03-28T12:09:40Z"
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:metadata:
            f:annotations:
              .: {}
              f:k8s.v1.cni.cncf.io/networks: {}
              f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:spec:
            f:containers:
              k:{"name":"samplepod"}:
                .: {}
                f:command: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:enableServiceLinks: {}
            f:nodeName: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
        manager: kubectl-client-side-apply
        operation: Update
        time: "2021-03-28T12:09:40Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:metadata:
            f:annotations:
              f:k8s.v1.cni.cncf.io/network-status: {}
              f:k8s.v1.cni.cncf.io/networks-status: {}
        manager: multus
        operation: Update
        time: "2021-03-28T12:09:42Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:status:
            f:conditions:
              .: {}
              k:{"type":"ContainersReady"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
              k:{"type":"Initialized"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
              k:{"type":"PodScheduled"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
              k:{"type":"Ready"}:
                .: {}
                f:lastProbeTime: {}
                f:lastTransitionTime: {}
                f:status: {}
                f:type: {}
            f:containerStatuses: {}
            f:hostIP: {}
            f:phase: {}
            f:podIP: {}
            f:podIPs:
              .: {}
              k:{"ip":"10.244.1.4"}:
                .: {}
                f:ip: {}
            f:startTime: {}
        manager: kubelet
        operation: Update
        time: "2021-03-28T12:09:44Z"
      name: samplepod1
      namespace: default
      resourceVersion: "1260"
      uid: 9e83f92a-0d02-434d-9be9-1b1f49d47f99
    spec:
      containers:
      - command:
        - /bin/ash
        - -c
        - 'trap : TERM INT; sleep infinity & wait'
        image: alpine
        imagePullPolicy: Always
        name: samplepod
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-xspwh
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: node-1
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      volumes:
      - name: default-token-xspwh
        secret:
          defaultMode: 420
          secretName: default-token-xspwh
    status:
      conditions:
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:40Z"
        status: "True"
        type: Initialized
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:44Z"
        status: "True"
        type: Ready
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:44Z"
        status: "True"
        type: ContainersReady
      - lastProbeTime: null
        lastTransitionTime: "2021-03-28T12:09:40Z"
        status: "True"
        type: PodScheduled
      containerStatuses:
      - containerID: docker://816b34d898816684bb12138cfdf8da3ef4c7e6c01748aaa7a0a5a98f9c79cb27
        image: alpine:latest
        imageID: docker-pullable://alpine@sha256:826f70e0ac33e99a72cf20fb0571245a8fee52d68cb26d8bc58e53bfa65dcdfa
        lastState: {}
        name: samplepod
        ready: true
        restartCount: 0
        started: true
        state:
          running:
            startedAt: "2021-03-28T12:09:43Z"
      hostIP: 192.168.1.2
      phase: Running
      podIP: 10.244.1.4
      podIPs:
      - ip: 10.244.1.4
      qosClass: BestEffort
      startTime: "2021-03-28T12:09:40Z"
    ```

- Other log outputs (if you use multus logging)

**Comment by arikachen** [comment]
should use whereabouts ipam.

**Comment by Panlichen** [comment]
Thanks a lot! I believe you are talking about this, I'll check it.

**Comment by s1061123** [comment]
@Panlichen in your above case, you use host-local IPAM plugin to allocate IP. host-local is just 'host' local, not 'cluster local'. So if two pods are allocated in different nodes for each other, then same IP address may be allocated to the pod because 'host-local' IPAM does not recognize other nodes IP address allocation.

So if you still use host-local, it may be happen again but it is not an issue. Please use other IPAM plugin which supports cluster-wide IP address allocation such as whereabouts.
