### ISSUE TITLE
Trying to create NetworkAttachmentDefinition in every work node.

### ISSUE THREAD

**Issue by kinglory** [k8snetworkplumbingwg/multus-cni#652]
Hi,
I am trying to deploy containers in a cluster which contains 2 nodes. But it seems that all my NetworkAttachmentDefinitions are only created in master node.  If my container is deployed to work node, it will be in the state ContainerCreating because the work node cannot get resource "network-attachment-definitions". How could I make every node join the cluster can deploy the  NetworkAttachmentDefinitions? Here is my yaml. Thank you.

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: userspace-vpp-net-1
  namespace: kube-system
spec:
  config: '{
        "cniVersion": "0.3.1",
        "type": "userspace",
        "name": "userspace-vpp-net-1",
        "kubeconfig": "/etc/kubernetes/admin.conf",
        "logFile": "/var/log/userspace-vpp-net-1-cni.log",
        "logLevel": "debug",
        "host": {
                "engine": "vpp",
                "iftype": "memif",
                "netType": "interface",
                "memif": {
                        "role": "master",
                        "mode": "ethernet"
                }
        },
        "container": {
                "engine": "vpp",
                "iftype": "memif",
                "netType": "interface",
                "memif": {
                        "role": "slave",
                        "mode": "ethernet"
                }
        },
        "ipam": {
                "type": "host-local",
                "subnet": "10.244.0.0/24",
                "rangeStart": "10.244.0.2",
                "rangeEnd": "10.244.0.254",
                "routes": [
                        {
                                "dst": "0.0.0.0/0"
                        }
                ],
                "gateway": "10.244.0.1"
        }
    }'


```

**Comment by dougbtv** [comment]
Hey @kinglory -- when you do a `kubectl create -f my-net-attach-def.yml` this create it in the api server -- therefore it's available on every node.

can you do a `kubectl get net-attach-def -A` and you can see that it's there? thanks!

*note*: on the ipam side host-local is it's own beast, and works only local to a single node. also checkout whereabouts for cluster-wide ipam: https://github.com/k8snetworkplumbingwg/whereabouts

**Comment by kinglory** [comment]
Thanks for your reply. My problem has been solved. The work nodes cannot get the network-definition information due to the authority problem. When I change the kubeconfig file in the network yaml, it worked properly. Thank you very much.
