### ISSUE TITLE
network name is empty under network-status annotation

### ISSUE THREAD

**Issue by amshankaran** [k8snetworkplumbingwg/multus-cni#656]
What happened:

Calico is configured as primary CNI. Multus uses this as delegate. Created a pod (via deployment). while describing the pod, under "networks-status:" annotation, network name is empty string "name": ""
master-0-ejlcluster> kubectl describe pod nginx-shr-6584fcbb55-lpndj
Name: nginx-shr-6584fcbb55-lpndj
Namespace: default
Priority: 0
Node: worker-pool1-w7m9sczq-ejlcluster/10.0.10.97
Start Time: Sat, 17 Apr 2021 09:30:08 +0000
Labels: app=nginx-shr
pod-template-hash=6584fcbb55
Annotations: k8s.v1.cni.cncf.io/network-status:
[{
"name": "",
"ips": [
"192.168.185.80"
],
"default": true,
"dns": {}
}]
k8s.v1.cni.cncf.io/networks-status:
[{
"name": "",
"ips": [
"192.168.185.80"
],
"default": true,
"dns": {}
}]

What you expected to happen:

under "networks-status:" annotation "name": "k8s-pod-network" is expected.

director-0> kubectl describe pod nginx-shr-6584fcbb55-5gqnf
Name: nginx-shr-6584fcbb55-5gqnf
Namespace: default
Priority: 0
Node: worker-p1-ywj6c6j5/10.0.10.17
Start Time: Fri, 16 Apr 2021 11:01:42 +0000
Labels: app=nginx-shr
pod-template-hash=6584fcbb55
Annotations: k8s.v1.cni.cncf.io/network-status:
[{
"name": "k8s-pod-network",
"ips": [
"192.168.248.74"
],
"default": true,
"dns": {}
}]
k8s.v1.cni.cncf.io/networks-status:
[{
"name": "k8s-pod-network",
"ips": [
"192.168.248.74"
],
"default": true,
"dns": {}
}]

How to reproduce it (as minimally and precisely as possible):
just deploy a nginx pod in latest kubernets cluster
kubectl create deployment nginx-shr --image=nginx

Anything else we need to know?:

master-0-ejlcluster> sudo vim 00-multus.conf

{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.0", "plugins": [ { "type": "calico", "log_level": "info", "etcd_endpoints": "https://10.0.10.163:2379", "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key", "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert", "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca", "mtu": 2070, "ipam": { "type": "calico-ipam", "assign_ipv4": "true", "assign_ipv6": "false" }, "container_settings": { "allow_ip_forwarding": true }, "policy": { "type": "k8s", "k8s_api_root": "https://[10.96.0.1]:443", "k8s_auth_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImhSRzZ..." }, "kubernetes": { "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} } ] } ] }

master-0-ejlcluster> kubectl edit configmap calico-config -n kube-system

apiVersion: v1
data:
calico_backend: bird
cni_network_config: |-
{
"name": "k8s-pod-network",
"cniVersion": "0.3.0",
"plugins": [
{
"type": "calico",
"log_level": "info",
"etcd_endpoints": "ETCD_ENDPOINTS",
"etcd_key_file": "ETCD_KEY_FILE",
"etcd_cert_file": "ETCD_CERT_FILE",
"etcd_ca_cert_file": "ETCD_CA_CERT_FILE",
"mtu": 2070,
"ipam": {
"type": "calico-ipam",
"assign_ipv4": "true",
"assign_ipv6": "false"
},
"container_settings": {
"allow_ip_forwarding": true
},
"policy": {
"type": "k8s",
"k8s_api_root": "https://[KUBERNETES_SERVICE_HOST]:KUBERNETES_SERVICE_PORT",
"k8s_auth_token": "SERVICEACCOUNT_TOKEN"
},
"kubernetes": {
"kubeconfig": "KUBECONFIG_FILEPATH"
}
},
{
"type": "portmap",
"snat": true,
"capabilities": {"portMappings": true}
}
]
}
etcd_ca: /calico-secrets/etcd-ca
etcd_cert: /calico-secrets/etcd-cert
etcd_endpoints: https://10.0.10.163:2379
etcd_key: /calico-secrets/etcd-key
kind: ConfigMap
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"v1","data":{"calico_backend":"bird","cni_network_config":"{\n "name": "k8s-pod-network",\n "cniVersion": "0.3.0",\n "plugins": [\n {\n "type": "calico",\n "log_level": "info",\n "etcd_endpoints": "ETCD_ENDPOINTS",\n "etcd_key_file": "ETCD_KEY_FILE",\n "etcd_cert_file": "ETCD_CERT_FILE",\n "etcd_ca_cert_file": "ETCD_CA_CERT_FILE",\n "mtu": 2070,\n "ipam": {\n "type": "calico-ipam",\n "assign_ipv4": "true",\n "assign_ipv6": "false"\n },\n "container_settings": {\n "allow_ip_forwarding": true\n },\n "policy": {\n "type": "k8s",\n "k8s_api_root": "https://[KUBERNETES_SERVICE_HOST]:KUBERNETES_SERVICE_PORT",\n "k8s_auth_token": "SERVICEACCOUNT_TOKEN"\n },\n "kubernetes": {\n "kubeconfig": "KUBECONFIG_FILEPATH"\n }\n },\n {\n "type": "portmap",\n "snat": true,\n "capabilities": {"portMappings": true}\n }\n ]\n}","etcd_ca":"/calico-secrets/etcd-ca","etcd_cert":"/calico-secrets/etcd-cert","etcd_endpoints":"https://10.0.10.163:2379","etcd_key":"/calico-secrets/etcd-key"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"calico-config","namespace":"kube-system"}}
creationTimestamp: "2021-04-17T05:51:09Z"
name: calico-config
namespace: kube-system
resourceVersion: "19908"

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
director-0-ccd-2-15:~> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"91fb1371fc570cfd3b3052012ce68fdd78b41c07", GitTreeState:"clean", BuildDate:"2020-10-28T08:55:37Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"91fb1371fc570cfd3b3052012ce68fdd78b41c07", GitTreeState:"clean", BuildDate:"2020-10-28T08:47:48Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- Primary CNI for Kubernetes cluster: Calico

- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- 
director-0-ejlcluster:~> kubectl get crd  network-attachment-definitions.k8s.cni.cncf.io  -o yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"network-attachment-definitions.k8s.cni.cncf.io"},"spec":{"group":"k8s.cni.cncf.io","names":{"kind":"NetworkAttachmentDefinition","plural":"network-attachment-definitions","shortNames":["net-attach-def"],"singular":"network-attachment-definition"},"scope":"Namespaced","versions":[{"name":"v1","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"config":{"type":"string"}},"type":"object"}},"type":"object"}},"served":true,"storage":true}]}}
  creationTimestamp: "2021-04-19T05:08:54Z"
  generation: 1
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2021-04-19T05:08:54Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
      f:status:
        f:storedVersions: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-19T05:08:54Z"
  name: network-attachment-definitions.k8s.cni.cncf.io
  resourceVersion: "963"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/network-attachment-definitions.k8s.cni.cncf.io
  uid: 662d8268-079e-414d-a360-8d4b3f163349
spec:
  conversion:
    strategy: None
  group: k8s.cni.cncf.io
  names:
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    plural: network-attachment-definitions
    shortNames:
    - net-attach-def
    singular: network-attachment-definition
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              config:
                type: string
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    plural: network-attachment-definitions
    shortNames:
    - net-attach-def
    singular: network-attachment-definition
  conditions:
  - lastTransitionTime: "2021-04-19T05:08:54Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-04-19T05:08:54Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1

**Comment by dougbtv** [comment]
Fixed in #657
