### ISSUE TITLE
Cannot ping the second interface's IP fron another node.

### ISSUE THREAD

**Issue by chenliu1993** [k8snetworkplumbingwg/multus-cni#660]
This is just a help-wanted issue. 
I added the second interface using macvlan and assgined it with a default gateway like 192.168.0.1 and a host-local type ipam with ranges specified by me. And I can successfully saw the interfaces in the different nodes with names as "net1" on node1 and "net2" on node2  
But I cannot ping the net2 ip address from node1 even I have manually added the route to the node1 route table.
So is this expected? multus-cni just add the IP to interface but not responsible for connecting the nodes. the connection job is done by other settings? like net-attach-defs? or other routes settings?
If this is not expected, then is just modifying route tables enough? 
Thanks

**Comment by dougbtv** [comment]
Hi @chenliu1993 -- could you provide some additional info, especially:

* What platform? (aws, bare metal, etc)
* Can you provide the net-attach-def
* Can you provide an `kubectl exec -it your-pod -- ip a; ip route;`

Thanks!

**Comment by chenliu1993** [comment]
Platform: VSPhere
Net-attach-def:
`
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "macvlan",
    "name": "net-macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
          "type": "host-local",
          "subnet": "100.73.34.0/24",
          "rangeStart": "100.73.34.20",
          "rangeEnd": "100.73.34.149",
          "gateway": "100.73.34.254",
          "routes": [
              { "dst": "100.73.34.0/24", "gw": "100.73.34.254" }
          ]
    }
  }'`
and the samplepod is:
`apiVersion: v1
kind: Pod
metadata:
  name: w0pod
  annotations:
    k8s.v1.cni.cncf.io/networks: default/macvlan-conf
spec:
  containers:
  - name: alpine
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/alpine
  nodeSelector:
    worker: "0"
---
apiVersion: v1
kind: Pod
metadata:
  name: w1pod
  annotations:
    k8s.v1.cni.cncf.io/networks: default/macvlan-conf
spec:
  containers:
  - name: alpine
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/alpine
  nodeSelector:
    worker: "1"`
the pods status are:
`NAME    READY   STATUS    RESTARTS   AGE
w0pod   1/1     Running   0          3m41s
w1pod   1/1     Running   0          3m13s`
the output of `kubectl exec -it your-pod -- ip a; ip route;`are:
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if14: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 8e:1a:60:c7:76:93 brd ff:ff:ff:ff:ff:ff
    inet 100.96.1.10/24 brd 100.96.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8c1a:60ff:fec7:7693/64 scope link 
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 26:06:b4:cb:fe:f5 brd ff:ff:ff:ff:ff:ff
    inet 100.73.34.21/24 brd 100.73.34.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fd01:0:106:5:2406:b4ff:fecb:fef5/64 scope global dynamic 
       valid_lft 2591956sec preferred_lft 604756sec
    inet6 fe80::2406:b4ff:fecb:fef5/64 scope link 
       valid_lft forever preferred_lft forever
default via 10.186.63.254 dev ens160 
10.186.48.0/20 dev ens160  proto kernel  scope link  src 10.186.50.165 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown`
and 
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 76:29:65:63:da:86 brd ff:ff:ff:ff:ff:ff
    inet 100.96.2.3/24 brd 100.96.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::7429:65ff:fe63:da86/64 scope link 
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether a6:3f:e7:5e:c9:f0 brd ff:ff:ff:ff:ff:ff
    inet 100.73.34.20/24 brd 100.73.34.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fd01:0:106:5:a43f:e7ff:fe5e:c9f0/64 scope global dynamic 
       valid_lft 2591925sec preferred_lft 604725sec
    inet6 fe80::a43f:e7ff:fe5e:c9f0/64 scope link 
       valid_lft forever preferred_lft forever
default via 10.186.63.254 dev ens160 
10.186.48.0/20 dev ens160  proto kernel  scope link  src 10.186.50.165 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown`
 and when sh into the node running w1pod and to ping the w0pod's IP. the default CNI works while the macvlan IP cannout be pinged.

**Comment by chenliu1993** [comment]
my issue is solved according to [https://github.com/k8snetworkplumbingwg/multus-cni/issues/390.](url)
seems some settings are not opened like promiscious on the interface.
thanks @dougbtv

**Comment by szgRunner** [comment]
> This is just a help-wanted issue.
> I added the second interface using macvlan and assgined it with a default gateway like 192.168.0.1 and a host-local type ipam with ranges specified by me. And I can successfully saw the interfaces in the different nodes with names as "net1" on node1 and "net2" on node2
> But I cannot ping the net2 ip address from node1 even I have manually added the route to the node1 route table.
> So is this expected? multus-cni just add the IP to interface but not responsible for connecting the nodes. the connection job is done by other settings? like net-attach-defs? or other routes settings?
> If this is not expected, then is just modifying route tables enough?
> Thanks

@chenliu1993  hey, i have the same problem as you , how did you solve it ? I have turned on the mixed mode of the host network card and it does not work either.
