### ISSUE TITLE
SR-IOV handling possibly breaks with K8s 1.21+ due to checkpoint file structure change

### ISSUE THREAD

**Issue by Levovar** [k8snetworkplumbingwg/multus-cni#665]
Following commit changed the type of the DeviceIDs parameter in Kubelet from []string to map[int][]string:
https://github.com/kubernetes/kubernetes/commit/a8b8995ef241e93e9486d475126450f33f24ef4e

As result I guess every project depending on directly parsing Kubelet's checkpoint file breaks when used with K8s 1.21+, because the file cannot be unmarshalled anymore into an old structure such as:
https://github.com/k8snetworkplumbingwg/multus-cni/blob/a52680b3bfa026087879f89fae331b0dfc8dffe0/pkg/checkpoint/checkpoint.go#L36

At least mine sure as hell broke, thought I also let you know :)
As a reference here is the new format:
https://github.com/kubernetes/kubernetes/blob/a41a3ed4ae77a7902577bdb50b35fc5f42ed7c60/pkg/kubelet/cm/devicemanager/checkpoint/checkpoint.go#L34

**Comment by s1061123** [comment]
Thank you so much for letting us about the changes, @Levovar !

**Comment by Levovar** [comment]
np :) I'm still testing my solution on real environments, but at least in UT sthing like this seems to be okay, and generally working for both older and newer K8s versions:
https://github.com/nokia/CPU-Pooler/pull/66/files

**Comment by ahalim-intel** [comment]
This above changes should not affect multus as for device info we primarily rely on kubelet pod_resource api. The checkpoint client was there as a fallback where the kubelet pod_resource endpoint was not available(earlier version of K8s).

**Comment by Levovar** [comment]
might be a good time to delete the checkpoint file handling code alltogether then

thanks for the pointer BTW, did not occur to me to use the monitoring API for this purpose!

**Comment by zshi-redhat** [comment]
I agree with @ahalim-intel that checkpoint client is a fallback option, the first option multus would try to get resource name is pod_resource api.  
If we were to fix this issue, it might be helpful to the scenario: latest multus is used on older kubernetes versions (which don't support pod_resource api). I don't know if multus has version compatability with k8s, thoughts?

**Comment by s1061123** [comment]
How about to discuss about it in next maintainers meeting. To me, I suppose it could be good timing to unsupport checkpoint because Kubernetes does not support checkpoint any longer and multus should follow Kubernetes...
