### ISSUE TITLE
what's the meaning of multiple delegates

### ISSUE THREAD

**Issue by hackerain** [k8snetworkplumbingwg/multus-cni#668]
in configuration doc, the explanation of delegates is as follow:

`delegates ([]map,required): number of delegate details in the Multus`

but in mose use cases I found, there is only one item in delegates, so I am confused what multus will do if there are multiple delegates, and what's the relationship between them, and when should we use it.
 
thanks

**Comment by dougbtv** [comment]
The `delegates` field is kind of the "static way of adding network attachments" -- as opposed to NetworkAttachmentDefinitions. So if you specified the CNI configurations for other CNI plugins that Multus "delegates" to -- it could be here in the configuration, as opposed to in CRDs (e.g. NetworkAttachmentDefinitions).

And without Kubernetes, Multus would still work -- and it would do so with the `delegates` field in the configuration file.

Potentially, the docs could be cleaned up to help clarify this.

**Comment by hackerain** [comment]
OK, got this, thank you @dougbtv

**Comment by hackerain** [comment]
By the way, I found under the hood, the networks in "k8s.v1.cni.cncf.io/networks" annotations will convert to delegates, every network is a delegate.
