### ISSUE TITLE
Pod deletion fails on CRI-O runtime with calico as default plugin

### ISSUE THREAD

**Issue by ahalim-intel** [k8snetworkplumbingwg/multus-cni#677]
**What happend**:
When try to delete a Pod which was created after Multus is installed with calico as default network provider Pod goes in Terminating state and it never gets deleted.

kubectl describe pod shows following logs:

` 
  Warning  FailedKillPod   112s (x2 over 112s)  kubelet            error killing pod: failed to "KillPodSandbox" for "098d82f5-8f10-444b-9806-6ec2504e0c09" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_nettools1_default_098d82f5-8f10-444b-9806-6ec2504e0c09_0(ba0367bdd10f9db8c8a00f09ce2f953c9aeaadd41fa04fa028b15cfec732c9b9): network \"multus-cni-network\" requested interface name \"eth0\" already assigned"
`

**What you expected to happen**:
Pod should get deleted successfully

**How to reproduce it (as minimally and precisely as possible)**:
Install crio, K8s cluster with kubeadm,  install calico, install multus using:
```
kubectl apply -f images/multus-daemonset-crio.yml
```

Run a test pod:
```
# kubectl run nettools1 --image=praqma/network-multitool

# kubectl get pods
NAME        READY   STATUS    RESTARTS   AGE
nettools1   1/1     Running   0          9s

# kubectl delete pod nettools1
pod "nettools1" deleted
^C

# The deletion command above never returns.
# From another terminal:
# kubectl get pods
NAME        READY   STATUS        RESTARTS   AGE
nettools1   0/1     Terminating   0          18m


# kubectl describe pod nettools1
...

  Warning  FailedKillPod   112s (x2 over 112s)  kubelet            error killing pod: failed to "KillPodSandbox" for "098d82f5-8f10-444b-9806-6ec2504e0c09" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_nettools1_default_098d82f5-8f10-444b-9806-6ec2504e0c09_0(ba0367bdd10f9db8c8a00f09ce2f953c9aeaadd41fa04fa028b15cfec732c9b9): network \"multus-cni-network\" requested interface name \"eth0\" already assigned"

```
**Anything else we need to know?**:

**Environment**:

- Multus version v3.4.2
  image path and image ID (from 'docker images'): 
  docker.io/nfvpe/multus                latest              323ac100f148a
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- Primary CNI for Kubernetes cluster:
   calico v3.19.0 
- OS (e.g. from /etc/os-release):
  CentOS 7
- File of '/etc/cni/net.d/'
00-multus.conf  100-crio-bridge.conf  10-calico.conflist  200-loopback.conf  calico-kubeconfig  multus.d

$ cat /etc/cni/net.d/00-multus.conf
```
{
  "cniVersion": "0.3.1",
  "name": "multus-cni-network",
  "type": "multus",
  "capabilities": {
    "portMappings": true
  },
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "delegates": [
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "silpixa00399119",
          "mtu": 1440,
          "ipam": {
            "type": "calico-ipam"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  ]
}
```

$ cat /etc/cni/net.d/10-calico.conflist | jq
```json
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "silpixa00399119",
      "mtu": 1440,
      "ipam": {
        "type": "calico-ipam"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
```

- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
 None used for this test.
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
 No yaml. used kubectl run ...
- Other log outputs (if you use multus logging)
 Didn't have logging enabled, unfortunately. But logs from Pod description probably good enough?

- Other logs:

$ cat /var/lib/cni/multus/ba0367bdd10f9db8c8a00f09ce2f953c9aeaadd41fa04fa028b15cfec732c9b9 | jq
```json
[                                                                                                                      
  {
    "Conf": {
      "cniVersion": "0.3.1",
      "name": "k8s-pod-network",
      "ipam": {},
      "dns": {}
    },
    "ConfList": {
      "cniVersion": "0.3.1",
      "name": "k8s-pod-network",
      "plugins": [
        {
          "type": "calico",
          "ipam": {
            "type": "calico-ipam"
          },
          "dns": {}
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          },
          "ipam": {},
          "dns": {}
        }
      ]
    },
    "Name": "",
    "IsFilterGateway": false,
    "Bytes": "eyJjbmlWZXJzaW9uIjoiMC4zLjEiLCJuYW1lIjoiazhzLXBvZC1uZXR3b3JrIiwicGx1Z2lucyI6W3siZGF0YXN0b3JlX3R5cGUiOiJrdWJlcm5ldGVzIiwiaXBhbSI6eyJ0eXBlIjoiY2FsaWNvLWlwYW0ifSwia3ViZXJuZXRlcyI6eyJrdWJlY29uZmlnIjoiL2V0Yy9jbmkvbmV0LmQvY2FsaWNvLWt1YmVjb25maWcifSwibG9nX2xldmVsIjoiaW5mbyIsIm10dSI6MTQ0MCwibm9kZW5hbWUiOiJzaWxwaXhhMDAzOTkxMTkiLCJwb2xpY3kiOnsidHlwZSI6Ims4cyJ9LCJ0eXBlIjoiY2FsaWNvIn0seyJjYXBhYmlsaXRpZXMiOnsicG9ydE1hcHBpbmdzIjp0cnVlfSwic25hdCI6dHJ1ZSwidHlwZSI6InBvcnRtYXAifV19"
  }
]
```

Noticed that there are two `results` cache for same eth0 interface for this Pod

$ ll /var/lib/cni/results/
```
-rw-------. 1 root root 1113 May 25 11:38 k8s-pod-network-ba0367bdd10f9db8c8a00f09ce2f953c9aeaadd41fa04fa028b15cfec732c9b9-eth0
-rw-------. 1 root root 1284 May 25 11:38 multus-cni-network-ba0367bdd10f9db8c8a00f09ce2f953c9aeaadd41fa04fa028b15cfec732c9b9-eth0
```

**Comment by s1061123** [comment]
Seems to be dup of https://github.com/k8snetworkplumbingwg/multus-cni/issues/669

Could you please try latest image in https://github.com/orgs/k8snetworkplumbingwg/packages/container/multus-cni/2700971?tag=latest ?

**Comment by ahalim-intel** [comment]
Thanks @s1061123, with latest image don't see this issue any longer. I will close this.

**Comment by jnpr-pradeep** [comment]
@s1061123 @ahalimx86 I am seeing the same issue with the stable image.

below is the image used:
- name: kube-multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
        command: ["/entrypoint.sh"]

**Comment by s1061123** [comment]
Could you please try latest image in https://github.com/orgs/k8snetworkplumbingwg/packages/container/multus-cni/2700971?tag=latest ?

**Comment by jnpr-pradeep** [comment]
@s1061123 I need to use this as part of the yaml, is it not available with any tag/version to access?

**Comment by s1061123** [comment]
once we release new version, then the new tag is added. Please wait for that.

**Comment by jnpr-pradeep** [comment]
@s1061123  thanks for the confirmation. what is coming release GA time line?

**Comment by s1061123** [comment]
@jnpr-pradeep v3.7.2 is released today.
