### ISSUE TITLE
Could not  assign static IP to pod with Multus plugin

### ISSUE THREAD

**Issue by arifur2021** [k8snetworkplumbingwg/multus-cni#684]
I would appreciate if anyone help me to resolve following issue.

Trying to assign a static IP to a pod (ubuntu) using multus plugin. But pod is stuck in "ContainerCreate" state with the following error:

Events:
  Type     Reason                  Age              From                 Message
  ----     ------                  ----             ----                 -------
  Normal   Scheduled               12s              default-scheduler    Successfully assigned default/csrx to user-host2
  Normal   AddedInterface          11s              multus               Add eth0 [172.16.1.116/32]
  Warning  FailedCreatePodSandBox  9s               kubelet, user-host2  Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "05d5312c427e52cfda529c141a38dcad09865e92c1adbb37d2304fe8984d0462" network for pod "csrx": networkPlugin cni failed to set up pod "csrx_default" network: [default/csrx:br-csrx]: error adding container to network "br-csrx": **failed to find plugin "static" in path [/opt/cni/bin /opt/cni/bin], failed to clean up sandbox container "05d5312c427e52cfda529c141a38dcad09865e92c1adbb37d2304fe8984d0462" network for pod "csrx": networkPlugin cni failed to teardown pod "csrx_default" network: delegateDel: error invoking DelegateDel - "bridge": error in getting result from DelNetwork: failed to find plugin "static" in path [/opt/cni/bin /opt/cni/bin]]**
  Normal   SandboxChanged          7s (x2 over 9s)  kubelet, user-host2  Pod sandbox changed, it will be killed and re-created.

===== Network Attachment Config =====

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-csrx
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-1",
	  "master": "ens192",
      "promiscMode": true,
      "ipam": {
        "type": "static",
         "addresses": [
           {
             "address": "20.0.0.1/24"
           }
			]
      }
    }'

---

============ POD definition =================

$ cat apps/csrx/csrx-2/csrx-pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csrx
  annotations:
    k8s.v1.cni.cncf.io/networks: br-csrx

spec:
  containers:
  - name: csrx
    securityContext:
       privileged: true
    image: gcr.io/encqor-ilab-2/csrx:21.1R1.11
    imagePullPolicy: IfNotPresent
    env:
    - name: CSRX_ROOT_PASSWORD
      value: "Temp123"
    - name: CSRX_SIZE
      value: "large"
    - name: CSRX_HUGEPAGES
      value: "no"
    - name: CSRX_PACKET_DRIVER
      value: "interrupt"
    - name: CSRX_AUTO_ASSIGN_IP
      value: "yes"
    - name: CSRX_FORWARD_MODE
      value: "routing"
    - name: CSRX_JUNOS_CONFIG
      value: "var/jail/csrx_config"
    volumeMounts:
    - name: config
      mountPath: "/var/jail"
    - name: disk
      mountPath: "/dev"
  imagePullSecrets:
  - name: gcr-io-secret
  volumes:
  - name: config
    configMap:
      name: csrx-configmap
      items:
      - key: csrx_config
        path: csrx_config
  - name: disk
    hostPath:
     path: /dev
     type: Directory

---

Thanks in advance.

**Comment by s1061123** [comment]
**failed to find plugin "static" in path [/opt/cni/bin /opt/cni/bin], failed to clean up sandbox container "05d5312c427e52cfda529c141a38dcad09865e92c1adbb37d2304fe8984d0462" network for pod "csrx": networkPlugin cni failed to teardown pod "csrx_default" network: delegateDel: error invoking DelegateDel - "bridge": error in getting result from DelNetwork: failed to find plugin "static" in path [/opt/cni/bin /opt/cni/bin]]**

This message shows your environment may not have `static` cni plugin in CNI directory (/opt/cni/bin). Could you please check plugin in the directory?

**Comment by arifur2021** [comment]
@s1061123 
I was able to resolve pod launching issue by using the multus-daemonset-gke-1.16.yml manifest instead of classic one.
However, now pod is created but interface is not added to the bridge and no error is showing this time.

Following is the config


ubuntu@gke-admin-ws-210511-105308:~$ cat apps/jtac/csrx-configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csrx-configmap
data:
  csrx_config: |
    interfaces { ge-0/0/0 { unit 0; } ge-0/0/1 { unit 0; } }
    security { policies { default-policy { permit-all; } }
    zones { security-zone trust { host-inbound-traffic {system-services {all;}
    protocols { all; } } interfaces { ge-0/0/0.0; } }
    security-zone untrust { host-inbound-traffic { system-services { all; }
    protocols { all; } } interfaces { ge-0/0/1.0; } } } }
ubuntu@gke-admin-ws-210511-105308:~$


ubuntu@gke-admin-ws-210511-105308:~$ cat apps/jtac/csrx_network.yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-nw-1-1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "north-bridge",
      "promiscMode": true,
      "ipam": {
        "type": "static",
                "addresses": [
                        {
                                "address": "120.0.0.11/24"
                        }
                ],
                "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
      }
    }'
---


ubuntu@gke-admin-ws-210511-105308:~$ cat apps/jtac/csrx.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: csrx-cm
  labels:
    app: csrx-cm
  annotations:
    k8s.v1.cni.cncf.io/networks: bridge-nw-1-1@ens192
spec:
  containers:
  - name: csrx-cm
    securityContext:
       privileged: true
    image: gcr.io/encqor-ilab-2/csrx:21.1R1.11
    imagePullPolicy: Always
    env:
    - name: CSRX_ROOT_PASSWORD
      value: "lab123"
    - name: CSRX_SIZE
      value: "large"
    - name: CSRX_HUGEPAGES
      value: "no"
    - name: CSRX_PACKET_DRIVER
      value: "interrupt"
    - name: CSRX_JUNOS_CONFIG
      value: "/var/jail/csrx_config"
    - name: CSRX_FORWARD_MODE
      value: "routing"
    - name: CSRX_TCP_CKSUM_CALC
      value: "yes"
    volumeMounts:
    - name: config
      mountPath: "/var/jail"
    - name: disk
      mountPath: "/dev"
  imagePullSecrets:
  - name: gcr-io-secret
  volumes:
  - name: config
    configMap:
      name: csrx-configmap
      items:
      - key: csrx_config
        path: csrx_config
  - name: disk
    hostPath:
     path: /dev
     type: Directory
  nodeSelector:
    kubernetes.io/hostname: user-host1

ubuntu@gke-admin-ws-210511-105308:~$


ubuntu@gke-admin-ws-210511-105308:~$ kubectl --kubeconfig usercluster1-kubeconfig describe pods csrx-cm
Name:         csrx-cm
Namespace:    default
Priority:     0
Node:         user-host1/10.176.94.240
Start Time:   Fri, 11 Jun 2021 17:17:48 +0000
Labels:       app=csrx-cm
Annotations:  cni.projectcalico.org/podIP: 172.16.2.78/32
              cni.projectcalico.org/podIPs: 172.16.2.78/32
              k8s.v1.cni.cncf.io/networks: bridge-nw-1-1@ens192
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"bridge-nw-1-1@ens192"},"labels":{"app":"csrx-cm"...
Status:       Running
IP:           172.16.2.78
IPs:
  IP:  172.16.2.78
Containers:
  csrx-cm:
    Container ID:   docker://7481a1ac754f8b1fc7897b06260ca3e83d54ee16eba6cad89804c99e4403dd60
    Image:          gcr.io/encqor-ilab-2/csrx:21.1R1.11
    Image ID:       docker-pullable://gcr.io/encqor-ilab-2/csrx@sha256:eb68b0cb9d0ed1e06deb7787bc7a77162225dbea40c6f87cea672bb75871ad16
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 11 Jun 2021 17:17:51 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      CSRX_ROOT_PASSWORD:   lab123
      CSRX_SIZE:            large
      CSRX_HUGEPAGES:       no
      CSRX_PACKET_DRIVER:   interrupt
      CSRX_JUNOS_CONFIG:    /var/jail/csrx_config
      CSRX_FORWARD_MODE:    routing
      CSRX_TCP_CKSUM_CALC:  yes
    Mounts:
      /dev from disk (rw)
      /var/jail from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-j826r (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      csrx-configmap
    Optional:  false
  disk:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  Directory
  default-token-j826r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-j826r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=user-host1
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                 Message
  ----    ------     ----  ----                 -------
  Normal  Scheduled  22m   default-scheduler    Successfully assigned default/csrx-cm to user-host1
  Normal  Pulling    22m   kubelet, user-host1  Pulling image "gcr.io/encqor-ilab-2/csrx:21.1R1.11"
  Normal  Pulled     22m   kubelet, user-host1  Successfully pulled image "gcr.io/encqor-ilab-2/csrx:21.1R1.11"
  Normal  Created    22m   kubelet, user-host1  Created container csrx-cm
  Normal  Started    22m   kubelet, user-host1  Started container csrx-cm
ubuntu@gke-admin-ws-210511-105308:~$


ubuntu@gke-admin-ws-210511-105308:~$ kubectl --kubeconfig usercluster1-kubeconfig exec -it csrx-cm -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if35: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether a2:a5:03:5f:5d:e8 brd ff:ff:ff:ff:ff:ff
    inet 172.16.2.78/32 brd 172.16.2.78 scope global eth0
       valid_lft forever preferred_lft forever
ubuntu@gke-admin-ws-210511-105308:~$

I am expecting 120.0.0.11 IP interface should show here.

root@user-host1:~# ip link show type bridge
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:7e:08:b4:b9 brd ff:ff:ff:ff:ff:ff
28: north-bridge: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
root@user-host1:~#

I would appreciate if you can help in this case.

Thanks in advance.

**Comment by s1061123** [comment]
@cucosion may know about it because he create yaml file for gke.
hi @cucosion , could you please take a look into it?

I suspect that your gke does not use multus cni yet. Please check 

- CNI config has multus configuration or not, and 
- multus cni plugin, bridge cni plugin and static cni plugin are in CNI bin directory?

Please ask cloud provider about the location of CNI config and CNI bin directory because these config depends on deployment and I am not good at GKE.

**Comment by arifur2021** [comment]
@s1061123 Thank you for your help. Appreciate it.

multus and static cni plugins are NOT in CNI bin directory, only bridge cni plugin. However, multus config file exist in /etc/cni/net.d/.  Following is the capture from one of the worker nodes:
```
root@user-host2:~# ls -l /opt/cni/bin/
total 160936
-rwxr-xr-x 1 root root  4159518 May 25 18:19 bandwidth
-r-xr-xr-x 1 root root  4028260 Jan  1  2000 bridge
-rwxr-xr-x 1 root root 37257216 May 25 18:19 calico
-rwxr-xr-x 1 root root 37257216 May 25 18:20 calico-ipam
-r-xr-xr-x 1 root root 10232415 Jan  1  2000 dhcp
-rwxr-xr-x 1 root root  3069556 May 25 18:20 flannel
-rwxr-xr-x 1 root root  3614480 May 25 18:20 host-local
-rwxr-xr-x 1 root root 37257216 May 25 18:20 install
-r-xr-xr-x 1 root root  3572685 Jan  1  2000 ipvlan
-rwxr-xr-x 1 root root  3209463 May 25 18:20 loopback
-r-xr-xr-x 1 root root  3613497 Jan  1  2000 macvlan
-rwxr-xr-x 1 root root  3939867 May 25 18:20 portmap
-r-xr-xr-x 1 root root  3993428 Jan  1  2000 ptp
-r-xr-xr-x 1 root root  2641877 Jan  1  2000 sample
-rwxr-xr-x 1 root root  3356587 May 25 18:20 tuning
-r-xr-xr-x 1 root root  3568537 Jan  1  2000 vlan
```
```
root@user-host2:~# ls -l /etc/cni/net.d/
total 16
-rw------- 1 root root  605 Jun 11 16:48 **00-multus.conf**  
-rw-r--r-- 1 root root  561 May 25 18:20 10-calico.conflist
-rw------- 1 root root 2764 May 25 18:20 calico-kubeconfig
drwxr-xr-x 2 root root 4096 Jun 11 16:48 multus.d
root@user-host2:~#
```

@cucosion, do i need to enable network policy to make working calico?

Thanks.

**Comment by arifur2021** [comment]
I re-installed multus plugin and this time binary file is showing in the /opt/cni/bin/ directory on each worker node, but static plugin is missing.

```
ubuntu@user-host2:~$ ls -l /opt/cni/bin/
total 201832
-rwxr-xr-x 1 root root  4159518 May 25 18:19 bandwidth
-r-xr-xr-x 1 root root  4028260 Jan  1  2000 bridge
-rwxr-xr-x 1 root root 37257216 May 25 18:19 calico
-rwxr-xr-x 1 root root 37257216 May 25 18:20 calico-ipam
-r-xr-xr-x 1 root root 10232415 Jan  1  2000 dhcp
-rwxr-xr-x 1 root root  3069556 May 25 18:20 flannel
-rwxr-xr-x 1 root root  3614480 May 25 18:20 host-local
-rwxr-xr-x 1 root root 37257216 May 25 18:20 install
-r-xr-xr-x 1 root root  3572685 Jan  1  2000 ipvlan
-rwxr-xr-x 1 root root  3209463 May 25 18:20 loopback
-r-xr-xr-x 1 root root  3613497 Jan  1  2000 macvlan
-rwxr-xr-x 1 root root 41874840 Jun 12 06:18 multus
-rwxr-xr-x 1 root root  3939867 May 25 18:20 portmap
-r-xr-xr-x 1 root root  3993428 Jan  1  2000 ptp
-r-xr-xr-x 1 root root  2641877 Jan  1  2000 sample
-rwxr-xr-x 1 root root  3356587 May 25 18:20 tuning
-r-xr-xr-x 1 root root  3568537 Jan  1  2000 vlan
ubuntu@user-host2:~$
```

**Comment by arifur2021** [comment]
This time when I launched a pod with nad, I am seeing in pods description that multus added an interface (eth0) with its pod IP but 2nd interface is missing.

`ubuntu@gke-admin-ws-210511-105308:~$ cat apps/centos-nad/centos-nad.yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: centos-runtimeconfig-def
spec:
  config: '{
            "cniVersion": "0.3.1",
            "type": "ipvlan",
            "capabilities": { "ips": true },
            "master": "eth1",
            "mode": "l3",
            "ipam": {
                "type": "static"
            }
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-runtimeconfig
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "centos-runtimeconfig-def",
              "interface": "ens192",
              "ips": [ "10.1.1.104/24" ],
              # "mac": "00:50:56:88:5e:cc" }
    ]'
spec:
  containers:
  - name: centos-runtimeconfig
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
---
ubuntu@gke-admin-ws-210511-105308:~$`

`ubuntu@gke-admin-ws-210511-105308:~$ kubectl  --kubeconfig usercluster1-kubeconfig describe pods centos-runtimeconfig
Name:         centos-runtimeconfig
Namespace:    default
Priority:     0
Node:         user-host1/10.176.94.240
Start Time:   Sat, 12 Jun 2021 06:29:53 +0000
Labels:       <none>
Annotations:  cni.projectcalico.org/podIP: 172.16.2.86/32
              cni.projectcalico.org/podIPs: 172.16.2.86/32
              k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "ips": [
                        "172.16.2.86"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks:
                [ { "name": "centos-runtimeconfig-def", "interface": "ens192", "ips": [ "10.1.1.104/24" ], # "mac": "00:50:56:88:5e:cc" } ]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "ips": [
                        "172.16.2.86"
                    ],
                    "default": true,
                    "dns": {}
                }]
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"[ { \"name\": \"centos-runtimeconfig-def\", \"in...
Status:       Running
IP:           172.16.2.86
IPs:
  IP:  172.16.2.86
Containers:
  centos-runtimeconfig:
    Container ID:  docker://d65ff125028f6e89ce5af0b78640880d92f58d45e434a26ca268687df0ec180f
    Image:         docker.io/centos/tools:latest
    Image ID:      docker-pullable://centos/tools@sha256:81159542603c2349a276a30cc147045bc642bd84a62c1b427a8d243ef1893e2f
    Port:          <none>
    Host Port:     <none>
    Command:
      /sbin/init
    State:          Running
      Started:      Sat, 12 Jun 2021 06:29:55 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-j826r (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-j826r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-j826r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason          Age   From                 Message
  ----    ------          ----  ----                 -------
  Normal  Scheduled       113s  default-scheduler    Successfully assigned default/centos-runtimeconfig to user-host1
  Normal  AddedInterface  111s  multus               Add eth0 [172.16.2.86/32]			<<<<<<<<<<<<<<<<<<<<<<<
  Normal  Pulling         111s  kubelet, user-host1  Pulling image "docker.io/centos/tools:latest"
  Normal  Pulled          111s  kubelet, user-host1  Successfully pulled image "docker.io/centos/tools:latest"
  Normal  Created         111s  kubelet, user-host1  Created container centos-runtimeconfig
  Normal  Started         111s  kubelet, user-host1  Started container centos-runtimeconfig
ubuntu@gke-admin-ws-210511-105308:~$`

`ubuntu@gke-admin-ws-210511-105308:~$ kubectl  --kubeconfig usercluster1-kubeconfig exec -it centos-runtimeconfig -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if43: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether 5a:af:e8:c7:cd:06 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.2.86/32 brd 172.16.2.86 scope global eth0
       valid_lft forever preferred_lft forever
ubuntu@gke-admin-ws-210511-105308:~$`

`ubuntu@gke-admin-ws-210511-105308:~$ kubectl  --kubeconfig usercluster1-kubeconfig exec -it centos-runtimeconfig bash
[root@centos-runtimeconfig /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if43: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether 5a:af:e8:c7:cd:06 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.2.86/32 brd 172.16.2.86 scope global eth0
       valid_lft forever preferred_lft forever
[root@centos-runtimeconfig /]#`

**Comment by s1061123** [comment]
Please install static plugin.

**Comment by s1061123** [comment]
As far as I looked the last log,

- kubernetes invokes multus cni from event message, `Add eth0 [172.16.2.86/32]`
- pod annotation, `k8s.v1.cni.cncf.io/networks`, needs to be checked because this annotation written in JSON may be wrong.

For further debug, I recommend to use `logFile` and `logLevel` configurations in multus CNI config. This shows error messages and intermediate debug message if you change log level to 'debug'.

**Comment by arifur2021** [comment]
> Please install static plugin.

could you please let me know how to install static plugin. I did not find any procedure.

Thanks,
Arifur

**Comment by s1061123** [comment]
https://github.com/containernetworking/plugins/tree/master/plugins/ipam/static

Here is the repo and binaries are in release page.

**Comment by arifur2021** [comment]
@s1061123 

I did not find the binary for static plugin in release page and could build with repo. I would appreciate if you provide steps for installing the plugin.

Thanks.

**Comment by s1061123** [comment]
https://github.com/containernetworking/plugins/releases/tag/v0.9.1

You can ask how to install in its repo.
https://github.com/containernetworking/plugins/issues

**Comment by cucosion** [comment]
I will add few comments from the time i tested with **gke setup with cluster version 1.16.XXX** (add your version since they are deprecating old ones) on a single node with **host plugin for ip management.** **!!!!important to start the cluster with --enable-network-policy that will enable CNI in kublet**

#start the cluster with ubuntu and kubernetes 1.16
gcloud beta container clusters creat tvm-cl --zone europe-west1-b  --num-nodes=1 --machine-type=n1-standard-8 --image-type ubuntu --enable-network-policy --cluster-version "1.16.XXX"
#install multus, we've adapted it for google kubernetes engine, just apply it from deployment project - https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/images/multus-daemonset-gke-1.16.yml
kubectl apply -f multus-daemonset-gke-1.16.yml
#install all the NAD files that will be used by test modules
kubectl apply -f multus-nad-macvlan-conf-gcp-0.yml

**Use whereabouts-cni plugin instead of DHCP and host local to allocate IPs to second interface in multus across multiple nodes**

A CNI plugin is responsible for inserting a network interface into the container network namespace (e.g. one end of a veth pair) and making any necessary changes on the host (e.g. attaching the other end of the veth into a bridge).

It should then assign the IP to the interface and setup the routes consistent with the IP Address Management section by invoking appropriate IPAM plugin.

At this moment we are using the host-local plugin that was allocating IPs for multus only on the same node it was not synchronized across nodes. We have few other options for cross nodes on second interface in pod to allocate ip like:

https://github.com/containernetworking/plugins/tree/master/plugins/ipam - few options
and third parties plugins like whereabouts
I did choose whereabout since its easier to use, it keeps all the ips in sync on etcd.

Official page : https://github.com/openshift/whereabouts-cni/blob/master/README.md

Example: http://dougbtv.com/nfvpe/2019/11/27/whereabouts-a-cluster-wide-cni-ipam-plugin/

**whereabout-ds-gke-post-1.16.yaml**

`apiVersion: v1
kind: ServiceAccount
metadata:
  name: whereabouts
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: whereabouts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: whereabouts-cni
subjects:
- kind: ServiceAccount
  name: whereabouts
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whereabouts-cni
rules:
- apiGroups:
  - whereabouts.cni.cncf.io
  resources:
  - ippools
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whereabouts
  namespace: kube-system
  labels:
    tier: node
    app: whereabouts
spec:
  selector:
    matchLabels:
      name: whereabouts
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: whereabouts
        name: whereabouts
    spec:
      serviceAccountName: whereabouts
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: whereabouts
        image: dougbtv/whereabouts:latest
        env:
        - name: CNI_BIN_DIR
          value: "/host/home/kubernetes/bin"
        - name: WHEREABOUTS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/home/kubernetes/bin
        - name: cni-net-dir
          mountPath: /host/etc/cni/net.d
      volumes:
        - name: cnibin
          hostPath:
            path: /home/kubernetes/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
`

**Comment by cucosion** [comment]
> I re-installed multus plugin and this time binary file is showing in the /opt/cni/bin/ directory on each worker node, but static plugin is missing.
> 
> ```
> ubuntu@user-host2:~$ ls -l /opt/cni/bin/
> total 201832
> -rwxr-xr-x 1 root root  4159518 May 25 18:19 bandwidth
> -r-xr-xr-x 1 root root  4028260 Jan  1  2000 bridge
> -rwxr-xr-x 1 root root 37257216 May 25 18:19 calico
> -rwxr-xr-x 1 root root 37257216 May 25 18:20 calico-ipam
> -r-xr-xr-x 1 root root 10232415 Jan  1  2000 dhcp
> -rwxr-xr-x 1 root root  3069556 May 25 18:20 flannel
> -rwxr-xr-x 1 root root  3614480 May 25 18:20 host-local
> -rwxr-xr-x 1 root root 37257216 May 25 18:20 install
> -r-xr-xr-x 1 root root  3572685 Jan  1  2000 ipvlan
> -rwxr-xr-x 1 root root  3209463 May 25 18:20 loopback
> -r-xr-xr-x 1 root root  3613497 Jan  1  2000 macvlan
> -rwxr-xr-x 1 root root 41874840 Jun 12 06:18 **multus**
> -rwxr-xr-x 1 root root  3939867 May 25 18:20 portmap
> -r-xr-xr-x 1 root root  3993428 Jan  1  2000 ptp
> -r-xr-xr-x 1 root root  2641877 Jan  1  2000 sample
> -rwxr-xr-x 1 root root  3356587 May 25 18:20 tuning
> -r-xr-xr-x 1 root root  3568537 Jan  1  2000 vlan
> ubuntu@user-host2:~$
> ```



> @cucosion may know about it because he create yaml file for gke.
> hi @cucosion , could you please take a look into it?
> 
> I suspect that your gke does not use multus cni yet. Please check
> 
> * CNI config has multus configuration or not, and
> * multus cni plugin, bridge cni plugin and static cni plugin are in CNI bin directory?
> 
> Please ask cloud provider about the location of CNI config and CNI bin directory because these config depends on deployment and I am not good at GKE.

The plugin folder in gke is not default, i did changed in multus daemon sets to point to the one that gke is expecting. So if someone want to install a new plugin it will have to change the daemon set to point to that directory, this does not have anything related to multus itself :)

name: CNI_BIN_DIR
value: "/host/home/kubernetes/bin"

**Comment by arifur2021** [comment]
@cucosion 
Thank you for your feedback. I will post the update here.

**Comment by arifur2021** [comment]
> https://github.com/containernetworking/plugins/releases/tag/v0.9.1
> 
> You can ask how to install in its repo.
> https://github.com/containernetworking/plugins/issues

@s1061123 
Thank you.

**Comment by arifur2021** [comment]
@cucosion 

I installed whereabouts (with multus) IPAM cni plugin on GKE but bin file is missing on host directory (/opt/cni/bin).

Multus plugin is working well.

Following is the changes I made in the whereabouts daemonSet file.

`---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whereabouts
  namespace: kube-system
  labels:
    tier: node
    app: whereabouts
spec:
  selector:
    matchLabels:
      name: whereabouts
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: whereabouts
        name: whereabouts
    spec:
      hostNetwork: true
      serviceAccountName: whereabouts
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: whereabouts
        image: ghcr.io/k8snetworkplumbingwg/whereabouts:latest-amd64
        env:
        - name: CNI_BIN_DIR										<<<<<<<<<<<<<<<<< Add this
          value: "/host/home/ubuntu/opt/cni/bin"				<<<<<<<<<<<<<<<<< Add this and point to the correct bin directory
        - name: WHEREABOUTS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/home/ubuntu/opt/cni/bin		<<<<<<<<<<<<<<<<< point to the correct bin directory
        - name: cni-net-dir
          mountPath: /host/etc/cni/net.d				<<<<<<<<<<<<<<<<< point to the correct bin directory
      volumes:
        - name: cnibin
          hostPath:
            path: /host/home/ubuntu/opt/cni/bin			<<<<<<<<<<<<<<<<< point to the correct bin directory
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
`
`root@user-host3:/opt/cni/bin# ls -l
total 227832
-rwxr-xr-x 1 root root  4159518 Jun 14 18:31 bandwidth
-r-xr-xr-x 1 root root  4028260 Jan  1  2000 bridge
-rwxr-xr-x 1 root root 41472000 Jun 14 18:31 calico
-rwxr-xr-x 1 root root 41472000 Jun 14 18:32 calico-ipam
-rwxr-xr-x 1 root root 13979648 Jun 14 17:28 cilium-cni
-r-xr-xr-x 1 root root 10232415 Jan  1  2000 dhcp
-rwxr-xr-x 1 root root  3069556 Jun 14 18:32 flannel
-rwxr-xr-x 1 root root  3614480 Jun 14 18:32 host-local
-rwxr-xr-x 1 root root 41472000 Jun 14 18:32 install
-r-xr-xr-x 1 root root  3572685 Jan  1  2000 ipvlan
-rwxr-xr-x 1 root root  3209463 Jun 14 18:32 loopback
-r-xr-xr-x 1 root root  3613497 Jan  1  2000 macvlan
-rwxr-xr-x 1 root root 41874840 Jun 14 19:04 multus
-rwxr-xr-x 1 root root  3939867 Jun 14 18:32 portmap
-r-xr-xr-x 1 root root  3993428 Jan  1  2000 ptp
-r-xr-xr-x 1 root root  2641877 Jan  1  2000 sample
-rwxr-xr-x 1 root root  3356587 Jun 14 18:32 tuning
-r-xr-xr-x 1 root root  3568537 Jan  1  2000 vlan
`
`ubuntu@user-host3:~$ ls -l /etc/cni/net.d/whereabouts.d/
total 8
-rw------- 1 root root  127 Jun 17 15:10 whereabouts.conf
-rw------- 1 root root 2788 Jun 17 15:10 whereabouts.kubeconfig
ubuntu@user-host3:~$
`

Am i missing something?

Thanks,
Arifur

**Comment by cucosion** [comment]
@arifur2021 close this issue since its not related to multus, i pasted above an example of whereabouts daemon set, i think that you've missed it.

In my case i made the whereabouts work with below values

- name: CNI_BIN_DIR
value: "/host/home/kubernetes/bin"
- name: WHEREABOUTS_NAMESPACE
volumeMounts:
- name: cnibin
mountPath: /host/home/kubernetes/bin
- name: cni-net-dir
mountPath: /host/etc/cni/net.d
volumes:
- name: cnibin
hostPath:
path: /home/kubernetes/bin
- name: cni-net-dir
hostPath:
path: /etc/cni/net.d

**Comment by arifur2021** [comment]
@cucosion 
Thank you for your feedback. I am closing this issue.

**Comment by cucosion** [comment]
@s1061123 close this issue

**Comment by s1061123** [comment]
@cucosion sure, thanks!
