### ISSUE TITLE
Update Documentation on Integrating Multus with GKE

### ISSUE THREAD

**Issue by d3c3balus** [k8snetworkplumbingwg/multus-cni#687]
**What would you like to be added**:
Based on [this issue](https://github.com/k8snetworkplumbingwg/multus-cni/issues/685#issuecomment-863492673), the documentation on integrating Multus with GKE must be updated to reflect the following:

- if GKE cluster starts (or is created) with default `--network-plugin=kubenet`, then installing Multus will fail. This is because Kubenet does not care/use configuration directory `--cni-conf-dir`
- for successful installation of Multus on GKE, one must start GKE with CNIs: `--network-plugin==cni` and specify a CNI configuration in the `--cni-conf-dir` folder (default `/etc/cni/net.d`).
- the easiest way to achieve that is to create the GKE cluster with flag `--enable-network-policy`. This will add Calico as CNI master plugin and Multus installation will succeed.

**Why is this needed**:
With default GKE configuration (GKE using Kubenet), installation of Multus fails.

**Comment by dougbtv** [comment]
We think this might be better suited for the reference deployments: https://github.com/k8snetworkplumbingwg/reference-deployment

This repo is suited for vendor-specific deployments, whereas the instructions here are intended to be generic.

Though, I do believe that we could include some verbiage in our docs to be on the look out for the `--cni-conf-dir`  and `--cni-bin-dir` and also have a link to the reference deployments.
