### ISSUE TITLE
Mutlus-dameonset with crio is not invoking the multus cni

### ISSUE THREAD

**Issue by jnpr-pradeep** [k8snetworkplumbingwg/multus-cni#690]
What happend: 

Applied the multus daemonset crio (https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/images/multus-daemonset-crio.yml) in the minikube setup where cri-o is the CRI.

It created the multus pod and properly configured the 00-multus.conf by reading the CNIs from the /etc/cni/net.d directory.

Multus CNI is not invoked with NASA annotation at pod, I see only eth0 configured and looks the call didn't go to multus.
```----    ------     ----  ----               -------
  Normal  Scheduled  7s    default-scheduler  Successfully assigned default/multus-pod-2 to minikube
  Normal  Pulling    7s    kubelet            Pulling image "busybox"
  Normal  Pulled     1s    kubelet            Successfully pulled image "busybox" in 5.472083367s
  Normal  Created    1s    kubelet            Created container multus-pod-2
  Normal  Started    1s    kubelet            Started container multus-pod-2
```

However, if I use the multus daemonset (https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/images/multus-daemonset.yml) - its creating the multi interfaces as expected.

What you expected to happen:

It should create the multiple interfaces on the pod's container -- similar to,

``` Normal  Scheduled       8s    default-scheduler  Successfully assigned default/multus-pod-2 to minikube
  Normal  AddedInterface  8s    multus             Add eth0 [10.244.0.11/24]
  Normal  AddedInterface  8s    multus             Add net1 [172.17.30.2/24] from default/sriov-nad-1
  Normal  Pulling         7s    kubelet            Pulling image "busybox"
  Normal  Pulled          2s    kubelet            Successfully pulled image "busybox" in 5.461173661s
  Normal  Created         2s    kubelet            Created container multus-pod-2
  Normal  Started         2s    kubelet            Started container multus-pod-2
```

How to reproduce it (as minimally and precisely as possible):
Bring up the k8s with minkube crio-o as CRI and flannel as the CNI.

minikube start --cni flannel --container-runtime cri-o --kubernetes-version 1.20.1

Apply the multus-daemonset-crio.yml
from --> https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/images/multus-daemonset-crio.yml

Create a NAD my-nad.yaml

```apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-nad-1
spec:
  config: '{
  "type": "bridge",
  "cniVersion": "0.3.1",
  "name": "sriov-network-1",
  "bridge": "cni4",
  "isGateway": true,
  "ipMasq": true,
  "ipam": {
    "type": "host-local",
    "subnet": "172.17.40.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "172.17.40.1"
  }
}'
```

Create a pod with NASA annotation pod.yaml

```apiVersion: v1
kind: Pod
metadata:
  name: multus-pod-2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-nad-1
spec:
  containers:
    - name: multus-pod-2
      image: busybox
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
        privileged: true
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule"
```

**Comment by jnpr-pradeep** [comment]
@k8snetworkplumbingwg can someone take a look into the mentioned issue?

**Comment by s1061123** [comment]
This is because minikube cri-o's CNI configuration is different from upstream cri-o (build from source).  In this case, you can just use https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/images/multus-daemonset.yml

The difference from multus-daemonset and multus-daemonset-crio is CNI path configuration (i.e. CNI plugin directory), so it is okey to use multus-daemonset.yml.
