### ISSUE TITLE
I  have the same problem as 660

### ISSUE THREAD

**Issue by szgRunner** [k8snetworkplumbingwg/multus-cni#691]
This is just a help-wanted issue.
I added the second interface using macvlan and assgined it with a default gateway like 192.168.0.1 and a host-local type ipam with ranges specified by me. And I can successfully saw the interfaces in the different nodes with names as "net1" on node1 and "net2" on node2
But I cannot ping the net2 ip address from node1 even I have manually added the route to the node1 route table.
So is this expected? multus-cni just add the IP to interface but not responsible for connecting the nodes. the connection job is done by other settings? like net-attach-defs? or other routes settings?
If this is not expected, then is just modifying route tables enough?
Thanks

my issue is solved according to https://github.com/k8snetworkplumbingwg/multus-cni/issues/390.
seems some settings are not opened like promiscious on the interface.
thanks @dougbtv

[question #660](https://github.com/k8snetworkplumbingwg/multus-cni/issues/660)

@chenliu1993 hey, i have the same problem as you , how did you solve it ? I have turned on the mixed mode of the host network and it does not work either.

**Comment by s1061123** [comment]
This is expected due to macvlan interface. Macvlan interface cannot ping to master interface and vise-vaersa. This is design decision of macvlan, not multus-cni and macvlan CNI plugin. If you want to change, you need to change macvlan interface driver (of linux kernel).

I'm not good at linux kernel, so please ask linux kernel community if you have question about it.

**Comment by szgRunner** [comment]
> @helioaymoto
> 
> ## I just configured Multus - type:macvlan - on my VSPhere environment. To reach the POD interface from outside the VM, you need to configure the following settings on the `VM Network ` of the `Virtual Switch`. You can find these settings in the path - Virtual Switches -> VMm Network -> Edit Settings -> Security.
> Promiscuous mode - Override
> 
> MAC address changes - Override
> 
> Forged transmits - Override

I have changed my exsi vm by you said ,it works. thank you!

**Comment by szgRunner** [comment]
> This is expected due to macvlan interface. Macvlan interface cannot ping to master interface and vise-vaersa. This is design decision of macvlan, not multus-cni and macvlan CNI plugin. If you want to change, you need to change macvlan interface driver (of linux kernel).
> 
> I'm not good at linux kernel, so please ask linux kernel community if you have question about it.

my node was created by exsi vm , i think it is the point

**Comment by s1061123** [comment]
In this case, macvlan might be created by ESXI, not by multus. Please ask VMWare side because we just invoke macvlan plugin to create macvlan interface, the implementation of macvlan interface is in vmware esxi.

**Comment by dougbtv** [comment]
Could this be related to port security in vmware?

**Comment by boeboe** [comment]
I am having exactly the same problem on AWS. ICMP traffic is exiting the correct node interface on the correct secondary subnet, but it never arrives at the remote host, and hence also not on the remote pod.
