### ISSUE TITLE
Entrypoint.sh throws unknown parameter warning when the parameter is valid

### ISSUE THREAD

**Issue by cgchinmay** [k8snetworkplumbingwg/multus-cni#694]
Run entrypoint.sh with following arguments
```
containers:
      - name: kube-multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=auto"
        - "--cni-version=0.3.1"
        - "--multus-master-cni-file-name=10-xxxx.conflist"

multus ds pod logs show following warning
WARN: {unknown parameter "--multus-master-cni-file-name"}
```

This argument is not invalid, as can be seen [here](https://github.com/k8snetworkplumbingwg/multus-cni/blob/085870c4b52323df42980448fba3c06e5304e4d8/images/entrypoint.sh#L118)

**Comment by ipatrykx** [comment]
Hi @cgchinmay, you are using `stable` image which does seem not to support this feature yet. Could you please check if it will work as expected if you change the image tag from `stable` to `latest`? It seems that it was built just 11 days ago so I think it should support this already.

**Comment by dougbtv** [comment]
Patryk is definitely correct on this one, it's not in the `:stable` image because that's the last tagged version, so please use the `:snapshot` to use the latest image built at master HEAD.

(there's a new release coming up, so it should be in the stable release shortly)
