### ISSUE TITLE
Multus with calico

### ISSUE THREAD

**Issue by haha150** [k8snetworkplumbingwg/multus-cni#699]
Hi,

How can i deploy multus when i have calico deployed as my CNI? (commands + yaml file, etc)

For kubernetes 1.21.1

**Comment by nicklesimba** [comment]
Hello,

You should be able to follow the quickstart guide in the repository and use calico as your CNI. Was that not working for you? 

If you are looking for a calico reference, this may be what you are looking for:
https://github.com/k8snetworkplumbingwg/reference-deployment/tree/master/multus-calico

If I didn't answer your question, provide more details and I can try to clarify further.

**Comment by haha150** [comment]
Hi,

yes that one was not working for me, this is the errors:

> master@sekiicvh00173:~$ cat multus-daemonset.yml calico-daemonset.yml | kubectl apply -f -
> Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use a piextensions.k8s.io/v1 CustomResourceDefinition
> customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
> Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.auth orization.k8s.io/v1 ClusterRole
> clusterrole.rbac.authorization.k8s.io/multus created
> Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rb ac.authorization.k8s.io/v1 ClusterRoleBinding
> clusterrolebinding.rbac.authorization.k8s.io/multus created
> serviceaccount/multus created
> configmap/multus-cni-config created
> configmap/calico-config created
> customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
> customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
> clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
> clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
> clusterrole.rbac.authorization.k8s.io/calico-node created
> clusterrolebinding.rbac.authorization.k8s.io/calico-node created
> serviceaccount/calico-node created
> serviceaccount/calico-kube-controllers created
> unable to recognize "STDIN": no matches for kind "DaemonSet" in version "extensions/v1beta1"
> unable to recognize "STDIN": no matches for kind "DaemonSet" in version "extensions/v1beta1"
> unable to recognize "STDIN": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by maiqueb** [comment]
I did not check if it works, but, unless I'm wrong, daemonset has graduated to [v1](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#daemonset-v1-apps), which quite probably means `v1beta1` got deprecated then removed some time ago. 

I guess that yaml needs to be updated. I can try to address this tomorrow.

**Comment by haha150** [comment]
Thanks

**Comment by maiqueb** [comment]
Actually, I've found this PR pushed a long time ago that I think addresses exactly this: 
https://github.com/k8snetworkplumbingwg/reference-deployment/pull/8

**Comment by haha150** [comment]
Alright, great, will you merge it to master?

**Comment by maiqueb** [comment]
> Alright, great, will you merge it to master?

I do not have merge rights; trying to stir the pot and find someone who does and is willing to have it merged.

**Comment by maiqueb** [comment]
@haha150 should be OK now. Please confirm, and close the issue if you're OK with it.

> also, do i need to modify the files, i saw that they have "nodename": "KUBERNETES_NODE_NAME" and "kubeconfig": "KUBECONFIG_FILEPATH", etc?

yes, this is a template. You'd need to use to replace those with whatever applies in your setup.

**Comment by haha150** [comment]
hi, looks like thae PR you mentioned is not so good.

got these warnings + error:

> cat multus-daemonset.yml calico-daemonset.yml | kubectl apply -f -

> Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
> Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
> clusterrole.rbac.authorization.k8s.io/multus created
> Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
> clusterrolebinding.rbac.authorization.k8s.io/multus created
> serviceaccount/multus created
> configmap/multus-cni-config created
> daemonset.apps/kube-multus-ds-amd64 created
> Warning: resource configmaps/calico-config is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> configmap/calico-config configured
> Warning: resource customresourcedefinitions/felixconfigurations.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/ipamblocks.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/blockaffinities.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/ipamhandles.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/ipamconfigs.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/bgppeers.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/bgpconfigurations.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/ippools.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/hostendpoints.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/clusterinformations.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/globalnetworkpolicies.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/globalnetworksets.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org configured
> Warning: resource customresourcedefinitions/networkpolicies.crd.projectcalico.org is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org configured
> Warning: resource clusterroles/calico-kube-controllers is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> clusterrole.rbac.authorization.k8s.io/calico-kube-controllers configured
> Warning: resource clusterrolebindings/calico-kube-controllers is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers configured
> Warning: resource clusterroles/calico-node is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> clusterrole.rbac.authorization.k8s.io/calico-node configured
> Warning: resource clusterrolebindings/calico-node is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> clusterrolebinding.rbac.authorization.k8s.io/calico-node configured
> Warning: resource daemonsets/calico-node is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> Warning: resource serviceaccounts/calico-node is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> serviceaccount/calico-node configured
> Warning: resource deployments/calico-kube-controllers is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> deployment.apps/calico-kube-controllers configured
> Warning: resource serviceaccounts/calico-kube-controllers is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> serviceaccount/calico-kube-controllers configured
> The DaemonSet "calico-node" is invalid:
> * spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
> * spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"k8s-app":"calico-node", "tier":"node"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by maiqueb** [comment]
Should have tested it before, sorry for that.

Would you please check that [PR](https://github.com/k8snetworkplumbingwg/reference-deployment/pull/11) works for you ? 

I've checked locally in a kind cluster and it managed to install calico nodes / multus:
```
$ cat multus-daemonset.yml calico-daemonset.yml | kubectl apply -f -
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/multus created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/multus created
serviceaccount/multus created
configmap/multus-cni-config created
daemonset.apps/kube-multus-ds-amd64 created
configmap/calico-config created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico-node created
clusterrolebinding.rbac.authorization.k8s.io/calico-node created
daemonset.apps/calico-node created
serviceaccount/calico-node created
deployment.apps/calico-kube-controllers created
serviceaccount/calico-kube-controllers created

.....
$ kubectl get pods -Aw
NAMESPACE            NAME                                        READY   STATUS        RESTARTS   AGE
kube-system          calico-kube-controllers-647b666889-fp4fb    1/1     Running       0          37s
kube-system          calico-node-b97jm                           1/1     Running       0          37s
kube-system          calico-node-hsbxx                           1/1     Running       0          37s
kube-system          calico-node-m9kld                           1/1     Running       0          37s
kube-system          coredns-74ff55c5b-4595g                     1/1     Running       0          19m
kube-system          coredns-74ff55c5b-hc69d                     1/1     Running       0          19m
kube-system          etcd-ovn-control-plane                      1/1     Running       0          19m
kube-system          kube-apiserver-ovn-control-plane            1/1     Running       0          19m
kube-system          kube-controller-manager-ovn-control-plane   1/1     Running       0          19m
kube-system          kube-multus-ds-amd64-4rwth                  1/1     Running       0          38s
kube-system          kube-multus-ds-amd64-4tsvd                  1/1     Running       0          38s
kube-system          kube-multus-ds-amd64-9f275                  1/1     Running       0          38s
kube-system          kube-scheduler-ovn-control-plane            1/1     Running       0          19m
local-path-storage   local-path-provisioner-78776bfc44-5qpwm     1/1     Running       0          19m
...
```

**Comment by haha150** [comment]
Hi,
i am still getting the error:

> 
The DaemonSet "calico-node" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"k8s-app":"calico-node", "tier":"node"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

also what does your calico-daemonset.yml look like?
also the image versions for calico you are using are old?

**Comment by maiqueb** [comment]
> Hi,
> i am still getting the error:
> 
> > 
> 
> The DaemonSet "calico-node" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"k8s-app":"calico-node", "tier":"node"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

The PR I've linked above **removes** the `tier: node` from the match selectors.

If you have an existing deployment, you'll have to remove all calico entities first, and then re provision.

> 
> also what does your calico-daemonset.yml look like?

It looks like [this](https://github.com/k8snetworkplumbingwg/reference-deployment/blob/a55f587d851ca7fa8745ed3b31c8e08f73779be7/multus-calico/calico-daemonset.yml#L475).

> also the image versions for calico you are using are old?

They are indeed, but they work are working on other projects I'm contributing, and that is why I chose those versions vs any other version. 

I would rather bump the images on a separate PR.

**Comment by dougbtv** [comment]
Thank you much for the contributions! We have merged: https://github.com/k8snetworkplumbingwg/reference-deployment/pull/11

Could you give it another try @haha150

**Comment by haha150** [comment]
Hi, 
tried this today and seems to not work for calico 3.19.1

> kubectl describe pod calico-node-85tmr -n kube-system
> 
>   Warning  Failed     4s (x3 over 16s)  kubelet            Error: failed to start container "install-cni": Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/install-cni.sh": stat /install-cni.sh: no such file or directory: unknown

are your changes only 3.12.0 applicable?

**Comment by haha150** [comment]
@maiqueb any suggestion?

**Comment by haha150** [comment]
None of this works with kubernetes v1.23.1.
