### ISSUE TITLE
multiple subnet in macvlan

### ISSUE THREAD

**Issue by mslee89** [k8snetworkplumbingwg/multus-cni#701]
Is it possible to two subnet  in one macvlan file and assign only one IP to pod?
Can I create multiple subnets in one macvlan file and set them to be assigned on the second subnet if the first subnet is not available?

For example, Macvlan settings are shown below
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "em2",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "datadir": "/k8s/test",
        "ranges": [
          [
            {
              "subnet": "1.1.1.0/24",
              "rangeStart": "1.1.1.2",
              "rangeEnd": "1.1.1.3",
              "gateway": "1.1.1.1"
            }
          ]
        ],
        "ranges": [
          [
            {
              "subnet": "2.2.2.0/24",
              "rangeStart": "2.2.2.2",
              "rangeEnd": "2.2.2.3",
              "gateway": "2.2.2.1"
            }
          ]
        ]
      }
    }'
```

The expectations I want are as follows.
1. Two pods are created and these pods are assigned 1.1.1.2 and 1.1.1.3.
2. The pod that is then created is assigned from 2.2.2.0 because there are no IPs that can be assigned to the 1.1.1.0 subnet.

However, the actual behavior is as follows.
- "Datadir" are not working.
- New pods are only allocated from 2.2.2.0.

How can you solve this problem in the same situation as me?

**Comment by s1061123** [comment]
your question seems to be related to CNI reference plugin, not multus because mutus just invokes CNI plugin (macvlan and host-local plugin in your case).

Could you please ask about it to CNI plugin community?
https://github.com/containernetworking/plugins/
