### ISSUE TITLE
networkPlugin cni failed to set up pod "test_default" network

### ISSUE THREAD

**Issue by hgliu1985** [k8snetworkplumbingwg/multus-cni#702]
**I have a virtual machine with two physical net cards ens192 and ens224. I install kubernetes and make it work well. Then I download the multus-cni-master and deploy it on my machine. I create a host-device network-attachment-definition and create a pod based on this network, the pod is alway in the state ContainerCreating. I get some error info from the pod:**

 kubectl describe pod samplepod 
Name:         samplepod
Namespace:    default
Node:         172.26.0.68/172.26.0.68
Start Time:   Thu, 29 Jul 2021 17:03:47 +0800
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: host-devices-1
Status:       Pending
IP:           
IPs:          <none>
Containers:
  samplepod:
    Container ID:  
    Image:         alpine
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/ash
      -c
      trap : TERM INT; sleep infinity & wait
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9gmzl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-9gmzl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9gmzl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                  Age                From                  Message
  ----     ------                  ----               ----                  -------
  Normal   Scheduled               22s                default-scheduler     Successfully assigned default/samplepod to 172.26.0.68
  Normal   AddedInterface          21s                multus                Add eth0 [10.241.0.169/24]
  Warning  FailedCreatePodSandBox  20s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "36881f74f0c6eac94dded4f4487f5bd911c9a2d7fb2bec6086215571adfea3b6" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   AddedInterface          20s                multus                Add eth0 [10.241.0.170/24]
  Warning  FailedCreatePodSandBox  20s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9dd64e2afba8b5158435b31f201a6680b859b6c107cffa99294a49625ab545dd" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   AddedInterface          19s                multus                Add eth0 [10.241.0.171/24]
  Warning  FailedCreatePodSandBox  19s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "5d7b80eb40968448d2ddd53e965ee88215c5e01aa8bd8a233b0f092d4d6b3b07" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Warning  FailedCreatePodSandBox  18s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "258c6508340d9c3cc879178ae916cfa1c02eaee3492e53e78f93dea5329d5a1e" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   AddedInterface          18s                multus                Add eth0 [10.241.0.172/24]
  Normal   AddedInterface          17s                multus                Add eth0 [10.241.0.173/24]
  Warning  FailedCreatePodSandBox  17s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b27818fd23e95476935136c2ab756ec3f9fab99b7911f269312c1c3be6e6ba08" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   AddedInterface          16s                multus                Add eth0 [10.241.0.174/24]
  Warning  FailedCreatePodSandBox  16s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9f3387a3bd49d69422c0e742a4ba96b0061c8b06ffcedb184c0d56b76a85fa3c" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Warning  FailedCreatePodSandBox  15s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ea2849334bd41e67bf2c73b51452d64d42eb2a294fc9a641f7e605cdee5a64f4" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   AddedInterface          15s                multus                Add eth0 [10.241.0.175/24]
  Warning  FailedCreatePodSandBox  14s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d587f4901ac1001fc4fc390a76f4934256dd564e6ec60bf53a09f3bfd4807563" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   AddedInterface          14s                multus                Add eth0 [10.241.0.176/24]
  Normal   AddedInterface          13s                multus                Add eth0 [10.241.0.177/24]
  Warning  FailedCreatePodSandBox  13s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "72698843bd4bb77bb61b50f1a7dc3f059490588794cc7293ab0d13b8c2919e12" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   AddedInterface          12s                multus                Add eth0 [10.241.0.178/24]
  Normal   AddedInterface          11s                multus                Add eth0 [10.241.0.179/24]
  Normal   AddedInterface          10s                multus                Add eth0 [10.241.0.180/24]
  Warning  FailedCreatePodSandBox  9s (x4 over 12s)   kubelet, 172.26.0.68  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "7ded3b27bd9688c4072fda78692f166bf0d356ccf8d914dc0bfbe3a58532946e" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: netplugin failed with no error message
  Normal   SandboxChanged          9s (x12 over 20s)  kubelet, 172.26.0.68  Pod sandbox changed, it will be killed and re-created.
  Normal   AddedInterface          9s                 multus                Add eth0 [10.241.0.181/24]
  Normal   AddedInterface          8s                 multus                Add eth0 [10.241.0.182/24]
  Normal   AddedInterface          7s                 multus                Add eth0 [10.241.0.183/24]
  Normal   AddedInterface          6s                 multus                Add eth0 [10.241.0.184/24]
  Normal   AddedInterface          5s                 multus                Add eth0 [10.241.0.185/24]
  Normal   AddedInterface          4s                 multus                Add eth0 [10.241.0.186/24]
  Normal   AddedInterface          3s                 multus                Add eth0 [10.241.0.187/24]
  Normal   AddedInterface          2s                 multus                Add eth0 [10.241.0.188/24]
  Normal   AddedInterface          1s                 multus                Add eth0 [10.241.0.189/24]

**What you expected to happen**:
I want to get the pod Running and when I run the command "kubectl exec -it samplepod -- ip a ",  there should be two network interfaces in the pod.

**How to reproduce it (as minimally and precisely as possible)**:
1.  cat ./images/multus-daemonset.yml | kubectl apply -f -
2. kubectl create -f host-device.yaml
cat host-device.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-devices-1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "host-device",
    "device": "ens224"
  }'
3. cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: host-devices-1
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
EOF

Then check the pod status:
 kubectl get pods -A
NAMESPACE       NAME                                        READY   STATUS              RESTARTS   AGE
default         samplepod                                   0/1     ContainerCreating   0          9s
ingress-nginx   nginx-ingress-controller-5d444788c5-rdfnl   1/1     Running             1          8d
kube-system     coredns-6c9c57c9d4-bg269                    1/1     Running             1          8d
kube-system     kube-flannel-ds-amd64-s69qx                 1/1     Running             1          8d
kube-system     kube-multus-ds-vzt97                        1/1     Running             0          66m

The pod status is always ContainerCreating.

**Environment**:
uname -a
Linux k8s-master 5.10.36 #1 SMP Wed May 12 02:44:34 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Multus version 
 docker images|grep multus
ghcr.io/k8snetworkplumbingwg/multus-cni                              stable              8acc31ac035f        2 weeks ago         302MB

- Kubernetes version (use `kubectl version`):
 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Primary CNI for Kubernetes cluster:
flannel,multus-cni

- OS (e.g. from /etc/os-release):
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- File of '/etc/cni/net.d/'
 ls /etc/cni/net.d/
00-multus.conf  10-flannel.conflist  multus.d

- File of '/etc/cni/multus/net.d'
no file in the directory /etc/cni/multus/net.d

- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
kubectl get net-attach-def -o yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    creationTimestamp: "2021-07-29T09:02:43Z"
    generation: 1
    managedFields:
    - apiVersion: k8s.cni.cncf.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:config: {}
      manager: kubectl
      operation: Update
      time: "2021-07-29T09:02:43Z"
    name: host-devices-1
    namespace: default
    resourceVersion: "1627163"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/host-devices-1
    uid: 180ec472-d200-4f62-8f2a-6eea57fdcbb3
  spec:
    config: '{ "cniVersion": "0.3.1", "type": "host-device", "device": "ens224" }'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
kubectl get pod samplepod -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: host-devices-1
  creationTimestamp: "2021-07-29T09:38:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:k8s.v1.cni.cncf.io/networks: {}
      f:spec:
        f:containers:
          k:{"name":"samplepod"}:
            .: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl
    operation: Update
    time: "2021-07-29T09:38:15Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2021-07-29T09:38:15Z"
  name: samplepod
  namespace: default
  resourceVersion: "1632202"
  selfLink: /api/v1/namespaces/default/pods/samplepod
  uid: a49d1574-8b03-4ea0-ad46-a8a30b1ab52e
spec:
  containers:
  - command:
    - /bin/ash
    - -c
    - 'trap : TERM INT; sleep infinity & wait'
    image: alpine
    imagePullPolicy: Always
    name: samplepod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9gmzl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 172.26.0.68
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-9gmzl
    secret:
      defaultMode: 420
      secretName: default-token-9gmzl
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T09:38:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T09:38:15Z"
    message: 'containers with unready status: [samplepod]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T09:38:15Z"
    message: 'containers with unready status: [samplepod]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-07-29T09:38:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: alpine
    imageID: ""
    lastState: {}
    name: samplepod
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.26.0.68
  phase: Pending
  qosClass: BestEffort
  startTime: "2021-07-29T09:38:15Z"

- Other log outputs (if you use multus logging)

**Comment by martinkennelly** [comment]
```netplugin failed with no error message``` seems like CNI binary (host-device) didn't even respond with a message. 
I cannot spot any error in your artefacts.

**Comment by hgliu1985** [comment]
@martinkennelly Thanks  a lot for your remind. There was an old multus binary in the directory /opt/kube/bin, after I copy /opt/cni/bin/multus to /opt/kube/bin and restart kubelet service, the test pod is running now.

Now I have a new problem:
There are two network interfaces in my system, ens192 and ens224. The ens192's ip is 172.26.0.68, the ens224's ip is 172.25.0.68.
After the pod is running, there are indeed two network interfaces in the pod as below, but there is no ip address for the second network interface.
kubectl exec -it test -- sh
sh-4.2# ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether da:77:9f:82:24:2c brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.241.0.6/24 scope global eth0
       valid_lft forever preferred_lft forever
4: net1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:0c:29:fa:0f:cb brd ff:ff:ff:ff:ff:ff

I want to set a static ip address for the net1 using the follow yaml,but failed.
cat host-device.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-devices-1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "host-device",
    "device": "ens224",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "172.25.0.68"
        }
      ],
      "routes": [
          { "dst": "0.0.0.0/0" }
      ],
      "gateway":"172.25.0.1"
    }
  }'


After I create a new network-attachment-definition using the host-device.yaml as above, and create a test pod based on this network, the pod can'be running. There is some error when running "kubectl describe pod test":
Events:
  Type     Reason                  Age                From                  Message
  ----     ------                  ----               ----                  -------
  Normal   Scheduled               24s                default-scheduler     Successfully assigned default/test to 172.26.0.68
  Normal   AddedInterface          23s                multus                Add eth0 [10.241.0.109/24] from cbr0
  Warning  FailedCreatePodSandBox  23s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "aa63f160a01f74b644635b23b4888afa07a5879419e9c6c148bd16a8d4c7c4cf" network for pod "test": networkPlugin cni failed to set up pod "test_default" network: [default/test:host-devices-1]: error adding container to network "host-devices-1": invalid CIDR 172.25.0.68: invalid CIDR address: 172.25.0.68, failed to clean up sandbox container "aa63f160a01f74b644635b23b4888afa07a5879419e9c6c148bd16a8d4c7c4cf" network for pod "test": networkPlugin cni failed to teardown pod "test_default" network: delegateDel: error invoking DelegateDel - "host-device": error in getting result from DelNetwork: failed to find "net1": Link not found]
  Normal   AddedInterface          21s                multus                Add eth0 [10.241.0.110/24] from cbr0
  Warning  FailedCreatePodSandBox  21s                kubelet, 172.26.0.68  Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "5b36923fc745f4e9920b9e8e8bdfaab47a377f6cff9d7b1e66f26831f83a12e1" network for pod "test": networkPlugin cni failed to set up pod "test_default" network: [default/test:host-devices-1]: error adding container to network "host-devices-1": invalid CIDR 172.25.0.68: invalid CIDR address: 172.25.0.68, failed to clean up sandbox container "5b36923fc745f4e9920b9e8e8bdfaab47a377f6cff9d7b1e66f26831f83a12e1" network for pod "test": networkPlugin cni failed to teardown pod "test_default" network: delegateDel: error invoking DelegateDel - "host-device": error in getting result from DelNetwork: failed to find "net1": Link not found]


Is there any config error in the host-device.yaml? How to set a static IP for net1 which can ping  successfully on my host?

Thanks.

**Comment by hgliu1985** [comment]
When I set "privileged: true" for the test pod, the pod is running now.
Thanks.

**Comment by martinkennelly** [comment]
This isn't a multus issue, but a configuration issue.

See [IPAM docs](https://www.cni.dev/plugins/current/ipam/static/). Be careful setting the default route to an interface other than the default network interface.

```
If “gw” is omitted, value of “gateway” will be used. 
```
