### ISSUE TITLE
The net1 interface can't be used when host-device type is used in multus-cni

### ISSUE THREAD

**Issue by hgliu1985** [k8snetworkplumbingwg/multus-cni#703]
**Hello, I deploy the multus-cni and create a network-attachment-definition using the following yaml.**
cat host-device.yaml**
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-devices-1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "host-device",
    "device": "ens224",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "172.25.0.68/32",
          "gateway":"172.25.0.1"
      ],
      "routes": [
          { "dst": "0.0.0.0/0" },
          { "dst": "172.0.0.0/8", "gw": "172.25.0.1"}
        }
      ]
    }
  }'

**Then I create a pod based on the network. There are indeed two network interfaces in the pod, but the net1 can't be used. There is no route for net1 interface and can't ping the net1 ip address on the other host.**
# kubectl exec -it testpod -- sh
sh-4.2# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if1828: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether 96:10:63:d6:ae:96 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.241.0.67/24 scope global eth0
       valid_lft forever preferred_lft forever
10: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:0c:29:fa:0f:cb brd ff:ff:ff:ff:ff:ff
    inet 172.25.0.68/32 scope global net1
       valid_lft forever preferred_lft forever
sh-4.2# ip route
default via 10.241.0.1 dev eth0 
10.241.0.0/24 dev eth0  proto kernel  scope link  src 10.241.0.67 
10.241.0.0/16 via 10.241.0.1 dev eth0 
sh-4.2# ip route add 172.0.0.0/8 via 172.25.0.1 dev net1
RTNETLINK answers: Network is unreachable
sh-4.2# ping 172.25.0.1 -I net1
PING 172.25.0.1 (172.25.0.1) from 172.25.0.68 net1: 56(84) bytes of data.
^C
--- 172.25.0.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2031ms

**What you expected to happen**:
There should be route existing for the net1, and I can ping the net1 ip address from other hosts.

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy multus-cni according to the docment https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md
2. create a host-device network
3. create a pod based on the network

**Environment**:
uname -a
Linux k8s-master 5.10.36 #1 SMP Wed May 12 02:44:34 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Multus version 
  image path and image ID (from 'docker images')
docker images|grep multus
ghcr.io/k8snetworkplumbingwg/multus-cni                                             stable              8acc31ac035f        3 weeks ago         302MB

- Kubernetes version (use `kubectl version`):
-kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Primary CNI for Kubernetes cluster:
-flannel, multus
- OS (e.g. from /etc/os-release):
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

- File of '/etc/cni/net.d/'
ls /etc/cni/net.d/
00-multus.conf  10-flannel.conflist  multus.d

- File of '/etc/cni/multus/net.d'
no file
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
kubectl get net-attach-def -o yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"host-devices-1","namespace":"default"},"spec":{"config":"{ \"cniVersion\": \"0.3.1\", \"type\": \"host-device\", \"device\": \"ens224\", \"ipam\": { \"type\": \"static\", \"addresses\": [ { \"address\": \"172.25.0.68/32\", \"gateway\":\"172.25.0.1\" ], \"routes\": [ { \"dst\": \"0.0.0.0/0\" }, { \"dst\": \"172.0.0.0/8\", \"gw\": \"172.25.0.1\"} } ] } }"}}
    creationTimestamp: "2021-07-30T09:46:07Z"
    generation: 1
    managedFields:
    - apiVersion: k8s.cni.cncf.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:config: {}
      manager: kubectl
      operation: Update
      time: "2021-07-30T09:46:07Z"
    name: host-devices-1
    namespace: default
    resourceVersion: "58419"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/host-devices-1
    uid: e8540c02-e4bc-4260-b59f-f34738d94bc4
  spec:
    config: '{ "cniVersion": "0.3.1", "type": "host-device", "device": "ens224", "ipam":
      { "type": "static", "addresses": [ { "address": "172.25.0.68/32", "gateway":"172.25.0.1"
      ], "routes": [ { "dst": "0.0.0.0/0" }, { "dst": "172.0.0.0/8", "gw": "172.25.0.1"}
      } ] } }'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
kubectl get pod haishen-mru-0  -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "10.241.0.67"
          ],
          "mac": "96:10:63:d6:ae:96",
          "default": true,
          "dns": {}
      },{
          "name": "haishen/host-devices-1",
          "interface": "net1",
          "ips": [
              "172.25.0.68"
          ],
          "mac": "00:0c:29:fa:0f:cb",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: host-devices-1
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "10.241.0.67"
          ],
          "mac": "96:10:63:d6:ae:96",
          "default": true,
          "dns": {}
      },{
          "name": "haishen/host-devices-1",
          "interface": "net1",
          "ips": [
              "172.25.0.68"
          ],
          "mac": "00:0c:29:fa:0f:cb",
          "dns": {}
      }]
  creationTimestamp: "2021-07-30T09:46:37Z"
  labels:
    application: mru
.......

Thanks.

**Comment by hgliu1985** [comment]
has fix

**Comment by dougbtv** [comment]
@hgliu1985 do you mind letting us know what fixed it for you?
