### ISSUE TITLE
Is there a possibility to define the default GW entry the CNI SBR plugin includes in the source-based routing table 100?

### ISSUE THREAD

**Issue by richardjudgeman** [k8snetworkplumbingwg/multus-cni#707]
Is it possible to define the default GW the CNI SBR plugin shall include in the source-based routing table (100), e.g. either in the k8s.v1.cni.cncf.io/networks annotation of the K8S pod (preferred) or in the CNI config spec included in the K8S network attachment definition?
```
~ # ip r list table 100
default via 10.1.20.1 dev eth1 <-- this default GW
10.1.20.0/24 dev eth1 scope link  src 10.1.20.201
```
Background: as per issue https://github.com/k8snetworkplumbingwg/multus-cni/issues/706, the SBR plugin does not seem to add the default GW as opposed to the CNI documentation of the CNI plugin.

**Comment by dougbtv** [comment]
This doesn't appear to be supported. 

The SBR plugin assumes that you may run the ip command somewhat manually, for example, via an init container (as a possibility), see also: https://www.cni.dev/plugins/current/meta/sbr/#usage
