### ISSUE TITLE
 failed to set up sandbox container，getPodResources: failed to list pod resources

### ISSUE THREAD

**Issue by silenceper** [k8snetworkplumbingwg/multus-cni#708]
**What happend**:
```
error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: failed to get a ResourceClient instance: getKubeletClient: error ge tting pod resources from client: getPodResources: failed to list pod resources, &{0xc000185180}.Get(_) = _, rpc error: code = Unimplemented desc = unknown service v1.PodResourcesLister
```

**What you expected to happen**:
set pod cni success

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version 
```
ghcr.io/k8snetworkplumbingwg/multus-cni:stable
id:8acc31ac035f
```
- Kubernetes version (use `kubectl version`):
```
v1.18.17
```
- Primary CNI for Kubernetes cluster: flannel
- OS (e.g. from /etc/os-release): 
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by dougbtv** [comment]
Silence, thanks for your report! ...We believe that when we recently upgraded the k8s library code, it uses newer resources than are available in k8s v1.18, as the error indicates objects that were added in k8s v1.20.

Looking at the previous versions, it's likely that v3.7.1 may work: https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v3.7.1

Side note: We may need to upgrade our documentation.

**Comment by silenceper** [comment]
Thank you, I have reverted to using the old version, thank you for your restoration.

**Comment by taoxin2988** [comment]
> Thank you, I have reverted to using the old version, thank you for your restoration.

Hi，I met the same issue with the similar error print as "what happened" above, I would like to know if the v3.7.1 of multus-cni workout . thanks!

**Comment by silenceper** [comment]
My test is ok.

**Comment by taoxin2988** [comment]
> My test is ok.

I tested it successed as well, Thanks so much~
