### ISSUE TITLE
[Question] How can I get the old version multus-cni image?

### ISSUE THREAD

**Issue by chenliu1993** [k8snetworkplumbingwg/multus-cni#709]
Hi team, I see multus are using ghcr.io instead of docker.io to ship multus-cni image. 
But what if I want to use a old version? like 3.7? Can I find it on ghcr.io?
And I notice that stable is the tag used in release, is there a image tag like v3.7, v3.7.1, v3.6 existing? If so, how to get it?
Thanks!

**Comment by dougbtv** [comment]
We'd recommend building your own images and pushing them to a registry.

However, for convenience, you can use the previous dockerhub namespace, you can find the previous version tags here @ https://hub.docker.com/r/nfvpe/multus/tags?page=1&ordering=last_updated
