### ISSUE TITLE
Getting "device or resource busy" error when trying to use examples/macvlan-pod.yml

### ISSUE THREAD

**Issue by nicklesimba** [k8snetworkplumbingwg/multus-cni#715]
**What happened**:
I ran the command `kubectl apply -f macvlan-pod.yml` which resulted in a created pod and network-attachment-definition. The NAD was created successfully. The pod "samplepod" never moved out of **ContainerCreating.**

**What you expected to happen**:
Pod should be running.

**How to reproduce it (as minimally and precisely as possible)**:
Run the command `kubectl apply -f macvlan-pod.yml` and see if the pod changes to running state.
If not, use `kubectl describe` and investigate pod logs.
The following is part of the output of my logs.
```
Warning  FailedCreatePodSandBox  4m34s (x262 over 9m24s)  kubelet            (combined from similar events): Failed to create pod sand
box: rpc error: code = Unknown desc = failed to set up sandbox container "762b42e29073f907b53050b7d4de1596cbc4262c86770785121f5b3795a952
a8" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: [default/samplepod:macvlan-conf]: e
rror adding container to network "macvlan-conf": device or resource busy
```

**Environment**: Centos 7

- Multus version : multus-cni version:master@git, commit:unknown commit, date:unknown date

**Comment by BurlyLuo** [comment]
please share the amplepod:macvlan-conf

**Comment by nicklesimba** [comment]
See multus-cni/examples/macvlan-pod.yml (it includes the NAD yaml)

**Comment by BurlyLuo** [comment]
https://github.com/k8snetworkplumbingwg/multus-cni/blob/ad257698effd425e957bef3069784583f9071501/examples/macvlan-pod.yml#L17

do you have a parant interface named eth0 in your environment?

**Comment by nicklesimba** [comment]
`[centos@kube-miguel nsimha-playground]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:52:ec:b2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.229/24 brd 192.168.122.255 scope global dynamic eth0
       valid_lft 3164sec preferred_lft 3164sec
    inet6 fe80::5054:ff:fe52:ecb2/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:96:ca:86:c7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 4a:70:7c:e4:8d:e0 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.0/32 brd 10.244.0.0 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::4870:7cff:fee4:8de0/64 scope link 
       valid_lft forever preferred_lft forever
5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether fa:51:a6:7a:73:66 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.1/24 brd 10.244.0.255 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::f851:a6ff:fe7a:7366/64 scope link 
       valid_lft forever preferred_lft forever
6: veth8b641dcc@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
    link/ether 86:fe:32:62:3b:21 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::84fe:32ff:fe62:3b21/64 scope link 
       valid_lft forever preferred_lft forever
7: veth0d393a8e@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
    link/ether a6:35:1a:e9:c0:06 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::a435:1aff:fee9:c006/64 scope link 
       valid_lft forever preferred_lft forever
8: veth90c924f5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
    link/ether a2:02:a2:ce:6f:b2 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::a002:a2ff:fece:6fb2/64 scope link 
       valid_lft forever preferred_lft forever`

Sorry for the late response. It appears I do.
