### ISSUE TITLE
Cant't work with secondary interface?

### ISSUE THREAD

**Issue by sunzhaoyang** [k8snetworkplumbingwg/multus-cni#720]
I wish to use multus with "ens33:1" and flannel with "ens33"
```
  Config:  { "cniVersion": "0.3.0", "type": "macvlan", "master": "ens33:1", "mode": "bridge", "ipam": { "type": "host-local", "subnet": "10.1.0.0/16", "rangeStart": "10.1.0.10", "rangeEnd": "10.1.0.100", "routes": [ { "dst": "0.0.0.0/0" } ], "gateway": "10.1.0.1" } }
```

got errors like this
```
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               3m52s                default-scheduler  Successfully assigned default/clash to k8s
  Normal   AddedInterface          3m52s                multus             Add eth0 [10.244.0.37/24] from cbr0
  Warning  FailedCreatePodSandBox  3m52s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "bb41f667024ac54420ae2c931bfa443f0c8b44d3f60800bb5f2e19c55ff10883" network for pod "clash": networkPlugin cni failed to set up pod "clash_default" network: [default/clash:macvlan-conf]: error adding container to network "macvlan-conf": Link not found, failed to clean up sandbox container "bb41f667024ac54420ae2c931bfa443f0c8b44d3f60800bb5f2e19c55ff10883" network for pod "clash": networkPlugin cni failed to teardown pod "clash_default" network: delegateDel: error invoking DelegateDel - "macvlan": error in getting result from DelNetwork: Link not found]
  Normal   SandboxChanged          5s (x19 over 3m51s)  kubelet            Pod sandbox changed, it will be killed and re-created.
```

messages
```
Sep  4 11:31:26 k8s kubelet: I0904 11:31:26.175135    1145 cni.go:333] "CNI failed to retrieve network namespace path" err="cannot find network namespace for the terminated container \"1c92a2d2e2e85aeb21e91bcf732d262255bbd641b6f3944afce7af624a26f7af\""
Sep  4 11:31:26 k8s kubelet: E0904 11:31:26.251548    1145 cni.go:380] "Error deleting pod from network" err="delegateDel: error invoking DelegateDel - \"macvlan\": error in getting result from DelNetwork: Link not found" pod="default/clash" podSandboxID={Type:docker ID:1c92a2d2e2e85aeb21e91bcf732d262255bbd641b6f3944afce7af624a26f7af} podNetnsPath="" networkType="multus" networkName="multus-cni-network"
Sep  4 11:31:26 k8s kubelet: E0904 11:31:26.252463    1145 remote_runtime.go:144] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"clash_default\" network: delegateDel: error invoking DelegateDel - \"macvlan\": error in getting result from DelNetwork: Link not found" podSandboxID="1c92a2d2e2e85aeb21e91bcf732d262255bbd641b6f3944afce7af624a26f7af"
Sep  4 11:31:26 k8s kubelet: E0904 11:31:26.252507    1145 kuberuntime_gc.go:176] "Failed to stop sandbox before removing" err="rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"clash_default\" network: delegateDel: error invoking DelegateDel - \"macvlan\": error in getting result from DelNetwork: Link not found" sandboxID="1c92a2d2e2e85aeb21e91bcf732d262255bbd641b6f3944afce7af624a26f7af"
Sep  4 11:31:38 k8s systemd: prometheus-9090.service holdoff time over, scheduling restart.
```

**Comment by szgRunner** [comment]
vm server ?

**Comment by dougbtv** [comment]
Looks like macvlan CNI plugin isn't seeing the interface named `ens33:1`. 

For macvlan the "master" interface must exist in advance. It's plausible you may be able to create `ens33:1`, however, typically you'd use an existing interface.

During maintainer's meeting we also noted that the error message from macvlan CNI is not very actionable, it doesn't help much, so we're looking into filing an issue / fix against the reference CNI plugins for macvlan.

**Comment by maiqueb** [comment]
> Looks like macvlan CNI plugin isn't seeing the interface named `ens33:1`.
> 
> For macvlan the "master" interface must exist in advance. It's plausible you may be able to create `ens33:1`, however, typically you'd use an existing interface.

Right; the `master` attribute specifies the lower device on which the macvlan is created, **not** the new interface: https://www.cni.dev/plugins/current/main/macvlan/#network-configuration-reference
> 
> During maintainer's meeting we also noted that the error message from macvlan CNI is not very actionable, it doesn't help much, so we're looking into filing an issue / fix against the reference CNI plugins for macvlan.

I think you can actually do what you're after - with a twist. 

Try the following NAD (basically yours, but using the existing lower device - `ens33`:

```json
  Config:  { "cniVersion": "0.3.0", "type": "macvlan", "master": "ens33", "mode": "bridge", "ipam": { "type": "host-local", "subnet": "10.1.0.0/16", "rangeStart": "10.1.0.10", "rangeEnd": "10.1.0.100", "routes": [ { "dst": "0.0.0.0/0" } ], "gateway": "10.1.0.1" } }
```

And on your pod spec, specify the desired interface name in the networks annotation, as per the [multus documentation](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/how-to-use.md#launch-pod-with-text-annotation-with-interface-name):
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-03
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf-1@ens331
spec:
  containers:
  - name: pod-case-03
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
```

Unfortunately, I don't think you can use the colon - `:` - in the interface name. When I tried it on my lab (which is using an old version of multus) I got the following error:
`default              2m25s       Warning   FailedCreatePodSandBox    pod/pod-case-03                                Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "77ff1e496bcf65cb291cf8eef61762f0733e554df5c4e6e0e47b23755d78971d": Multus: [default/pod-case-03]: error loading k8s delegates k8s args: parsePodNetworkAnnotation: parsePodNetworkObjectName: Failed to parse: one or more items did not match comma-delimited format (must consist of lower case alphanumeric characters). Must start and end with an alphanumeric character), mismatch @ 'ens33:1'`
