### ISSUE TITLE
Support for NodePort service on secondary POD interfaces

### ISSUE THREAD

**Issue by lsoica** [k8snetworkplumbingwg/multus-cni#727]
Hi,

I am trying to setup two k8s clusters where pods are attached on two different networks. One for intra-cluster communication and another one for inter-cluster communication and for accessing the pods from the outside world. 

The only option I have for making services externally accessible is through NodePort, like in this diagram:

![image](https://user-images.githubusercontent.com/1623282/134352640-8816a1b8-bbaf-47b2-bea4-59fdf36b759d.png)

The question is, can I have NodePort services on POD interfaces other than default one ?

**Comment by s1061123** [comment]
Multus cni does not support NodePort to secondary interfaces.

**Comment by lsoica** [comment]
Are you aware of any other way to achieve this use case considering that I only have one IP available per cluster node per network ?

Thanks!

**Comment by s1061123** [comment]
No I don't have such idea yet.
