### ISSUE TITLE
Change cni version to 0.4.0

### ISSUE THREAD

**Issue by s1061123** [k8snetworkplumbingwg/multus-cni#738]
Currently we use 0.3.1 CNI version but we could change it to 0.4.0 because Kubernetes 1.20 and later support it.

https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml#L176
https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset-crio.yml#L176

**Comment by dunaparty** [comment]
We really need to support 0.4.0 (which introduces `prevResult` on DEL), otherwise `whereabouts` and `host-local` IPAM cannot release its IPs if plugin structured NAD is being used.
See: https://github.com/k8snetworkplumbingwg/whereabouts/issues/102

**Comment by s1061123** [comment]
@dunaparty Currently multus CNI binary supports CNI 0.4.0. If you want to use it, please change I mentioned above.

https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml#L176
https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset-crio.yml#L176

**Comment by cyclinder** [comment]
so should we change the cni version to 0.4.0?
