### ISSUE TITLE
Failed to create pod suddenly 

### ISSUE THREAD

**Issue by liyimeng** [k8snetworkplumbingwg/multus-cni#743]
**What happend**:
Suddenly, no pod can be created, error reports 

```
 Normal   Scheduled               32s   default-scheduler  Successfully assigned drone/drone-5c955bf8fd-lg5gg to master0
  Warning  FailedCreatePodSandBox  32s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "60a7cbd94184581492ab1b6c85c6d61d8d4480252d6b59b942b6bf64da4adf75": Multus: [drone/drone-5c955bf8fd-lg5gg]: error getting pod: Get https://[10.53.0.1]:443/api/v1/namespaces/drone/pods/drone-5c955bf8fd-lg5gg?timeout=1m0s: x509: certificate signed by unknown authority
  Warning  FailedCreatePodSandBox  17s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "79e84f9c12243034e0795e4b0825cf37d88ad701096a2310c50ac03bedb4664b": Multus: [drone/drone-5c955bf8fd-lg5gg]: error getting pod: Get https://[10.53.0.1]:443/api/v1/namespaces/drone/pods/drone-5c955bf8fd-lg5gg?timeout=1m0s: x509: certificate signed by unknown authority
  Warning  FailedCreatePodSandBox  6s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "b80846f9603ffcab49bf79ddbdfba855d6e651ece435b9d45a985c6279728d13": Multus: [drone/drone-5c955bf8fd-lg5gg]: error getting pod: Get https://[10.53.0.1]:443/api/v1/namespaces/drone/pods/drone-5c955bf8fd-lg5gg?timeout=1m0s: x509: certificate signed by unknown authority

```

while kubectl works OK, which indicates the cluster still have good certs, but somewhere multus dose not believe so. 

**What you expected to happen**:

Pod created, multus create pod ip as expected. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version: stable 
  image path and image ID (from 'docker images'). 
- Kubernetes version (use `kubectl version`): 1.21
- Primary CNI for Kubernetes cluster: flannel 
- OS (e.g. from /etc/os-release): ubuntu 
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by liyimeng** [comment]
@dougbtv Thanks a lot! It seems the case. Thanks for helping out, but how this can happen? Can it be a bug? should be pickup the change automatically?

**Comment by liyimeng** [comment]
This happen again after I upgrade my k8s, this time restart Daemonset is no help.

**Comment by liyimeng** [comment]
@dougbtv How Multus talk to api server? dose it use in cluster service account?

**Comment by jansmets** [comment]
I'm having the same problem on a freshly kubeadm-bootstrapped k8s 1.24
