### ISSUE TITLE
Use which interface name as master parameter in  network attachment definition if the hosts have different interface names

### ISSUE THREAD

**Issue by Ezi4Zy** [k8snetworkplumbingwg/multus-cni#744]
host1 interface name is eth1
host2 interface name is eth2
use which interface name as master  parameter in  network attachment definition?

**Comment by Ezi4Zy** [comment]
Thank you @dougbtv

**Comment by crutonjohn** [comment]
for future travelers, this might help:

https://www.shellhacks.com/change-network-interface-name-eth0-eth1-eth2/

essentially you can use udev rules to enforce a specific name.
