### ISSUE TITLE
Multus is adding additional default gw in main routing table in case of IPV6

### ISSUE THREAD

**Issue by SabirHussain87** [k8snetworkplumbingwg/multus-cni#749]
**What happened**:
Multus is adding additional default gateway along with other routes. So the main routing table ends up with 2 default gateway. 
Here is my sample Network Attachment Definition:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-v6
spec:
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "ipvlan",
                    "capabilities": { "ips": true },
                    "master": "eth2",
                    "ipam": {
                      "type": "host-local",
                      "rangeStart": "fd5d:d50a:8c17:2030::1d1",
                      "rangeEnd": "fd5d:d50a:8c17:2030::1df",
                      "subnet": "fd5d:d50a:8c17:2030::/64",
                      "gateway": "fd5d:d50a:8c17:2030::ff",
                      "routes": [
                        { "dst": "fd5d:d50a:8c17:2040::/64", "gw": "fd5d:d50a:8c17:2030::ff" }
                      ]
                    }
                }
            ]
        }'
```

Here is the routing table inside the pod:

```
[root@test6 /]# ip -6 route show
1100::5486:2d90:6847:2ee5:550d dev eth0 proto kernel metric 256 pref medium
fd5d:d50a:8c17:2030::/64 dev net1 proto kernel metric 256 pref medium
fd5d:d50a:8c17:2040::/64 via fd5d:d50a:8c17:2030::ff dev net1 metric 1024 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev net1 proto kernel metric 256 pref medium
default via fe80::ecee:eeff:feee:eeee dev eth0 metric 1024 pref medium
default via fe80::822d:bfff:feb8:cf27 dev net1 proto ra metric 1024 expires 1664sec hoplimit 64 pref medium
```

You can see there are two default gateways one through eth0 and another one added by Multus through net1. I am also not sure about  fe80::822d:bfff:feb8:cf27, from where this gateway ip is picked. 

**What you expected to happen**:
Multus should not add another default gateway. It does not do, if all ips are IPV4.
**How to reproduce it (as minimally and precisely as possible)**:
Create a NetworkAttachmentDefinition with all IPV6. Use multus to add interface from this created NetworkAttachmentDefinition.

**Anything else we need to know?**:

**Environment**:

- Multus version : nfvpe/multus:stable
  image path and image ID (from 'docker images') : 0a68c2549d96
- Kubernetes version (use `kubectl version`):: 1.21.1
- Primary CNI for Kubernetes cluster: Calico
- OS (e.g. from /etc/os-release): Centos 7
- File of '/etc/cni/net.d/': 
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"ipvlan-v6","namespace":"sabir"},"spec":{"config":"{ \"cniVersion\": \"0.3.1\", \"plugins\": [ { \"type\": \"ipvlan\", \"capabilities\": { \"ips\": true }, \"master\": \"eth2\", \"ipam\": { \"type\": \"host-local\", \"rangeStart\": \"fd5d:d50a:8c17:2030::1d1\", \"rangeEnd\": \"fd5d:d50a:8c17:2030::1df\", \"subnet\": \"fd5d:d50a:8c17:2030::/64\", \"gateway\": \"fd5d:d50a:8c17:2030::ff\", \"routes\": [ { \"dst\": \"fd5d:d50a:8c17:2040::/64\", \"gw\": \"fd5d:d50a:8c17:2030::ff\" } ] } } ] }"}}
  creationTimestamp: "2021-10-20T06:15:05Z"
  generation: 14
  name: ipvlan-v6
  namespace: sabir
[net.d.tar.gz](https://github.com/k8snetworkplumbingwg/multus-cni/files/7459608/net.d.tar.gz)

  resourceVersion: "96758675"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/sabir/network-attachment-definitions/ipvlan-v6
  uid: fdbd8005-e785-48df-abd8-e6f8e786af03
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities":
    { "ips": true }, "master": "eth2", "ipam": { "type": "host-local", "rangeStart":
    "fd5d:d50a:8c17:2030::1d1", "rangeEnd": "fd5d:d50a:8c17:2030::1df", "subnet":
    "fd5d:d50a:8c17:2030::/64", "gateway": "fd5d:d50a:8c17:2030::ff", "routes": [
    { "dst": "fd5d:d50a:8c17:2040::/64", "gw": "fd5d:d50a:8c17:2030::ff" } ] } } ]
    }'
```

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)

Attached as file

- Other log outputs (if you use multus logging
[info.net-attach-def.yaml.txt](https://github.com/k8snetworkplumbingwg/multus-cni/files/7459618/info.net-attach-def.yaml.txt)
[info.pod.yaml.txt](https://github.com/k8snetworkplumbingwg/multus-cni/files/7459619/info.pod.yaml.txt)
)

**Comment by nicklesimba** [comment]
The second default gateway is due to `proto ra` which indicates router advertisement. 

https://www.cisco.com/assets/sol/sb/RV320_Emulators/RV320_Emulator_v1.0.1.01/help/DHCP7.html
This seems like a useful link..

**Comment by SabirHussain87** [comment]
How to disable autoconfig in this case? On my host where the pod is running, autoconfig is disabled, this sysctl parameter is set to 0. net.ipv6.conf.all.autoconf=0
Now how to disable autoconfig through multus so that multus sets the gateway present in the Network attachment difination?
I am running in the dual stack K8s setup which needs net.ipv6.conf.all.forwarding=1 on the host.

**Comment by mzeeshan1** [comment]
I am facing exactly the same issue. @SabirHussain87 did you find any solution for it.  The routing table inside the pod for me looks like:

`2001:920:1868:800::/64 dev net1  metric 256 
fd00:42::d:e9c8 dev eth0  metric 256 
fe80::/64 dev eth0  metric 256 
fe80::/64 dev net1  metric 256 
default via fe80::ecee:eeff:feee:eeee dev eth0  metric 1024 
default via fe80::464e:6dff:fe77:15d6 dev net1  metric 1024  expires 0sec
multicast ff00::/8 dev eth0  metric 256 
multicast ff00::/8 dev net1  metric 256 `

And I am also not sure where fe80::464e:6dff:fe77:15d6 this address is coming from. But it is causing the connectivity within the cluster to break for this pod. Also, i do not have proto ra field available in the routing table.

**Comment by dougbtv** [comment]
> How to disable autoconfig in this case? On my host where the pod is running, autoconfig is disabled, this sysctl parameter is set to 0. net.ipv6.conf.all.autoconf=0

I realize that's on the host -- but can you check inside the pod? You might also want to look into the tuning CNI

**Comment by SabirHussain87** [comment]
> I am facing exactly the same issue. @SabirHussain87 did you find any solution for it. The routing table inside the pod for me looks like:
> 
> `2001:920:1868:800::/64 dev net1 metric 256
> 
> fd00:42::d:e9c8 dev eth0 metric 256
> 
> fe80::/64 dev eth0 metric 256
> 
> fe80::/64 dev net1 metric 256
> 
> default via fe80::ecee:eeff:feee:eeee dev eth0 metric 1024
> 
> default via fe80::464e:6dff:fe77:15d6 dev net1 metric 1024 expires 0sec
> 
> multicast ff00::/8 dev eth0 metric 256
> 
> multicast ff00::/8 dev net1 metric 256 `
> 
> And I am also not sure where fe80::464e:6dff:fe77:15d6 this address is coming from. But it is causing the connectivity within the cluster to break for this pod. Also, i do not have proto ra field available in the routing table.

Not yet. I have not found a way to disable autoconfig.

**Comment by SabirHussain87** [comment]
> Tuning plugin solved the issue for me

Can you please let me know, how did you do that?

**Comment by mzeeshan1** [comment]
here is yaml i defined in network attachment definition

`        {
           "type": "tuning",
           "sysctl": {
              "net.ipv6.conf.net1.autoconf": 0
         }
        }`

you can read up on it here https://www.cni.dev/plugins/v0.8/meta/tuning/

**Comment by SabirHussain87** [comment]
@mzeeshan1  looks good. Thanks.
