### ISSUE TITLE
How to deal with multus-cni start order 

### ISSUE THREAD

**Issue by JornShen** [k8snetworkplumbingwg/multus-cni#766]
Many User use multus-cni will face one problem which my app start before the multus.

Support that I have a deployment using multi network interface, 
now I have no enough resouces, and Need to extend a new node. 
And all the cni will start with this deployment Pod, if one of multus-cni CNI Plugin like Flannel start before the Multus-cni, 
And Pod will start success, But Pod will not have multi eth，
Because CNI Plugin like Flannel will not know about the annotation of multus-cni.

**Comment by JornShen** [comment]
@maiqueb @s1061123

**Comment by s1061123** [comment]
To use multus cni, you need to install the multus. This is one important requirement. We don't change the requirement.
If you want to use similar functionality of multus, you need to add the functionality not in multus, something else.

Please ask the component you want to have the functionalities. We cannot do nothing before install.

**Comment by JornShen** [comment]
> 

@s1061123 I know that we use it after it install,But I am focused on the scene that we extend the node. It is also important scene. So you mean you dont consider this scene ?

**Comment by s1061123** [comment]
Start order is maintained by Kubernetes, not multus. We don't have a way to change the order.
If we have a way to do that, then we could do what you want, but for now, as far as I know of, there is no way to do that.
Please let me know if you have a way to do that.

**Comment by andrein** [comment]
@JornShen you might want to take a look at https://github.com/kubernetes/kubernetes/issues/75890#issuecomment-725792993 for a possible solution.
