### ISSUE TITLE
[Question] Multus support on AWS

### ISSUE THREAD

**Issue by boeboe** [k8snetworkplumbingwg/multus-cni#767]
Hi all,

I am trying to get Multus CNI working on AWS, as preliminary support was announced recently [here](https://docs.aws.amazon.com/eks/latest/userguide/pod-multiple-network-interfaces.html).

However, only when traffic remains on a local node, it seems to be working. Whenever secondary interface/subnet traffic is crossing the node boundary, traffic seems to be dropped on those links. Do you have any idea why?

I tried with several combinations of CNIs:
 - Calico + Multus
 - Aws-VPC-CNI + Multus
All works well as long as POD's are scheduled on the same node, but as soon as they are scheduled on different nodes. the traffic does not arrive at the target node.

    POD1 => Node1 ==(this is where the traffic is not arriving at node2)==> Node2 => POD2
     => Ping to node1 IP: OK
     => Ping to node2 IP: OK
     => Ping to POD2 secondary IP: NOK (ICMP requests for POD2_IP2 are never responded and also not arriving on Node2 (tcpdump verified)

I also tried with ipvlan (l2, l3), macvlan (bridge)... my guess is that the MAC addresses are not discovered/reachable on the secondary subnet. I tried to resolve this by also switching to aws-vpc-cni on this interfaces, but then my PODs get random primary ClusterIP addresses inside k8s (some will get primary subnet IPs, others secondary IPs).

I assume that Multus support is still under development. Where can I follow up on the progress and roadmap thereof?

Kind regards,
Bart

The issue seems very similar to the one reported here: 
https://github.com/k8snetworkplumbingwg/multus-cni/issues/390

I have also asked for some clarity on the AWS repo here:
https://github.com/aws-samples/eks-install-guide-for-multus/issues/7#issuecomment-994274130

**Comment by boeboe** [comment]
**Update:**

 I found the answer I was looking for at https://github.com/aws-samples/eks-automated-ipmgmt-multus-pods

**Comment by boeboe** [comment]
Note that there was one more thing that I was doing wrong before everything worked. Since I am using self hosted ubuntu machines with self managed `kubeadm` to bootstrap my whole `multus` cluster on AWS, I had to manually enable IP FWing, which was one of the reasons traffic was not getting across.

    # Allow IP Forwarding
    echo "[Terraform Cloud Init] Allow IP Forwarding"
    sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
    sed -i 's/#net.ipv4.conf.all.rp_filter=1/net.ipv4.conf.all.rp_filter=2/g' /etc/sysctl.conf
    
    
The output of this `multus` experiment with `aws-cni` is summarized on the following Terraform module I am working on currently (WIP): https://github.com/boeboe/terraform-aws-k8s-multus-gtp5g

For some reason, this was not necessary with `calico-cni` (without `aws-cni`) so I am assuming `calico-cni` does this out of the box for you.

**Comment by s1061123** [comment]
AWS supports multus, however, multus does not support multus officially. Please ask AWS team (as you submit to AWS repo) for troubleshooting.
