### ISSUE TITLE
Are there any examples of VLAN interface

### ISSUE THREAD

**Issue by haha150** [k8snetworkplumbingwg/multus-cni#769]
Hi,

I want to create an interface for my pod where the interface sits on a subnet with say VLAN 10 and this traffic shall be routed out towards a physical interface/NIC on the server, which is connected to a switch.

Do you have any examples of creating VLAN interface?

**Comment by dougbtv** [comment]
I'd take a look into using Bridge CNI.

It has vlan capabilities: https://www.cni.dev/plugins/v0.7/main/bridge/#network-configuration-reference

**Comment by RandomGHUser** [comment]
I set up my VLAN interfaces directly on the host, and then have multus use the corresponding VLAN interfaces.  You will need to also have your switch/router configured to pass/trunk these VLANs to your host for proper subnet tagging/routing.

If this is what you would like to try, and your host is a Debian variant, you can install bridge-utils, and then set up your /etc/network/interfaces to correspond to your vlans.  Basic example below:
```sh
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug enp4s0
iface enp4s0 inet manual

auto enp4s0.1
iface enp4s0.1 inet manual 
vlan-raw-device enp4s0

auto enp4s0.66
iface enp4s0.66 inet manual
vlan-raw-device enp4s0

auto enp4s0.5
iface enp4s0.5 inet manual
vlan-raw-device enp4s0

auto vlan1
iface vlan1 inet static
        bridge_ports enp4s0.1
        address 192.168.0.5
        netmask 255.255.255.0
        gateway 192.168.0.1

auto vlan5-iot
iface vlan5-iot inet manual
        bridge_ports enp4s0.5

auto vlan66-dmz 
iface vlan66-dmz inet manual
        bridge_ports enp4s0.66

**Comment by hunhoffe** [comment]
Hello! I have looked through the bridge documentation but I would also find an example very helpful. Does anyone have one they would be willing to share?

**Comment by willzhang** [comment]
> Hello! I have looked through the bridge documentation but I would also find an example very helpful. Does anyone have one they would be willing to share?

but bridge cni can not choose host nic
