### ISSUE TITLE
Multus doesn't support Kubernetes 1.21 or later (PodDevicesEntry.Data.PodDeviceEntries.DeviceIDs type has changed)

### ISSUE THREAD

**Issue by gmaquinay** [k8snetworkplumbingwg/multus-cni#778]
I've faced a problem, deploying multus with Kubernetes 1.21.
Checkpoint structure changed in Kube since commit a8b8995ef241e93e9486d475126450f33f24ef4e (2020 July 14th):
```
+// DevicesPerNUMA represents device ids obtained from device plugin per NUMA node id
+type DevicesPerNUMA map[int64][]string
+
 // PodDevicesEntry connects pod information to devices
 type PodDevicesEntry struct {
        PodUID        string
        ContainerName string
        ResourceName  string
-       DeviceIDs     []string
+       DeviceIDs     DevicesPerNUMA
        AllocResp     []byte
 }
```
DeviceIDs is not any more a slice of strings but its now a map:
```
// DevicesPerNUMA represents device ids obtained from device plugin per NUMA node id
type DevicesPerNUMA map[int64][]string
```

Thus, multus is not any more able to read `/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint` and fails to provision requested network interfaces.

Is there a proper way to work around this? If not, I can propose a fix.
Please let me know.

Thx

**Comment by zshi-redhat** [comment]
> 
> Thus, multus is not any more able to read `/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint` and fails to provision requested network interfaces.
> 
> Is there a proper way to work around this? If not, I can propose a fix. Please let me know.

Did you try the kubelet API endpoint[1] path (default option) to get device ID? 
[1] https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/pkg/kubeletclient/kubeletclient.go#L31

I agree that the checkpoint file structure needs to be fixed in multus-cni.

**Comment by s1061123** [comment]
Hi @gmaquinay thank you for the issue and offer to fix. Could you please propose this fix to us? I appreciate your help!

To work around the issue, you can use kubelet API endpoint as @zshi-redhat mentioned. Currently multus-cni and sr-iov device plugin prefers to use kubelet API endpoint to pass the device ID and checkpoint is the fallback method. So we recommend to enable  kubelet API endpoint to use multus-cni and sr-iov device plugin.
