### ISSUE TITLE
Network Policy Support

### ISSUE THREAD

**Issue by ggkunka** [k8snetworkplumbingwg/multus-cni#780]
We are checking if multus cni supports network policies. If yes, how can it be configured? Any kind of documentation link will be helpful.

**Comment by s1061123** [comment]
We defined https://github.com/k8snetworkplumbingwg/multi-networkpolicy as Kube CRD for network policy object of multi interface and provide iptables based implementation https://github.com/k8snetworkplumbingwg/multi-networkpolicy-iptables

Feedback is welcome!
