### ISSUE TITLE
Support more architectures for new thick image variant

### ISSUE THREAD

**Issue by stv0g** [k8snetworkplumbingwg/multus-cni#781]
The new think image is only available for the amd64 architecture.

We should update the CI to build it for other architectures as well

**Comment by dougbtv** [comment]
Good eye. The image that we tag as `:thick` is only built for one architecture, and we have it as the default installation method in the quickstart guide.

Maybe we should expand this?

...Also of note the name "thick" can be misleading. There's also discussion and forward progress for Multus architecture to add a mode for what we call a "thick plugin" (where some portion of the application runs as a daemon). 

The `:thick` variant implements a new entrypoint script, and is in anticipation of a thick plugin mode, but, the thick plugin changes are still pending.
