### ISSUE TITLE
DHCP plugin override the default route

### ISSUE THREAD

**Issue by MaxThom** [k8snetworkplumbingwg/multus-cni#786]
Hi,

I have setup up a macvlan with dhcp with multuscni in our k8s clusters.
Pods receives the ip address from the dhcp and the container is starting normally. The problem is the dhcp add a second default route in the ip tables. This blocks all internet connection because the now default route is the wrong one.
How can I configure multus or the dhcp daemon to not add a second route ?

![image](https://user-images.githubusercontent.com/26239574/152885777-3d4f464c-4323-43d3-ba54-33d6135b48bb.png)

<details>
  <summary>Multus config</summary>

```json
{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "name": "sw-lan",
    "master": "eno1",
    "mode": "bridge",
    "ipam": {
        "type": "dhcp"
    }
}
```
</details>

<details>
  <summary>DHCP Plugin daemon</summary>
 
```sh
[Unit]
Description=DHCP Client for CNI

[Socket]
ListenStream=/run/cni/dhcp.sock
SocketMode=0660
SocketUser=root
SocketGroup=root
RemoveOnStop=true

[Install]
WantedBy=sockets.target
```

```sh
[Unit]
Description=DHCP Client CNI Service
Requires=multus.dhcp.socket
After=network.target multus.dhcp.socket

[Service]
Type=simple
ExecStart=/var/lib/rancher/k3s/data/current/bin/dhcp daemon
TimeoutStopSec=30
KillMode=process

[Install]
WantedBy=multi-user.target
Also=multus.dhcp.socket
```
</details>

<details>
<summary>Annotation on the pods</summary>

```yaml
annotations:
    k8s.v1.cni.cncf.io/networks: networking/sw-lan@sw0
```
</details>

**Comment by s1061123** [comment]
@MaxThom sorry for reply late. As I noted in https://github.com/containernetworking/plugins/pull/701, If you just want to remove only default route, we have [cni-route-override](https://github.com/redhat-nfvpe/cni-route-override), which modify the CNI plugins' routing table information. This plugin also has flushgateay so you can use it with this option, it may be solved.
