### ISSUE TITLE
Mutus CNI DHCP for addtional network attachment

### ISSUE THREAD

**Issue by pkamaraj** [k8snetworkplumbingwg/multus-cni#787]
Hi, 
We have created the below config as addtional network configuration: 
➜  /tmp cat addNic.yaml 
spec:
  additionalNetworks:
  - name: simple-macvlan
    namespace: sample
    type: SimpleMacvlan
    simpleMacvlanConfig:
      mode: bridge
      master: ens161
      ipamConfig:
        type: dhcp
➜  /tmp 

Patch the contents of the file to the network.operator cluster object, i.e oc patch network.operator cluster --patch "$(cat addNic.yaml)" --type=merge
After patching, a new NetworkAttachmentDefinition will be created automatically of the name simple-macvlan.
Once its attached to the cluster, the pod refers to the simple-macvlan for one of the interface and in the pod shell it has net1 interface created (multus CNI ) 
Use simple-macvlan in the annotation for POD deployment instead of previous NetworkAttachmentDefinition for POD mgmt

The above approach we have 2 ip address assigned even with same MAC address for one interface .. 
The DHCP IP assigned for net1 interface another one from the POD interface.  How do avoid DHCP address assignment on net1 interfaces ? 
Does this expected behavior ?  Please share your thoughts. 

Thanks,
Kamaraj

**Comment by s1061123** [comment]
Thank you for the issue. Could you please provide us about following output?

- kubectl -n sample get net-attach-def -o yaml
- kubectl -n sample get pod -o yaml

**Comment by pkamaraj** [comment]
PodManifest.yaml
===========================
apiVersion: v1
kind: Pod
metadata:
  name: sfcn-default-enforcer-6d6554b6b-qkcz4
  generateName: sfcn-default-enforcer-6d6554b6b-
  namespace: sfcn-system
  uid: 2d9d4af2-84dd-4870-bfc9-e4f0eded117e
  resourceVersion: '4039236'
  creationTimestamp: '2022-02-23T04:34:32Z'
  labels:
    app.kubernetes.io/component: enforcer
    app.kubernetes.io/instance: sfcn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cnfw
    app.kubernetes.io/version: v0.0.0-pr-2063-B
    helm.sh/chart: cnfw-v0.0.0-pr-2063-B
    pod-template-hash: 6d6554b6b
    sfcn.cisco.com/enforcement-point: ASA
    sfcn.cisco.com/role: default-enforcer
    sfcn.cisco.com/service-role: default
    tenant-namespace.sfcn.cisco.com/sfcn-system: 'true'
  annotations:
    checksum/asac-plat-limits: e2f70800150e64b385b93a3c5bf6d5e74895a1e3875797836e0f5cf7a436d4d5
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.254.4.152"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "sfcn-system/simple-macvlan",
          "interface": "net1",
          "ips": [
              "10.10.3.99"
          ],
          "mac": "ea:09:d2:25:a4:b1",
          "dns": {}
      },{
          "name": "sfcn-system/oc-multus-gig0",
          "interface": "net2",
          "mac": "00:50:56:81:23:46",
          "dns": {}
      },{
          "name": "sfcn-system/oc-multus-gig1",
          "interface": "net3",
          "mac": "00:50:56:81:2f:2f",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: simple-macvlan, oc-multus-gig0, oc-multus-gig1
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.254.4.152"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "sfcn-system/simple-macvlan",
          "interface": "net1",
          "ips": [
              "10.10.3.99"
          ],
          "mac": "ea:09:d2:25:a4:b1",
          "dns": {}
      },{
          "name": "sfcn-system/oc-multus-gig0",
          "interface": "net2",
          "mac": "00:50:56:81:23:46",
          "dns": {}
      },{
          "name": "sfcn-system/oc-multus-gig1",
          "interface": "net3",
          "mac": "00:50:56:81:2f:2f",
          "dns": {}
      }]
    openshift.io/scc: privileged
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    sfcn.cisco.com/attach-interfaces: '3'
    sfcn.cisco.com/attach-public-ip: outside
    sfcn.cisco.com/interface-subnet: mgmt,outside,inside
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: sfcn-default-enforcer-6d6554b6b
      uid: 82220d40-030b-40d5-9eb1-0daf17e730d3
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-02-23T04:34:32Z'
      fieldsType: FieldsV1
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2022-02-23T04:34:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:k8s.v1.cni.cncf.io/network-status: {}
            f:k8s.v1.cni.cncf.io/networks-status: {}
      subresource: status
    - manager: manager
      operation: Update
      apiVersion: v1
      time: '2022-02-23T04:34:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"Protected"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-02-23T04:35:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.254.4.152"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
status:
  phase: Running
  conditions:
    - type: Protected
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-02-23T04:34:51Z'
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-02-23T04:34:35Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-02-23T04:35:25Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-02-23T04:35:25Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-02-23T04:34:32Z'
  hostIP: 10.10.3.15
  podIP: 10.254.4.152
  podIPs:
    - ip: 10.254.4.152
  startTime: '2022-02-23T04:34:35Z'
  containers:
    - name: kube-rbac-proxy
      image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.7
      args:
        - '--secure-listen-address=:15444'
        - '--upstream=http://127.0.0.1:15080/'
        - '--logtostderr=true'
        - '--v=10'
      ports:
        - name: https
          containerPort: 15444
          protocol: TCP
      resources:
        limits:
          cpu: 200m
          memory: 40Mi
        requests:
          cpu: 100m
          memory: 25Mi
      volumeMounts:
        - name: kube-api-access-wk5b7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: false
    - name: asac
      image: devhub-docker.cisco.com/asac-dev-docker/sfcn-asac-ci:99.17.28.66
      command:
        - /bin/sh
        - '-c'
      args:
        - >-
          sed -i -e "s/udhcpc/echo udhcpc/g" /asa/scripts/rcS.common; cat
          /etc/resolv.conf; export ASAC_ID=$(echo ${POD_NAME} | cut -d- -f4);
          echo "ASAC_ID:${ASAC_ID}"; /asa/bin/lina_launcher.sh; for x in `ls
          /mnt/disk0/*crash*`; do NEW_FILENAME=${POD_NAME}_`date +%s`_`basename
          $x`; cp $x $COREDUMP_PATH/$NEW_FILENAME; done
      envFrom:
        - configMapRef:
            name: sfcn-asac-plat-limits-default
      env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: host
              optional: true
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: port
              optional: true
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: username
              optional: true
        - name: REDIS_TOKEN
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: token
              optional: true
        - name: REDIS_DB
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: db
              optional: true
        - name: REDIS_USESSL
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: useSsl
              optional: true
        - name: REDIS_EXTSERVERCERT
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: extServerCert
              optional: true
        - name: REDIS_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: storage_key
              optional: true
        - name: REDIS_STORAGE_IV
          valueFrom:
            secretKeyRef:
              name: sfcn-redis
              key: storage_iv
              optional: true
        - name: ASAC_CONFIG_DISABLED
          value: '1'
        - name: ASAC_DEALER_ENDPOINT
          value: tcp://127.0.0.1:5555
        - name: ASA_DOCKER
          value: '1'
        - name: COREDUMP_PATH
          value: /mnt/coredump_repo/
        - name: CORE_SIZE_LIMIT
          value: 200M
        - name: DISABLE_DPDK
          value: '0'
        - name: RUN_ASA_WITH_GDB
          value: '0'
        - name: ASAC_CPUS
          value: '3'
        - name: ASAC_MEMORY
          value: 8192M
        - name: ASAC_ROOT_PRIVILEGE
          value: '0'
      resources:
        limits:
          cpu: '3'
          hugepages-2Mi: 128Mi
          memory: 8Gi
        requests:
          cpu: '3'
          hugepages-2Mi: 128Mi
          memory: 8Gi
      volumeMounts:
        - name: asac-configuration
          mountPath: /mnt/disk0/configuration
        - name: file-storage
          mountPath: /mnt/disk0/storage
        - name: redis-storage
          mountPath: /mnt/disk0/redis_data
        - name: manager-socket
          mountPath: /manager-socket
        - name: redis-pem
          mountPath: /mnt/disk0/redis_pem
        - name: dev
          mountPath: /dev
        - name: hugepage
          mountPath: /hugepages
        - name: local
          mountPath: /config
        - name: modulepath
          mountPath: /lib/modules
        - name: tmp
          mountPath: /tmp
        - name: coredumprepo
          mountPath: /mnt/coredump_repo/
        - name: vpn-config
          mountPath: /mnt/disk0/ravpn_client_profile.xml
          subPath: vpn-config
        - name: interface-config
          mountPath: /mnt/disk0/interface-config/interface-config
          subPath: interface-config
        - name: kube-api-access-wk5b7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - '-c'
            - kill -0 `pidof lina` && [ -f /tmp/${POD_NAME}-dataplane.started ]
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/lina_ready
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 10
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - '-c'
              - >-
                curl --unix-socket /manager-socket/manager.sock -X POST
                http://$NODE_IP/ -d 'hello'; if [ -f
                /tmp/${POD_NAME}-dataplane.started ] && [ -f
                /tmp/${POD_NAME}-vpp.started ]; then rm
                /tmp/${POD_NAME}-vpp.started; fi; touch
                /tmp/${POD_NAME}-dataplane.started;
        preStop:
          exec:
            command:
              - /bin/sh
              - '-c'
              - >-
                rm -f /tmp/lina_ready /tmp/${POD_NAME}-dataplane.started; find
                /mnt/disk0; find $COREDUMP_PATH; env; for x in `ls
                /mnt/disk0/*crash*`; do NEW_FILENAME=${POD_NAME}_`date
                +%s`_`basename $x`; cp $x $COREDUMP_PATH/$NEW_FILENAME; done
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add:
            - SYS_RESOURCE
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_RAWIO
        privileged: true
      stdin: true
      tty: true
    - name: asagatewayserver
      image: >-
        devhub-docker.cisco.com/asac-dev-docker/sfcn-asagatewayserver-ci:v0.0.0-pr-2063-B
      args:
        - '--port=8100'
        - '--zap-log-level=2'
        - '--zap-encoder=console'
      ports:
        - name: grpc
          hostPort: 8100
          containerPort: 8100
          protocol: TCP
        - name: health-port
          hostPort: 8101
          containerPort: 8101
          protocol: TCP
      env:
        - name: GOGC
          value: '20'
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 40Mi
      volumeMounts:
        - name: tmp
          mountPath: /asac/tmp
        - name: kube-api-access-wk5b7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readinessProbe:
        httpGet:
          path: /healthz
          port: health-port
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      startupProbe:
        httpGet:
          path: /healthz
          port: health-port
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 12
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
    - name: manager
      image: >-
        devhub-docker.cisco.com/asac-dev-docker/sfcn-enforcementpoint-ci:v0.0.0-pr-2063-B
      args:
        - '--metrics-port=15080'
        - '--system-namespace=sfcn-system'
        - '--deltagen-service=sfcn-deltagen-server.sfcn-system.svc:8088'
        - '--asagateway-service=127.0.0.1:8100'
        - >-
          --cli-validation-service=sfcn-cli-validation.sfcn-system.svc.cluster.local:47474
        - '--storage-service=sfcn-storage-server.sfcn-system.svc:80'
        - '--webhook-port=15443'
        - '--asac-socket-path=/asac/manager-socket/manager.sock'
        - '--license-service=sfcn-license-server.sfcn-system.svc:80'
        - '--license-client-port=50052'
        - '--licensing-enabled=true'
        - '--zap-log-level=2'
        - '--zap-encoder=console'
        - '--config-status-port=50053'
      ports:
        - containerPort: 50052
          protocol: TCP
        - name: cfg-status-port
          hostPort: 50053
          containerPort: 50053
          protocol: TCP
      envFrom:
        - configMapRef:
            name: sfcn-ep-feature-flag-config
      env:
        - name: GOGC
          value: '20'
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: VALIDATE_CLI
          value: '1'
      resources:
        limits:
          cpu: 100m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 200Mi
      volumeMounts:
        - name: asacdevicemgr
          mountPath: /dev/net/tun
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: asac-configuration
          mountPath: /mnt/configuration
        - name: dev
          mountPath: /asac/dev
        - name: file-storage
          mountPath: /asac/storage
        - name: manager-socket
          mountPath: /asac/manager-socket
        - name: tmp
          mountPath: /asac/tmp
        - name: kube-api-access-wk5b7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readinessProbe:
        httpGet:
          path: /configstatus
          port: cfg-status-port
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 10
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
  restartPolicy: Always
  terminationGracePeriodSeconds: 10
  dnsPolicy: ClusterFirstWithHostNet
  serviceAccountName: default
  serviceAccount: default
  nodeName: worker2.testbed3.kasa-vm.com
  hostPID: true
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  imagePullSecrets:
    - name: regsfcn
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: sfcn.cisco.com/nodetype
                operator: In
                values:
                  - enforcement
  schedulerName: default-scheduler
  tolerations:
    - key: cisco-nodetype
      operator: Equal
      value: enforcement
      effect: NoSchedule
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority

==============================
NetworkAttachmentDefinition.yaml
=======================
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  creationTimestamp: '2022-02-23T04:30:25Z'
  generation: 1
  managedFields:
    - apiVersion: k8s.cni.cncf.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:ownerReferences:
            .: {}
            k:{"uid":"edb042ae-9346-437a-9bbc-fd46e62620ab"}: {}
        f:spec:
          .: {}
          f:config: {}
      manager: cluster-network-operator
      operation: Update
      time: '2022-02-23T04:30:25Z'
  name: simple-macvlan
  namespace: sfcn-system
  ownerReferences:
    - apiVersion: operator.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Network
      name: cluster
      uid: edb042ae-9346-437a-9bbc-fd46e62620ab
  resourceVersion: '4036396'
  uid: 1791a445-2458-43e0-8673-cd77a77da699
  selfLink: >-
    /apis/k8s.cni.cncf.io/v1/namespaces/sfcn-system/network-attachment-definitions/simple-macvlan
spec:
  config: |-
    { "cniVersion": "0.3.1", "type": "macvlan",
    "master": "ens161",
    "mode": "bridge",
    "ipam":       { "type": "dhcp" } }

**Comment by pkamaraj** [comment]
> Thank you for the issue. Could you please provide us about following output?
> 
> * kubectl -n sample get net-attach-def -o yaml
> * kubectl -n sample get pod -o yaml

Shared more info. Can you please check

**Comment by s1061123** [comment]
As far as I looked your pod annotation, no duplicated MAC address in the network interface status. You may see network status in two different annotations (k8s.v1.cni.cncf.io/network-status and k8s.v1.cni.cncf.io/networks-status, network v.s. network's') and that may make you misunderstanding that same MAC address is assigned.

```
k8s.v1.cni.cncf.io/network-status: |-
[{
"name": "openshift-sdn",
"interface": "eth0",
"ips": [
"10.254.4.152"
],
"default": true,
"dns": {}
},{
"name": "sfcn-system/simple-macvlan",
"interface": "net1",
"ips": [
"10.10.3.99"
],
"mac": "ea:09:d2:25:a4:b1",
"dns": {}
},{
"name": "sfcn-system/oc-multus-gig0",
"interface": "net2",
"mac": "00:50:56:81:23:46",
"dns": {}
},{
"name": "sfcn-system/oc-multus-gig1",
"interface": "net3",
"mac": "00:50:56:81:2f:2f",
"dns": {}
}]
```

> The above approach we have 2 ip address assigned even with same MAC address for one interface ..
> The DHCP IP assigned for net1 interface another one from the POD interface. How do avoid DHCP address assignment on net1 interfaces ?

Hence I'm not still clear yet about
- 2 ip address assigned even with same MAC address for one interface  and 
- The DHCP IP assigned for net1 interface another one from the POD interface. (I found that net1 interface has DHCP IP, but I'm not clear that 'another one from the POD interface, do you mean that eth0 of openshift-sdn?)

**Comment by pkamaraj** [comment]
Hi, 
for the config perspective,  we will not see the 2 IP address assigned on same MAC. 
Our deployment scenarios as follows. 
* Bringup DPDK application POD with host networking ( 3 interfaces, eth0,eth1,eth2)
* defined POD interfaces as multus CNI (net1/net2/net3). this we can seen the pod shell and invoke "ifconfig" command
* the net1/net2/net3 will be mapped to the POD interface as per the network attachment and definion of pod yaml file
* when the DHCP enabled for the interfaces - it tries to get the ip address for both multus net1 interface and POD interfaces in the DPDK application
* We have verifed as we logged into the POD shell ( with same MAC for net1/net2/net3) and POD application i.e DPDK application CLI interface. As you know the our DPDK pod application has property dhcp client. Hence our application also receives an DHCP ip address from server and multus interfaces also getting an ip address 
* how do we prevent the multus CNI interfaces(net1/net2/net3) not to get the DHCP ip address from DHCP server ? 
Please share your thoughts. 

Thanks,
Kamaraj

**Comment by s1061123** [comment]
In your config, you explicitly uses DHCP for macvlan interface, of multus. So you just explicitly mention that you don't use DHCP for ipam, for example replace it with something others or jsut remove 'ipam' section, then net1/net2/net3 does not have DHCP assigned IP address. I guess.

```
 config: |-
{ "cniVersion": "0.3.1", "type": "macvlan",
"master": "ens161",
"mode": "bridge",
"ipam": { "type": "dhcp" } }  <- here you mention DHCP is used for IP address management.
```
