### ISSUE TITLE
Missing v3.8.1 tag at code

### ISSUE THREAD

**Issue by qinqon** [k8snetworkplumbingwg/multus-cni#789]
**What happend**:

At [cluster-network-addons-operator](https://github.com/kubevirt/cluster-network-addons-operator) we are integrating with latest tagged multus with appear to be v3.8.1 at [container registry](https://github.com/k8snetworkplumbingwg/multus-cni/pkgs/container/multus-cni/versions), we also take the manifest from source code but v3.8.1 tag is not [there](https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v3.8).

**What you expected to happen**:
A v3.8.1 tag has to be present at source code to align with the container.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
If there is no release, v3.8.1 is not released yet. To fix the CI issue, I may create/delete v3.8.1 once (as far as I remembered), hence the container registry's entry is the one.

**Comment by s1061123** [comment]
let me check my logs...

**Comment by s1061123** [comment]
Right. I checked my logs and multus maintainer's agenda but cannot find any mention to v3.8.1. So it is just a noise. v3.8.1 is just v3.8 based one, I suppose.

Once we release new version, then 'latest' will be replaced with newer one.
