### ISSUE TITLE
libcni update to 1.0

### ISSUE THREAD

**Issue by s1061123** [k8snetworkplumbingwg/multus-cni#792]
Todo:

- [ ] update go mod
- [ ] update go code a bit (because libcni 1.0 change is not so small...)
- [ ] Add unit-test to multus 1.0
- [ ] Something missed...
- [ ] Update e2e testing

**Comment by cyclinder** [comment]
Should these todo's be done in one PR or by each of the four PR's?

**Comment by s1061123** [comment]
This will be done inone PR, as a part of next major version.

**Comment by cyclinder** [comment]
maybe not an easy thing.. :), If i have free time, I want to try to do this.
