### ISSUE TITLE
Need anything specific for multus to work on k3s ?

### ISSUE THREAD

**Issue by tardich** [k8snetworkplumbingwg/multus-cni#796]
Hi,

I'm trying to make multus work on k3s on Raspberry Pi. It works.....  somewhat. My pod starts, gets an IP. But then, I'm facing something strange.

From the pod, I can ping anything in the same network as the multus interface, which is the desired state. But the opposite is not true. If, from the same network as the multus interface, I try to ping the multus interface (or connect to its listening service (say...  UDP/TCP/53 (DNS listener)), it does not work. This works without anything special on my rke cluster (baremetal, AMD64).

Tried it with two different OSes (Gentoo derivative for Rpi4) and DietPI (Debian derivative). Same behavior

Configuration is:

k3s v1.22.6
64-bit OS
Main CNI: Flannel
Multus interface attached to eth0 (single interface from Raspberry PI 4

From the host holding the pod, which doing a ping from outside of kubernetes, if I tcpdump the icmp proto, I can see an ECHO REQUEST, then an ECHO REPLY. On the host originating the PING, I'm only seeing ECHO REQUESTS, no reply

Could I be missing something on the raspberry pi node which would drop the echo reply before it's sent out ?

**Comment by s1061123** [comment]
From multus-cni project point of view, we are not sure about k3s. 
I hope someone, who use multus with k3s, may reply the issue, but I'm not sure...

How about to file a issue on k3s repo as well? https://github.com/k3s-io/k3s/issues

**Comment by dougbtv** [comment]
+1 to the above, worth mentioning to that community.

It sounds a connectivity issue for the CNI plugin that they've used to create the secondary interface, that Multus may have executed but the configuration for whatever CNI plugin you're using via Multus might not be correct. Something to look at.

If you do get a working deployment, you could contribute @ https://github.com/k8snetworkplumbingwg/reference-deployment
