### ISSUE TITLE
We need updated documentation for supported versions as well as supported dependencies

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/multus-cni#804]
For example:

* Which versions we currently support
* Which kubernetes versions we support
* Which CNI versions we support
* Follow up: Remove NFVPE-named images from dockerhub (?)

Let's add documentation for all of the above.

We can target the release 4 branch for this

**Comment by Zalastax** [comment]
Hi @dougbtv, was this completed?

I can find:
https://github.com/k8snetworkplumbingwg/multus-cni/blob/3a951119017e71bd36f3d442914d239465afbf80/docs/development.md?plain=1#L3-L6

All of the aspects that you bring up would be very valuable to have documented. Knowing this would help with setting up a cluster with compatible components (Kubernetes, Multus, CNI). Knowing this would help understand what Multus versions to verify applications against for applications that may run in different environments.

Without this, it can be difficult to know e.g. whether Multus 3.9.3 is considered supported (or is only Multus 4 and beyond supported now?) and whether Multus 3.9.3 is supposed to be compatible with Kubernetes 1.27 (released later than Multus 3.9.3 but could still be compatible).

I don't know your policies, so I can't go ahead immediately, but if you let me know your view on these aspects I could format that nicely, find a suitable place to include the information, and make a Pull Request.
