### ISSUE TITLE
enhancement: add metrics capability for multus

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/multus-cni#808]
**What would you like to be added**:
I want to add some metrics capability for multus(prometheus)
**Why is this needed**:
At present, Multus lacks some metrics capability, For Example:
- Number of calls to CNI plugin or number of failed calls
- Latency of calling CNI plugin
- Get information about the NetworkAttachmentDefinition CR(.etc)

We should provide this capability in multus and be able to control whether to turn it on or not on installing via flags. 

WDYT? @s1061123

**Comment by s1061123** [comment]
Thank you for your opinion! Current multus CNI is just a one shot process, not server, hence it is hard to implement metrics for prometheus, but next version we introduce client/server style multus CNI (as ovn-kubernetes and other plugin does). In this client/server deployment, we could implement some of metrics and actually I'm planning to do that.

BTW, In next version, of course, we still continue to provide current (one shot process) CNI, for small footprint.

**Comment by s1061123** [comment]
Once I implement some of them, update this issue and let you know.

**Comment by cyclinder** [comment]
Thank your good reply and great job,  I looking forward to your update!

**Comment by sherif84** [comment]
+1

**Comment by jcpunk** [comment]
I'll confess I'd like to see this, any chance to reopen?

**Comment by aphrodite1028** [comment]
also need!   if add metrics capability for multus, if call macvlan or other error msg?
