### ISSUE TITLE
pod in ContainerCreating - error adding container to network "x": Link not found

### ISSUE THREAD

**Issue by ritokispingvin** [k8snetworkplumbingwg/multus-cni#809]
Hi,

my pod stays in ContainerCreating status. 
![image](https://user-images.githubusercontent.com/81585862/157312654-dfb90e9d-8d4d-4f59-ade4-426f20d4014e.png)

Kubectl describe pod UPF:
![image](https://user-images.githubusercontent.com/81585862/157312732-8b6ebd10-b4d4-43e7-912a-8f3bc8d3597c.png)

I've tried to set this up on both minikube and kubeadm, both with flannel and calico CNIs but all my trials resulted in same issue.

My current network config:
![image](https://user-images.githubusercontent.com/81585862/157314859-3df83dd6-49b8-4cb7-b862-063cd06170fe.png)
![image](https://user-images.githubusercontent.com/81585862/157314902-7bf79f37-1e41-45cd-bbfc-3a8065df7730.png)
![image](https://user-images.githubusercontent.com/81585862/157314870-1df5f2fb-6d2a-4dd6-86ea-bedef817940e.png)
![image](https://user-images.githubusercontent.com/81585862/157314882-63c83d70-75b1-4220-98db-25f9404a8218.png)

NetworkAttachmentDefinition is following. Only n6 network uses eth1 so I'm listing only that. All other pods are using eth0 which is working fine as those pods are running.
![image](https://user-images.githubusercontent.com/81585862/157313928-618bb2e1-926c-4828-bc97-5f24a44a8c59.png)

If I set n6 network to use eth0 instead of eth1 then the UPF pod is created successfully, but I need to attach it to eth1 for my project. So I think it is some issue when using a secondary interface.

Thank you and best regards,
Tamas

**Comment by dougbtv** [comment]
Looks like the delegated CNI plugin is reporting `link not found` -- which seems like it can't find the interface on the host side. This looks like a platform problem from here that the corresponding NIC name isn't found. May be worth double checking that it's there, and/or looking into it from the virtualization platform angle

**Comment by camilla-m** [comment]
Hi!
I'm having precisely the same problem, but I'm very new at network interfaces at k8s and don't know exactly how to debug it and solve it. When I try to search for the problem on the internet I don't receive information accurate enough to go deeper into it.
Can anyone give a tip?
