### ISSUE TITLE
the functon getNetDelegate have a bug

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/multus-cni#810]
**What happend**:
https://github.com/k8snetworkplumbingwg/multus-cni/blob/45428a53ceedcf6359a7c2f75e8b84d64a10148b/pkg/k8sclient/k8sclient.go#L526-L530
according to debug info, the value of `netname` is cni conf name, such as `k8s-pod-network`.  When used as an argument to this function, this will definitely return an error.

**What you expected to happen**:
The argument to os.stat should be a file directory path instead of netname

**How to reproduce it (as minimally and precisely as possible)**:
refer to the source code

**Anything else we need to know?**:
option 3 never work

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
This code is not for network annotation,  'k8s.v1.cni.cncf.io/networks', actually. I'm not clear what  you want to do.
Could you please share your config and let you know what you try to do?

**Comment by cyclinder** [comment]
Thank for your reply! this is my config:
```bash
root@kind-worker:/etc/cni/net.d# ls
00-multus.conf  10-calico.conflist  calico-kubeconfig  multus.d
root@kind-worker:/etc/cni/net.d# cat 00-multus.conf
{
    "binDir":"/opt/cni/bin",
    "capabilities":{
        "portMappings":true
    },
    "clusterNetwork":"k8s-pod-network",
    "cniDir":"/var/lib/cni/multus",
    "cniVersion":"0.3.1",
    "confDir":"/etc/cni/net.d",
    "defaultNetwork":[],
    "delegates":[],
    "globalNamespaces":"kube-system,kube-test",
    "kubeconfig":"/etc/cni/net.d/multus.d/multus.kubeconfig",
    "logFile":"/var/log/multus.log",
    "logLevel":"debug",
    "name":"multus-cni-network",
    "namespaceIsolation":true,
    "readinessindicatorfile":"",
    "systemNamespaces":[
        "kube-system"
    ],
    "type":"multus"
}
root@kind-worker:/etc/cni/net.d# cat 10-calico.conflist
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "datastore_type": "kubernetes",
      "nodename": "kind-worker",
      "mtu": 0,
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]
```
I checked the source code for multus has three options to get defalutNetwork:

- Get it from net-atta-defi CRD with namespace kube-system and name k8s-pod-network
- Get it from confdir (in my case, get it from /etc/cni/net.d/ path)

The above two ways are fine, but the third option doesn't actually work in my opinion, the value of the variable `netname` is `k8s-pod-network`, which definitely doesn't work when we use `os.stat(netname)`.

I am very confused. So what I mean is that the input parameter of os.stat should be a directory name, not netname.

Do you think so?

**Comment by s1061123** [comment]
No, this accepts directory as following example:

```
[root@kube-node-1 ~]# cat /etc/cni/net.d/00-multus.conf
{
  "cniVersion": "0.3.1",
  "name": "multus-cni-network",
  "type": "multus",
  "capabilities": {
    "portMappings": true
  },
  "logLevel": "debug",
  "logFile": "/tmp/multus.log",
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "clusterNetwork": "/etc/cni/sample"
}
[root@kube-node-1 ~]# cat /etc/cni/sample/10-flannel.conflist
{
  "name": "cbr0",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
```

**Comment by cyclinder** [comment]
Thanks!  I get it.
