### ISSUE TITLE
the pod log of multus is not output to the terminal

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/multus-cni#811]
I deployed multus via helm, and the following is the multus installation configuration：
```bash
{
    "binDir":"/opt/cni/bin",
    "capabilities":{
        "portMappings":true
    },
    "clusterNetwork":"k8s-pod-network",
    "cniDir":"/var/lib/cni/multus",
    "cniVersion":"0.3.1",
    "confDir":"/etc/cni/net.d",
    "defaultNetwork":[],
    "delegates":[],
    "kubeconfig":"/etc/cni/net.d/multus.d/multus.kubeconfig",
    "logFile":"/var/log/multus.log",
    "logLevel":"debug",
    "name":"multus-cni-network",
    "readinessindicatorfile":"",
    "type":"multus"
}
```
But when I look at the multus pod logs via kubectl logs, I don't see the expected logs, only something like the following：
```bash
[root@node2]# kubectl logs -f -n kube-system multus-multus-ds-xqtv6
+ sed 's|__KUBERNETES_NODE_NAME__|kind-worker2|g' /tmp/multus-conf/00-multus.conf.template
+ /entrypoint.sh --multus-conf-file=/tmp/multus-conf/00-multus.conf
2022-03-10T06:52:16+0000 Entering sleep (success)...
```
Someone tell me why? Thanks!

**Comment by dougbtv** [comment]
Ok, that gist is that the "pod logs" for the multus daemonset, only show you the result of the installation of the Multus CNI plugin.

If you want more detailed logs, the places to look are:

* The k8s events of a specific failing pod that has a */networks annotation (will give you a clue as to what happened during a failure)
* You could also look at kubelet logs to see results from a failed CNI call
* Last but not least, look at the host side for the log file you specified: `"logFile":"/var/log/multus.log",`
