### ISSUE TITLE
type of DelegateNetConf.GatewayRequest should be net.IP

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/multus-cni#812]
**What happend**:
Currently, the type of DelegateNetConf.GatewayRequest is []net.IP, Just see the following: 
https://github.com/k8snetworkplumbingwg/multus-cni/blob/45428a53ceedcf6359a7c2f75e8b84d64a10148b/pkg/types/types.go#L100

But the function `CheckGatewayConfig` will check the number of `GatewayRequest`, If len > 1 , just return err. so I think type of `DelegateNetConf.GatewayRequest` should be net.IP instead of []net.IP.
**What you expected to happen**:
type of DelegateNetConf.GatewayRequest should be net.IP instead of []net.IP
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by dougbtv** [comment]
We allow multiple gateways due to IPv6 specification

more info in the specification @ https://github.com/k8snetworkplumbingwg/multi-net-spec -- do a find for "gateway" and it should have some explanation

**Comment by cyclinder** [comment]
Thanks!
