### ISSUE TITLE
custom config cni-conf.json takes no effect

### ISSUE THREAD

**Issue by owenchenxy** [k8snetworkplumbingwg/multus-cni#816]
Refering to https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml#L104.
User should be able to customize the cni-conf.json file. However, when I add logLevel or logFile configs to the configmap and follow the instructions to use the configmap as my multus cni configuration, it doesn't take effect.

I inspected the multus docker image. In the entrypoint.sh script, it has not ever used the MUTULS_CONF_FILE to parse configurations, but use command options such as "--multus-log-level" to determine it's behaviors.

However, I specified the parameters like follow:
```
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=auto"
        - "--multus-log-level=debug"
        - "--multus-log-file=/var/log/multus.log"
        - "--cni-version=0.3.1"
```
pod's log shows the configurations has been made:
```
root@fb:~# kubectl -n kube-system logs kube-multus-ds-qrx6p
2022-03-25T01:34:22+0000 Generating Multus configuration file using files in /host/etc/cni/net.d...
2022-03-25T01:34:23+0000 Using MASTER_PLUGIN: 10-weave.conflist
2022-03-25T01:34:23+0000 Nested capabilities string: "capabilities": {"portMappings": true},
2022-03-25T01:34:23+0000 Using /host/etc/cni/net.d/10-weave.conflist as a source to generate the Multus configuration
2022-03-25T01:34:23+0000 Config file created @ /host/etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true}, "logLevel": "debug", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "cniVersion": "0.3.0", "name": "weave", "plugins": [ { "name": "weave", "type": "weave-net", "hairpinMode": true }, { "type": "portmap", "capabilities": {"portMappings": true}, "snat": true } ] } ] }
2022-03-25T01:34:23+0000 Entering sleep (success)...
```

But it still seemed to take no effect,  as I entered the container but didn't find the log file under /var/log directory
```
[root@mjqkuber01n01 log]# ll
total 40
-rw------- 1 root utmp     0 Nov 13  2020 btmp
-rw-r--r-- 1 root root   193 Nov 13  2020 grubby_prune_debug
-rw-r--r-- 1 root root 23944 Nov 13  2020 lastlog
-rw------- 1 root root  5248 Nov 13  2020 tallylog
-rw-rw-r-- 1 root utmp     0 Nov 13  2020 wtmp
-rw------- 1 root root  1430 Nov 13  2020 yum.log
```

**Comment by nicklesimba** [comment]
I don't have a clear answer, but maybe a maintainer will. I want to cover a few things, which might better help them solve this issue. :slightly_smiling_face: 

1. when you defined the multus-conf-file yourself, what did you name it? Are you sure it is alphabetically first in the `/etc/cni/net.d/` dir on **every** node? For example, starting a filename with 0 (`000-custom-multus.conf) will help in this regard. I think this is the supported way of customizing your multus conf, so hopefully you can get this working and not worry about the other approach.

2. If you do opt for using `"--multus-conf-file=auto"`, it does appear to me also that you're passing in the arguments correctly. So I'm not sure why this isn't working. Just a +1, you seem to be doing things correctly, at least according to `entrypoint.sh`.

**Comment by s1061123** [comment]
Config map in deployment yaml, is previously used but no longer used, well, let me remove it in next release...

BTW, Multus log, which could be configured as `--multus-log-file` and `--multus-log-level`, is the log which generated by multus cni, not multus installer, the daemonset of `kube-multus-ds-xxx`.

multus daemonset is used to watch cluster network CNI config (and update multus config when it is updated) and it is not CNI plugin.

Once you configured  "--multus-log-level=debug" and "--multus-log-file=/var/log/multus.log", then your CNI config in Kubernetes nodes have CNI json config, '/etc/cni/net.d/00-multus.conf', and it contains `"logLevel": "debug"` and `"logFile":"/var/log/multus.log"` .

Once you launched the pod after install the multus, multus CNI plugin in the node, scheduled to run pod, is executed and creates the log, in container host (not pod).

**Comment by nicklesimba** [comment]
So after some more digging - I think I understand what's going on a bit better. The correct behavior, like Tomo said, is that the pod logs *should* show up on the nodes (host). This works fine using your setup:
```
image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
command: [ "/entrypoint.sh" ]
args:
- "--multus-conf-file=auto"
...etc...
```

You were looking for logs on the container, probably by doing `kubectl exec -it <pod-name> /bin/bash` or something like that. Where you actually are supposed to find the logs is on the host - aka on your nodes. So you'd want to get your node names (`docker ps` if you're using KIND, for example) and `docker exec -it <node-name> /bin/bash`. Here, under `/var/log/` you should find your `multus.log`.

Additional context: In the incorrect "temporary fix" I provided above, I use the thick plugin image, and the logs **do show up** on the pods, but this is potentially a bug/error; they should be on the host (nodes) *and not on the pods*.

**Comment by dougbtv** [comment]
re: 

> Additional context: In the incorrect "temporary fix" I provided above, I use the thick plugin image, and the logs do show up on the pods, but this is potentially a bug/error; they should be on the host (nodes) and not on the pods. This will likely be addressed soon.

I was able to reproduce this in my lab.

The gist is that when using the `multus-daemon`  (from the thick variant deployment) as opposed to the `entrypoint.sh` the multus-daemon itself actually honors the value of the `logFile`, and logs to that file **in the daemonset container*

As well as it templates the CNI configuration on disk properly and, Multus -- which is running on the host ALSO logs to the `logFile` value's location and logs to that file **on the host**

I think this is acceptable functionality.

**Comment by dougbtv** [comment]
@owenchenxy -- sorry for all the extra conversation here, we just noticed something while trying to reproduce your issue.

I think the end solution here is -- look for that `logFile` *on the host* -- that's where you'll find it, not in the container.

**Comment by dougbtv** [comment]
Did the logfile on the host show up? If not, please feel free to reopen.
