### ISSUE TITLE
Uninstall multus cni

### ISSUE THREAD

**Issue by robertbotez** [k8snetworkplumbingwg/multus-cni#819]
Hi,

How to uninstall corectly multus cni? 

I deleted all multus resources and multus files from /etc/cni/net.d/ but I still have some bugs when I try to deploy other k8s workloads.

**Comment by s1061123** [comment]
Uninstall CNI depend on your platform, so we don't have any steps to uninstall multus CNI.
In case of Kubernetes, Kubernetes does not mention how to uninstall CNI plugin and how to migrate CNI network one to another.

So the easy way to uninstall multus is undeploy Kubernetes and deploy new Kubernetes.
