### ISSUE TITLE
Not able to access Multus 2nd network interface from node

### ISSUE THREAD

**Issue by yockgen** [k8snetworkplumbingwg/multus-cni#832]
I'm able to ping primary network address from host/node, for example:
kubectl exec -it test01-deployment-5fc76b45c6-ljv4m -- ping 10.233.65.3  <-this is my 1st/default network interface, able to ping!

Node (where the pod is sitting on):
root@focal01:~#  ping 10.233.65.3 <- ping from the node, working fine!
*****************************************************************************
However, for 2nd network interface:
kubectl exec -it test01-deployment-5fc76b45c6-ljv4m -- ping 192.168.22.227  <-this is my 2nd network interface, able to ping!

Node (where the pod is sitting on):
root@focal01:~#  ping 192.168.22.227 **<-ERROR!! running forever, nothing return**

2nd network interface definition
=======================
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: yockgen-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "yockgen-network",
    "type": "macvlan",
    "master": "ens4",
    "mode": "bridge",           
    "isDefaultGateway": false,
    "forceAddress": false,
    "ipMasq": false,
    "hairpinMode": false,
    "ipam": {
        "type": "whereabouts",
        "range": "192.168.22.225/28"    }
    }'

App Deployment as below
=================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test01-deployment
  labels:
    app: yockgen
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test01pod
  template:
    metadata:      
      annotations:
        k8s.v1.cni.cncf.io/networks: yockgen-network
      labels:
        app: test01pod
    spec:	
      containers:
      - name: test01pod
        command: ["/bin/sleep","3650d"]
        image: yockgen/ubuntu
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME","NET_RAW"]

Any help is really appreciate!

**Comment by cyclinder** [comment]
Maybe you should look into macvlan's bridge mode... In this mode, the container cannot communicate directly with the master interface of the node.

**Comment by yockgen** [comment]
Found a solution, on the host: 
1. Create macvlan bridge with same IP address range (ens is the master network device):
ip link add yockgen-macvlan link ens8 type macvlan mode bridge
ip addr add 10.0.0.155/32 dev yockgen-macvlan
ip link set yockgen-macvlan up

2. Delete existing route link to master "ens" by Kubernetes
ip route del 10.0.0.0/24

3. Link the route to macvlan bridge created by step 1 above
ip route add 10.0.0.0/24 dev yockgen-macvlan

4. Try to ping secondary network interface IP address from the pod's host (not inside container):
root@focal02:~# ping 10.0.0.227   <- this is the pod secondary IP address
PING 10.0.0.227 (10.0.0.227) 56(84) bytes of data.
64 bytes from 10.0.0.227: icmp_seq=1 ttl=64 time=0.199 ms
64 bytes from 10.0.0.227: icmp_seq=2 ttl=64 time=0.080 ms
