### ISSUE TITLE
Intermittent failure in kubernetes coredns when I use multus-cni

### ISSUE THREAD

**Issue by shruthidharani-4313** [k8snetworkplumbingwg/multus-cni#840]
I have deployed a rancher cluster with 3 interfaces (eth0, eth1- private and eth2- public) with multi-interface (multus-cni) . And on the worker node, I could see the default route is eth0. Also I have installed a pod in the default namespace of rancher cluster. I have one container inside that pod and also I am getting eth0 as default route inside that container. With this route, my pod/container is able to communicate coredns without any issues. Route info as below:
```
[root@user]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         169.254.1.1      0.0.0.0         UG    0      0        0 eth0
10.30.5.0       0.0.0.0         255.255.255.0   U     0      0        0 eth1
10.31.7.0       0.0.0.0         255.255.255.0   U     0      0        0 eth2
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0
```
But I don't need to send all traffic via default eth0 interface. So I changed the default route as eth2 instead of eth0 on both worker node and inside my container. Route info as below:
```
[root@user]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.31.7.1      0.0.0.0         UG    0      0        0          eth2
10.30.5.0       0.0.0.0         255.255.255.0   U     0      0        0     eth1
10.31.7.0       0.0.0.0         255.255.255.0   U     0      0        0     eth2
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0      0  eth0
```

Once I changed the default route, container is getting intermittent failure to reach coredns. Output as below:
```
[root@user]# host da
da.default.svc.cluster.local has address 10.43.72.31
[root@user]# host da
;; connection timed out; no servers could be reached
[root@user]# host kube-dns.kube-system
;; connection timed out; no servers could be reached
[root@user]# host da
;; connection timed out; no servers could be reached
```   

Could someone help me out why this issue is occurring when I change default route? I am not sure whether coredns communication will work only using eth0. Is there anything like that? As I'm quite new to kubernetes environment and multi interface (multus-cni), it would be really helpful if someone explain how to resolve this issue. Thanks in advance!!!

**Comment by dougbtv** [comment]
Your eth2 likely doesn't have the connectivity to the default pod-to-pod network. If the default route is changed to eth2, service requests will go over eth2, but if it's isolated from the default pod-to-pod network, it won't have connectivity.

Typically what I'd advise is that you leave eth0 with connectivity on the pod-to-pod network, leave the default route for eth0, and then add the routes that you need for the secondary interfaces (e.g. on eth2)
