### ISSUE TITLE
Need e2e tests for default-route selection

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/multus-cni#842]
See #841

Gist is, we need some e2e tests that test default-route selection. Currently we have excellent unit test coverage, but we need an integration test for this feature to prevent regressions.

We can likely use the steps described here @ https://github.com/k8snetworkplumbingwg/multus-cni/blob/130db696ca739fb3bcb550104ace34f03c00a360/docs/how-to-use.md#specifying-a-default-route-for-a-specific-attachment

And then spin up a pod, and check that it succeeds to launch and check its default route.

**Comment by cyclinder** [comment]
https://github.com/k8snetworkplumbingwg/multus-cni/blob/ecc1482d500673eb7ed7f0a3d8fb89be0851a4ba/.github/workflows/kind-e2e.yml#L44
There are e2e tests for `default-route selection` ?
