### ISSUE TITLE
How to specify a NetworkAttachmentDefinition as a custom default-network for pods

### ISSUE THREAD

**Issue by l-rossetti** [k8snetworkplumbingwg/multus-cni#843]
We have a k3s cluster with flannel as default cni network plugin. We have integrated [ovs-cni](https://github.com/k8snetworkplumbingwg/ovs-cni) with multus in order to inject an additional interface on our pods. That works fine.
Right now we are trying to make use of ovs-cni as default-network plugin for our pods. We didn't find any reference on the multus documentation about that, but we read about `v1.multus-cni.io/default-network` annotation in [issue-374](https://github.com/k8snetworkplumbingwg/multus-cni/issues/374).
Unfortunately we couldn't get a running pod with a custom default-network. You can see our example manifests below:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: emu
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-nad
  namespace: emu
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/ovs-bridge
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "plugins": [
        {
          "type": "ovs",
          "vlan": 1,
          "bridge": "br-emu"
        }
      ]
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: ovs-client
  namespace: emu
  annotations:
    v1.multus-cni.io/default-network: emu/ovs-nad
  labels:
    app: ovs-client
spec:
  containers:
  - image: alpine:latest
    name: ovs-client
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep infinity" ]
```

Basically we defined a NAD with ovs-cni plugin and we are referencing it into the pod `v1.multus-cni.io/default-network` annotation. Our pod is stuck in `ContainerCreating` state and the describe shows the following events:
```
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               6s    default-scheduler  Successfully assigned emu/ovs-client to auroraibm1
  Warning  FailedCreatePodSandBox  6s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8d0532cd780404ec11badb1ea91a4fbf37957045b84bd2a4e111e72c28cb78a3": failed to find network info for sandbox "8d0532cd780404ec11badb1ea91a4fbf37957045b84bd2a4e111e72c28cb78a3"
  Normal   AddedInterface          6s    multus             Add eth0 [] from emu/ovs-nad
  Normal   AddedInterface          5s    multus             Add eth0 [] from emu/ovs-nad
  Warning  FailedCreatePodSandBox  5s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ea8fecadcdcd4b8135531ddf6fbd5e991a55a043fee4de949bb44f387b1de113": failed to find network info for sandbox "ea8fecadcdcd4b8135531ddf6fbd5e991a55a043fee4de949bb44f387b1de113"
  Warning  FailedCreatePodSandBox  4s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "cd761c65c62dcb4464f6d9f0517ea100b92d1c99708429282a6d0dd2430e3e10": failed to find network info for sandbox "cd761c65c62dcb4464f6d9f0517ea100b92d1c99708429282a6d0dd2430e3e10"
```

Could you please help us understanding what's going on and how to specify a custom default-network for our pods? The fact that the interface created by Multus doesn't have an assigned IP address could prevent the correct pod lifecyle? Cause due to our project requirements we have to assign an IP via a dedicated dhcp-server pod in a second moment.

**Comment by l-rossetti** [comment]
-------------- UPDATE -----------------

Just figured it out that by setting a static IP address for the interface, then the container is correctly starting.
Here the updated NAD:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-nad1
  namespace: emu
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/ovs-bridge
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "plugins": [
        {
          "type": "ovs",
          "vlan": 1,
          "bridge": "br-emu",
          "ipam": {
            "type": "static",
            "addresses": [
              {
                "address": "192.168.98.2/24",
                "gateway": "192.168.98.1"
              }
            ]
          }
        }
      ]
    }
```
Just to provide some more context on our requirements and researches: we know it is a very uncommon design to let a dedicated dhcp daemon to serve the pod with an IP address in a second moment with respect to the container startup. Although, we have to execute a qemu/kvm vm inside a container so we basically need the vm to request the IP address, we don't need it on the container itself. 
So the question is: is there any alternative for avoiding to provide an IP on the container or is it really mandatory?

**Comment by s1061123** [comment]
`  Normal   AddedInterface          6s    multus             Add eth0 [] from emu/ovs-nad` indicates that multus may not get IP address information from 'ovs-cni' plugin's result. Multus does not assign ip address for net-attach-def because multus expects that delegating CNI plugin (i.e. 'ovs-cni' in this case) in net-attach-def assign IP address based on the plugin's network information.  As far as I looked https://github.com/k8snetworkplumbingwg/ovs-cni, ovs-cni just returns interface, without IP address. So 'ovs-cni' cannot be used for default network.

To making CNI plugin for default network (i.e. Kubernetes cluster network), CNI plugin should return IP address otherwise Kubernetes cannot reach the pods. So you need to use ipam pluign, for example, https://github.com/k8snetworkplumbingwg/whereabouts/. (as your second post).

Static cni plugin is designed to assign 'static IP address', as described in https://www.cni.dev/plugins/current/ipam/static/, hence this is not used for the cases.

**Comment by maiqueb** [comment]
>  is there any alternative for avoiding to provide an IP on the container or is it really mandatory?

@l-rossetti afaiu, **no**. According to the [k8s network model](https://kubernetes.io/docs/concepts/services-networking/#the-kubernetes-network-model), "Every Pod gets its own IP address."
