### ISSUE TITLE
Known static IP for each pod on a StatefulSet

### ISSUE THREAD

**Issue by bbouzan** [k8snetworkplumbingwg/multus-cni#845]
**What would you like to be added**: Ability to set static IPs for each pod on a StatefulSet

**Why is this needed**: Like explained by #537 and #589, whenever a StatefulSet is used it's a common situation to require known static IPs on each of the pods. Right now this doesn't seem to be possible using multus,

**Comment by s1061123** [comment]
Static IP plugin is just desined to assign static IP address, as described in https://www.cni.dev/plugins/current/ipam/static/ hence it is not applicable to StatefulSet. You may need other IPAM plugins (e.g. whereabouts).
