### ISSUE TITLE
New Release for Multus

### ISSUE THREAD

**Issue by cgchinmay** [k8snetworkplumbingwg/multus-cni#849]
Hi, the v3.8 is 8 months old now and there have been several changes on the Master branch. Any plans for a new release ? There are also some CVE's reported with these generated images. These can be addressed by updating packages during docker build, as below. I could test the image for arm32,arm64 and amd64 architectures and was able to resolve the CVE's. 
```
FROM golang:1.17.9 as build

# Add everything
ADD . /usr/src/multus-cni

RUN  cd /usr/src/multus-cni && \
     ./hack/build-go.sh

FROM centos:centos7

RUN yum update -y && \
    yum clean all && \
    rm -rf /var/cache/yum

LABEL org.opencontainers.image.source https://github.com/k8snetworkplumbingwg/multus-cni
COPY --from=build /usr/src/multus-cni/bin /usr/src/multus-cni/bin
COPY --from=build /usr/src/multus-cni/LICENSE /usr/src/multus-cni/LICENSE
WORKDIR /

ADD ./images/entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by cgchinmay** [comment]
@s1061123 Hi, are there any updates for this one ?

**Comment by dougbtv** [comment]
Tagged new release @ https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v3.9
