### ISSUE TITLE
getting 401 Unauthorized error to pull the multus image: https://ghcr.io/k8snetworkplumbingwg/multus-cni:thick

### ISSUE THREAD

**Issue by znoune** [k8snetworkplumbingwg/multus-cni#850]
Hi,
Trying to install the multus cni in my kind kubernetes cluster and the pod creation fails with the error message in the pod description:

code = Unknown desc = failed to pull and unpack image "ghcr.io/k8snetworkplumbingwg/multus-cni:thick": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://ghcr.io/v2/k8snetworkplumbingwg/multus-cni/manifests/sha256:e6319d716341e07602aeabe7afbf6c599db8bcd57fd52a2b16b7aa68fc595d36": read tcp 172.22.0.3:47458->140.82.121.34:443: read: connection reset by peer
 I have tried to pull the image from different hosts connected to different networks, the issue is still there:

PS C:\Users\zozanian>  wget https://ghcr.io/v2/k8snetworkplumbingwg/multus-cni/manifests/sha256:e6319d716341e07602aeabe7afbf6c599db8bcd57fd52a2b16b7aa68fc595d36
wget : {"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}

It was still working 2 days ago with another installation.
Wny updates which coould have caused this issue?

**How to reproduce it (as minimally and precisely as possible)**:
The procedure which have been follows is the official one described in the git repo quick start README.md file:

https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md

**Anything else we need to know?**:

**Environment**:
any..

- Multus version 
  image path and image ID (from 'docker images'): image: ghcr.io/k8snetworkplumbingwg/multus-cni:thick
- Kubernetes version (use `kubectl version`): kind v0.11.1 go1.16.4 linux/amd64
- Primary CNI for Kubernetes cluster:  
- OS (e.g. from /etc/os-release): NAME="Ubuntu" VERSION="20.04.4 LTS (Focal Fossa)"
- File of '/etc/cni/net.d/': not present
- File of '/etc/cni/multus/net.d': not present
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- 
kube-system          kube-multus-ds-8vmjm                        0/1     Init:ErrImagePull       0          84m
kube-system          kube-multus-ds-bk5t8                        0/1     Init:ErrImagePull       0          84m
kube-system          kube-multus-ds-lgrfx                        0/1     Init:ImagePullBackOff   0          84m
kube-system          kube-multus-ds-lwqlz                        0/1     Init:ImagePullBackOff   0          84m

- Other log outputs (if you use multus logging)

**Comment by maiqueb** [comment]
> kube-system kube-multus-ds-8vmjm 0/1 Init:ErrImagePull 0 84m
kube-system kube-multus-ds-bk5t8 0/1 Init:ErrImagePull 0 84m
kube-system kube-multus-ds-lgrfx 0/1 Init:ImagePullBackOff 0 84m
kube-system kube-multus-ds-lwqlz 0/1 Init:ImagePullBackOff 0 84m

Seems it failed to pull the imgs, doesn't it ? What exact multus image are you trying to pull ? I'm able to successfully pull the [multus stable](https://github.com/k8snetworkplumbingwg/multus-cni/blob/6adb4dc4c4b119f08a938607c14e9a89760024b8/deployments/multus-daemonset.yml#L197) img from the repo:
```bash
$ podman run -it --rm --entrypoint /bin/sh ghcr.io/k8snetworkplumbingwg/multus-cni:stable
Trying to pull ghcr.io/k8snetworkplumbingwg/multus-cni:stable...
Getting image source signatures
Copying blob 2d473b07cdd5 done  
Copying blob 781978f87722 done  
Copying blob a7f1a52c2445 done  
Copying config e6cafb5d5a done  
Writing manifest to image destination
Storing signatures
sh-4.2# exit
exit
```

**Comment by dougbtv** [comment]
Here's a nice reference deployment: https://github.com/k8snetworkplumbingwg/reference-deployment/tree/master/multus-whereabouts

**Comment by dougbtv** [comment]
Looks like a local kind problem or possibly a problem pulling images. If it's not one of those, please reopen.
