### ISSUE TITLE
Failed to set up pod network because token expired due to bound service account token

### ISSUE THREAD

**Issue by snowmansora** [k8snetworkplumbingwg/multus-cni#852]
**What happend**:
Pod stuck at ContainerCreating and following unauthorized error is shown when describing it:
```
  Warning  FailedCreatePodSandBox  9m38s                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "779db7fa6529acbdf3db228bc81a1f11e070e31c1d15354645e79f04631cb663" network for pod "ops-centos-8ff66846f-hff26": networkPlugin cni failed to set up pod "ops-centos-8ff66846f-hff26_default" network: Multus: [default/ops-centos-8ff66846f-hff26]: error getting pod: Unauthorized, failed to clean up sandbox container "779db7fa6529acbdf3db228bc81a1f11e070e31c1d15354645e79f04631cb663" network for pod "ops-centos-8ff66846f-hff26": networkPlugin cni failed to teardown pod "ops-centos-8ff66846f-hff26_default" network: Multus: [default/ops-centos-8ff66846f-hff26]: error getting pod: Unauthorized]
```

**What you expected to happen**:
Multus set up the pod network successfully and pod can run.

**Anything else we need to know?**:
Bound service account token is turned on by default in K8s 1.21: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md
In previous versions of K8s, service account token doesn't has an expiration.
In K8s 1.21, the token expires after 1 year or expires after 1 hour if service-account-extend-token-expiration is false.
Looking at Multus source code, I think the token will never be updated after the Multus pod finished its initial setup in entrypoint.sh.
Restarting the multus pod will fix the problem, because a new token will be used.

**How to reproduce it (as minimally and precisely as possible)**:
In a K8s with API server argument service-account-extend-token-expiration set to false.
After multus pod has been running for an hour, create a new pod, and the pod will stuck at ContainerCreating.

**Environment**:

- Multus version: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.8
- Kubernetes version (use `kubectl version`): 1.21.5
- Primary CNI for Kubernetes cluster: Flannel
- OS (e.g. from /etc/os-release): CentOS 7

**Comment by snowmansora** [comment]
Also, I notice there was an attempt to refresh the token, https://github.com/k8snetworkplumbingwg/multus-cni/pull/686/files, but that was never completed/merged-to-master.

Wondering is there any plan to fix the issue, now that there is a need to refresh the token or else Multus can potentially fail after an hour of running when service-account-extend-token-expiration is set to false.

Thanks.

**Comment by Alan01252** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/issues/1868#issuecomment-1126344830

We've also experienced this and it caused much confusion for a while.

**Comment by JornShen** [comment]
> 

I see this MR https://github.com/k8snetworkplumbingwg/multus-cni/pull/686 has been closed. 
And do you plan to merge it to the master, for these time,multus 4.0 has not release version ? 
@dougbtv

**Comment by infinitydon** [comment]
@dougbtv - Any update on which version has this fix? This is also affecting whereabouts.

**Comment by xagent003** [comment]
Bump... any ideas why this PR was closed? https://github.com/k8snetworkplumbingwg/multus-cni/pull/686

**Comment by dougbtv** [comment]
Yeah, it should be open, it just went auto stale.

**Comment by dougbtv** [comment]
Also, for what it's worth, I think with the thick plugin architecture, it shouldn't be such a big deal, that is, it should be using the service account token in the pod, and not a generated kubeconfig that resides on disk, so... It should just use the updated token.

**Comment by caribbeantiger** [comment]
> Also, for what it's worth, I think with the thick plugin architecture, it shouldn't be such a big deal, that is, it should be using the service account token in the pod, and not a generated kubeconfig that resides on disk, so... It should just use the updated token.

has anybody tried Thick plugin architecture in EKS already ?

**Comment by MarkSpencerTan** [comment]
Bumping this again since it seems like it went stale. Any updates?

**Comment by infinitydon** [comment]
For EKS, thick-plugin is now available, so far the token issue seems to be resolved using it.

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/multus/v4.0.2-eksbuild.1/multus-daemonset-thick.yml

**Comment by mikemykhaylov** [comment]
Still an issue on v4.0.2, after an hour the pod creation fails

**Comment by cbf123** [comment]
So what's the plan here, are we saying that this is never going to get fixed in the "thin" plugin?

**Comment by akashgreninja** [comment]
Any updates ?
