### ISSUE TITLE
Network status field in annotations lost infomation

### ISSUE THREAD

**Issue by thanhlong9x** [k8snetworkplumbingwg/multus-cni#855]
**What happend**:
I deployed the statefulsets of kafka application with SRIOV network. The replicas of statefulset is 3 
**What you expected to happen**:
In created pods, pod-0 lost the network information in k8s.v1.cni.cncf.io/networks-status field. I don't know what happened ? 
![image](https://user-images.githubusercontent.com/29721257/170946910-7af2fb05-5601-4cea-93a6-0fd7f2ac102d.png)

**How to reproduce it (as minimally and precisely as possible)**:
This is random and I don't know how to reproduce this error

**Environment**:
- Multus version 
  image path and image ID (from 'docker images'):   multus:v3.4
- Kubernetes version (use `kubectl version`): 1.21.5
- Primary CNI for Kubernetes cluster: Calico
- OS (e.g. from /etc/os-release): redhat 7
- File of '/etc/cni/net.d/':
   + 00-multus.conf:
   + 10-calico.conflist

**Comment by dougbtv** [comment]
Try updating to a later version as well, 3.4 is dated!

**Comment by cmssczy** [comment]
https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/blob/6ace5615d26a4d00d0a24bbbfa5d5f400ce7593e/pkg/utils/net-attach-def.go#L86-L96

hi @dougbtv , I'm curious about why we use `UpdateStatus(context.TODO(), pod, metav1.UpdateOptions{})` method to patch annotations?
