### ISSUE TITLE
In arm64 platform, ds name is kube-multus-ds-amd64

### ISSUE THREAD

**Issue by tukwila** [k8snetworkplumbingwg/multus-cni#866]
**What happend**:
i installed multus via kubespray (kube_network_plugin_multus: true) in ubuntu2004 arm64 platform, then checked multus ds which is kube-multus-ds-amd64

**What you expected to happen**:
 i think it should inplicite arm64 daemonset such as kube-multus-ds-arm64.

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy kubespray release-2.17 (set kube_network_plugin_multus is true) in one ubuntu2004 arm64 platform
2.  check all daemonsets, refer to the followings:
root@node1:~# kubectl get ds -A
NAMESPACE     NAME                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
kube-system   calico-node            1         1         1       1            1           kubernetes.io/os=linux     10h
kube-system   **kube-multus-ds-amd64**   0         0         0       0            0           **kubernetes.io/arch=amd64**   120m
kube-system   kube-proxy             1         1         1       1            1           kubernetes.io/os=linux     10h
**Anything else we need to know?**:
1.  hardware configuration: Lenovo SR650
2. root@node1:~# printf "$(uname -srm)\n$(cat /etc/os-release)\n"
Linux 5.4.0-120-generic aarch64
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Environment**:

- Multus version 
 multus-cni:v3.7.2
It is odd that there is no multus image in the tested env when k8 cluster is built up.
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:50:34Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}

- Primary CNI for Kubernetes cluster: 
- OS (e.g. from /etc/os-release):
root@node1:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- File of '/etc/cni/net.d/': 10-calico.conflist  calico-kubeconfig  calico.conflist.template
- File of '/etc/cni/multus/net.d': no such file
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)

root@node1:~# kubectl describe ds kube-multus-ds-amd64 -n kube-system
Name:           kube-multus-ds-amd64
Selector:       app=multus,tier=node
Node-Selector:  kubernetes.io/arch=amd64
Labels:         app=multus
                tier=node
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=multus
                    tier=node
  Service Account:  multus
  Containers:
   kube-multus:
    Image:      10.6.170.10:5000/k8snetworkplumbingwg/multus-cni:v3.7.2
    Port:       <none>
    Host Port:  <none>
    Command:
      /entrypoint.sh
    Args:
      --cni-conf-dir=/host/etc/cni/net.d
      --cni-bin-dir=/host/opt/cni/bin
      --multus-conf-file=auto
      --multus-kubeconfig-file-host=/etc/cni/net.d/multus.d/multus.kubeconfig
      --cni-version=0.4.0
    Limits:
      cpu:     100m
      memory:  90Mi
    Requests:
      cpu:        100m
      memory:     90Mi
    Environment:  <none>
    Mounts:
      /host/etc/cni/net.d from cni (rw)
      /host/opt/cni/bin from cnibin (rw)
  Volumes:
   cni:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
   cnibin:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
Events:            <none>

- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
Thank you for filing the issue, @tukwila 

As far as I looked your description, I guess that the issue might be in [kubespray](https://github.com/kubernetes-sigs/kubespray). 
Multus CNI repository does not have yaml about 'kube-multus-ds-arm64' and [kubespray have it](https://github.com/kubernetes-sigs/kubespray/blob/master/roles/network_plugin/multus/templates/multus-daemonset.yml.j2).

Kubespray is managed by different community so please ask kubespray community about it.
