### ISSUE TITLE
Example for Infiniband mode in multus-cni

### ISSUE THREAD

**Issue by ReyRen** [k8snetworkplumbingwg/multus-cni#874]
Is there any `config` examples for **Infiniband**?  
And I notice the `mode ` can configured with infinibandGUID, but what else like as following(static ip)?
```
config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
                "type": "macvlan",
                "capabilities": { "ips": true },
                "master": "eth0",
                "mode": "bridge",
                "ipam": {
                        "type": "static"
                }
        }]
    }'

```

**Comment by ReyRen** [comment]
@s1061123 Can you please do me a favor? thanks a lot

**Comment by s1061123** [comment]
I don't know the example for ib. Please ask in different community. At least I know that macvlan is not the one. So you may found infiniband cni plugin.
