### ISSUE TITLE
error adding container to network "cbr0": unsupported CNI result version "1.0.0"

### ISSUE THREAD

**Issue by NAVRockClimber** [k8snetworkplumbingwg/multus-cni#875]
First of all, I am still pretty new to K8S and might have overseen something. 
After updating to K3S 1.23.8 and Multus v3.9 I receive the following error message on creating containers:

kubectl describe:

`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9b4dda403aae6e013fc88d994f8040dbeadb8d616ea44e593203505cdd17d596": plugin type="multus" name="multus-cni-network" failed (add): [default/nginx/2105b0c4-6899-4268-8e85-1f40985d8a25:cbr0]: error adding container to network "cbr0": unsupported CNI result version "1.0.0"`

For closer investigation I set up a fresh single node cluster:

`curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=stable sh -`

installed multus using deployments/multus-daemonset.yml with the following (for k3s necessary) adjustment to the Daemonset:

```YAML
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: multus
    name: multus
    tier: node
  name: kube-multus-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: multus
  template:
    metadata:
      labels:
        app: multus
        name: multus
        tier: node
    spec:
      containers:
      - args:
        - --multus-conf-file=auto
        - --cni-version=0.3.1
        - --multus-kubeconfig-file-host=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
        command:
        - /entrypoint.sh
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
        name: kube-multus
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/etc/cni/net.d
          name: cni
        - mountPath: /host/opt/cni/bin
          name: cnibin
        - mountPath: /tmp/multus-conf
          name: multus-cfg
      hostNetwork: true
      initContainers:
      - command:
        - cp
        - /usr/src/multus-cni/bin/multus
        - /host/opt/cni/bin/multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
        name: install-multus-binary
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
          name: cnibin
      serviceAccountName: multus
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/rancher/k3s/agent/etc/cni/net.d
        name: cni
      - hostPath:
          path: /var/lib/rancher/k3s/data/current/bin
        name: cnibin
      - configMap:
          items:
          - key: cni-conf.json
            path: 70-multus.conf
          name: multus-cni-config
        name: multus-cfg
  updateStrategy:
    type: RollingUpdate
```

**What happend**:
Pod is stuck in ContainerCreating with kubectl describe showing:

`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9b4dda403aae6e013fc88d994f8040dbeadb8d616ea44e593203505cdd17d596": plugin type="multus" name="multus-cni-network" failed (add): [default/nginx/2105b0c4-6899-4268-8e85-1f40985d8a25:cbr0]: error adding container to network "cbr0": unsupported CNI result version "1.0.0"`

**What you expected to happen**:

Pod is created and gets to the state Running

**How to reproduce it (as minimally and precisely as possible)**:

- Setup a new K3S performing:  `curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=stable sh -`
- Copy plugins from https://github.com/containernetworking/plugins/releases/tag/v1.1.1 and extract them to: `/var/lib/rancher/k3s/data/current/bin`
- Take deployments/multus-daemonset.yml adjust volume cni and cnibin like shown above and add the arg: `"--multus-kubeconfig-file-host=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig"`
- apply a random pod e.g.: 
```apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.23.0
    resources: {}
    ports:
      - containerPort: 80
```
- run: `kubectl describe pod nginx`

**Anything else we need to know?**:

**Environment**:

- Multus version: 3.9 / ghcr.io/k8snetworkplumbingwg/multus-cni:stable
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s1", GitCommit:"53f2d4e7d80c09a7db1858e3f4e7ddfa13256c45", GitTreeState:"clean", BuildDate:"2022-06-27T21:49:50Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}`
- Primary CNI for Kubernetes cluster: flannel
- OS (e.g. from /etc/os-release): Debian GNU/Linux 11 (bullseye)
- File of '/etc/cni/net.d/'
`{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true}, "kubeconfig": "/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name":"cbr0", "cniVersion":"1.0.0", "plugins":[ { "type":"flannel", "delegate":{ "hairpinMode":true, "forceAddress":true, "isDefaultGateway":true } }, { "type":"portmap", "capabilities":{ "portMappings":true } } ] } ] }`
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`):
```
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"macvlan-static","namespace":"kube-system"},"spec":{"config":"{ \"cniVersion\": \"1.0.0\", \"name\": \"macvlan-static\", \"type\": \"macvlan\", \"master\": \"eth0\", \"capabilities\": { \"ips\": true }, \"ipam\": { \"type\": \"host-local\", \"subnet\": \"192.168.0.0/16\", \"rangeStart\": \"192.168.1.0\", \"rangeEnd\": \"192.168.2.255\" } }"}}
    creationTimestamp: "2022-07-04T18:10:16Z"
    generation: 2
    name: macvlan-static
    namespace: kube-system
    resourceVersion: "1350"
    uid: 2fb817ed-5685-4336-94d4-6a5f15492907
  spec:
    config: '{ "cniVersion": "1.0.0", "name": "macvlan-static", "type": "macvlan",
      "master": "eth0", "capabilities": { "ips": true }, "ipam": { "type": "host-local",
      "subnet": "192.168.0.0/16", "rangeStart": "192.168.1.0", "rangeEnd": "192.168.2.255"
      } }'
kind: List
metadata:
  resourceVersion: ""
```
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)
journalctl

```
Jul 04 20:00:04 node1 k3s[444349]: E0704 20:00:04.956012  444349 remote_runtime.go:209] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"4a9a0bf7fe3a31423151aae6994>
Jul 04 20:00:04 node1 k3s[444349]: E0704 20:00:04.956156  444349 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"4a9a0bf7fe3a31423151aae6994abff9>
Jul 04 20:00:04 node1 k3s[444349]: E0704 20:00:04.956221  444349 kuberuntime_manager.go:833] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"4a9a0bf7fe3a31423151aae6994abff9>
Jul 04 20:00:04 node1 k3s[444349]: E0704 20:00:04.956353  444349 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"nginx-58564c6d88-qfns5_nginx(224055e7-212f-4716-b285-35cdb95f0c9c)\" with Crea>
Jul 04 20:00:04 node1 systemd[1020]: run-netns-cni\x2dca4a0ab5\x2d1fe5\x2d6cf4\x2df6e1\x2da590afb89594.mount: Succeeded.
Jul 04 20:00:04 node1 systemd[1]: run-netns-cni\x2dca4a0ab5\x2d1fe5\x2d6cf4\x2df6e1\x2da590afb89594.mount: Succeeded.
Jul 04 20:00:10 node1 kernel: cni0: port 7(vethafdeef4c) entered blocking state
Jul 04 20:00:10 node1 kernel: cni0: port 7(vethafdeef4c) entered disabled state
Jul 04 20:00:10 node1 kernel: device vethafdeef4c entered promiscuous mode
Jul 04 20:00:10 node1 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Jul 04 20:00:10 node1 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethafdeef4c: link becomes ready
Jul 04 20:00:10 node1 kernel: cni0: port 7(vethafdeef4c) entered blocking state
Jul 04 20:00:10 node1 kernel: cni0: port 7(vethafdeef4c) entered forwarding state
```

**Comment by s1061123** [comment]
Thank you for the issue.

We're working on new multus release, 4.0, and it is addressed in 4.0 release. Please wait for a while. 
For workaround the issue, you can change version to less than '1.0.0', for example, '0.3.1' or '0.4.0'.

If you want to taste multus 4.0, 4.0 release candidate branch is in https://github.com/k8snetworkplumbingwg/multus-cni/tree/feature/multus-4.0 so you can build and try that.

**Comment by VoiDeD** [comment]
>  For workaround the issue, you can change version to less than '1.0.0', for example, '0.3.1' or '0.4.0'.

Changing k3s's flannel CNI configuration is a bit fraught with pain points once you've got a cluster stood up.

Is there any idea when 4.0 will be released? Alternatively, is it possible for support of the 1.0.0 CNI spec to be backported to 3.9?

As is, k3s's current out-of-the-box CNI configuration unfortunately makes Multus unusable.

**Comment by l-rossetti** [comment]
same issue here

**Comment by kaneg** [comment]
same issue, waiting for resolution.
