### ISSUE TITLE
How to add a custom data to metadata of an openstack instance

### ISSUE THREAD

**Issue by shruthidharani-4313** [k8snetworkplumbingwg/multus-cni#889]
I have a worker node where I added two additional interfaces named eth1 and eth2 using multus CNI. eth0 is provided by kubernetes. So I have three interfaces. Each interface has an external IP (10.94.x.x) and internal IP(10.32.x.x). i.e, seen same as below
```
Network-name            Internal IP             External IP/Floating IP
-----------------------------------------------------------------------
Private                   192.162.x.x,           10.94.x.x (used for kubernetes communication - eth0)
PrivateNetwork-1-test     10.32.x.x,             10.94.x.x (Created using multus cni for my pod private communication- eth1) 
PublicNetwork-1-test      10.31.x.x,             10.94.x.x (Created using multus cni for my pod public communication - eth2)
```
Inside my pod/container which I will install, same eth0, eth1 and eth2 internal IPs can be seen. But I need to fetch external IPs inside my pod/container. I can able to fetch the internal and external ip of eth0 (Private) using the below command to fetch the metadata of openstack.
```
[root@user ~]# curl http://169.254.169.254/latest/meta-data
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
hostname
instance-action
instance-id
instance-type
local-hostname
local-ipv4 (External/Floating ip of eth0 = 192.162.x.x)
placement/
public-hostname
public-ipv4 (Internal ip of eth0 = 10.94.x.x) 
public-keys/
reservation-id
security-groups
``` 

How can I add public-ipv4 IPs of my other two interfaces through terraform to this openstack metadata? If so, kindly provide in which module of terraform has this support to add metadata. I have this External/Floating IPs of eth1 and eth2 interfaces in my terraform.tfstate file. Is that data somehow can be used to achieve this? Or is there any other possible way I can achieve this?

It would be really helpful if someone helps me to get a solution on this. Thanks in advance!

**Comment by dougbtv** [comment]
I don't quite get what's going on with internal vs. external IP? Is that from services? 

Can you provide the net-attach-def so we can see how the IPs are getting assigned to the interfaces? 

> How can I add public-ipv4 IPs of my other two interfaces through terraform to this openstack metadata? If so, kindly provide in which module of terraform has this support to add metadata. 

This might be outside the scope of Multus, but... You can potentially assign IP addresses statically with the static IPAM CNI plugin.

**Comment by dougbtv** [comment]
During the maintainer's call Miguel brought up this may be openstack floating IPs reachable from outside the cluster.

Is that the case? It may require some further setup to make sure these are reachable.
