### ISSUE TITLE
Multus does not send some deletes to cni plugin after a reboot of the node

### ISSUE THREAD

**Issue by saranshan2603** [k8snetworkplumbingwg/multus-cni#891]
**What happend**:

The node was rebooted and the pods existing in that node went it to terminating and moved to another node. When the node came back up, deletes are sent for the containers that moved to another node to the cni-plugin from multus. I see deletes of some containers are missing.

Following is a snapshot from multus-lumberjack logs

 [error] Multus: failed to get the cached delegates file: open /var/lib/cni/multus/80c8f5d1c4727793b987b5592bd0a3228cb2cdde8f292804b404fb439b379a99: no such file or directory, cannot properly delete

**What you expected to happen**:
All stale containers multus should send a delete to the cni plugin

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version 
  latest
- Kubernetes version (use `kubectl version`):
 openshift 4.10
- Primary CNI for Kubernetes cluster:
calico

**Comment by dougbtv** [comment]
@saranshan2603 this I believe is a functionality of CNI itself, and not of Multus. So, Multus can only react to what's been sent by CNI.

The CNI DEL for Multus is done as a kind of best effort, Multus tries to use what's available, and if resources are missing -- it quietly moves on without erroring (errr, well at least exiting zero)

See also: https://github.com/containernetworking/cni/blob/main/SPEC.md#del-remove-container-from-network-or-un-apply-modifications

> Plugins should generally complete a DEL action without error even if some resources are missing. 

In this case, the cache is missing, so Multus has missing resources.
