### ISSUE TITLE
CVE Reduction / Base Container Image Change

### ISSUE THREAD

**Issue by jeremy-duckworth** [k8snetworkplumbingwg/multus-cni#898]
**What would you like to be added**:

Scanning `ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.1` (latest apparent release) with Snyk, it reports 877 CVEs, with ~ 30 critical or high:

```
Package manager:   rpm
Project name:      docker-image|ghcr.io/k8snetworkplumbingwg/multus-cni
Docker image:      ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.1
Platform:          linux/amd64
Base image:        centos:centos7.9.2009
Licenses:          enabled

Tested 148 dependencies for known issues, found 877 issues.

Base Image             Vulnerabilities  Severity
centos:centos7.9.2009  877              3 critical, 27 high, 416 medium, 431 low

Recommendations for base image upgrade:

Major upgrades
Base Image      Vulnerabilities  Severity
centos:centos8  355              0 critical, 31 high, 206 medium, 118 low
```

Adding a layer in with `yum -y upgrade ...` doesn't change this situation. Thus, this really looks like the upstream container image (centos 7) isn't picking up patches. Given the ~ imminent EOL for CentOS 7 (June 2024), it may explain why the patching cycle is slowing (in part). 

On the presumption that Multus would be fairly happy with much less than a ~ full Linux distro in a container, would it be possible to transition to a much slimmer, and more current "base" image? 

My team would like to leverage your container images, ideally not forking if possible. I would think this is a similar desire for others, given the criticality of Multus. 

**Why is this needed**:

Manage known 3rd party security vulnerabilities in Multus container image distributions. 

If you have a base image transition/image build transition in mind, happy to submit a PR/help out.

**Comment by stradling** [comment]
Even if it could be argued that the base container vulns are not a critical, they are still very visible to site security compliance folks. My site is very interested in this fix.

**Comment by dougbtv** [comment]
For 3.9.x we'll need some shell tools for the initial install. I propose that we switch to a fedora base image

**Comment by jeremy-duckworth** [comment]
Thanks @dougbtv do you have a requirement or forcing function to leverage an EL-based container distribution?

**Comment by jeremy-duckworth** [comment]
Thanks @dougbtv! We'll start moving towards the newer builds.
