### ISSUE TITLE
Rename interfaces 'net*' to 'eth*'

### ISSUE THREAD

**Issue by Ganesh-Juniper** [k8snetworkplumbingwg/multus-cni#901]
**What happend**:
I'm trying to add two network interfaces eth1 & eth2 to my pod. I have used below nad annotation.
`
template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"orange","interface":"eth1"},{"name":"green","interface":"eth2"}]'
`

The network interfaces eth1 & eth2 added to k8s pod instead of net1 & net2. This is fine and this is what I expected.
But, these interfaces do not have IP addresses assigned. Instead, two other interfaces 'tap1' and 'tap2' are created with proper IP addresses assigned. This is the issue.

`eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether be:42:eb:d6:1c:53  txqueuelen 0  (Ethernet)
        RX packets 5  bytes 446 (446.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1  bytes 42 (42.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 9a:e7:20:35:f6:b6  txqueuelen 0  (Ethernet)
        RX packets 5  bytes 446 (446.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1  bytes 42 (42.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

**What you expected to happen**:
Expected two network interfaces eth1 & eth2 added to pod and assigned IP addresses to these interfaces as per NAD.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Multus CNI plugin and create required NADs.
2. Take a simple pod yaml
3. Add below annotation and deploy the pod
4. check network interfaces of pod(ifconfig)

**Anything else we need to know?**:

**Environment**:

- Multus version 
  Taken latest code by doing git clone https://github.com/intel/multus-cni.git

- Kubernetes version (use `kubectl version`):
- 1.20
- Primary CNI for Kubernetes cluster:
Calico
- OS (e.g. from /etc/os-release):
  ubuntu

**Comment by s1061123** [comment]
Please share the net-attach-def and pod yaml used in above condition.

**Comment by s1061123** [comment]
@Ganesh-Juniper could you please share the net-attach-def and pod yaml used in above case?
