### ISSUE TITLE
gstreamer via multus network

### ISSUE THREAD

**Issue by yepmunchun** [k8snetworkplumbingwg/multus-cni#909]
Hi,
We have setup multus network in our cluster. When we use iPerf performance tool to test its performance, multus network performs significantly better (about 20x higher) than default network. 
![image](https://user-images.githubusercontent.com/92574290/188048421-31c0e353-8752-46fd-bcc0-1e79e194a88d.png)

However, when we use it in our gstreamer use case, the performance is lower when running via multus network comparing to default network.
![image](https://user-images.githubusercontent.com/92574290/188049369-8881ece9-8441-44d6-8ad7-500cacf62f99.png)

Do you have any idea? Or Is it we missed out some Multus CNI configuration that need to be fined tune specifically for RTP streaming protocol?

Thanks.

**Comment by dougbtv** [comment]
Any further progress on your part? 

Which CNI are you using? Multus is just invoking a CNI plugin, so it's likely related to the CNI plugin used.
