### ISSUE TITLE
unable to ping network interface IP

### ISSUE THREAD

**Issue by yepmunchun** [k8snetworkplumbingwg/multus-cni#910]
Hi,
In our k8s cluster with multus enabled, the container unable to reach the bounded network interface IP defined in CNI (enp170s0 in the screenshot below)

![image](https://user-images.githubusercontent.com/92574290/189595465-57cae4b6-afb3-4ee0-9dd4-1c57d393350d.png)
![image](https://user-images.githubusercontent.com/92574290/189595579-4eeca555-a8e2-4eee-89e5-38694a1a3cd8.png)
![image](https://user-images.githubusercontent.com/92574290/189595754-107548bf-a73c-42c1-b4e3-2eef6a4417c8.png)

Any idea?

Thanks.

**Comment by yockgen** [comment]
https://github.com/k8snetworkplumbingwg/multus-cni/issues/832
