### ISSUE TITLE
How to set different VLAN tags from a pod YAML file?

### ISSUE THREAD

**Issue by JustinHuang402490** [k8snetworkplumbingwg/multus-cni#921]
I already know that we can set a VLAN tag using both ways:

1. `ip link set {pf_name} {vf_index} vlan {vlan_tag}` from host. 
2. NetworkAttachmentDefinition file to set a VLAN tag to the specific resource pool. (see the first figure)
<img src="https://user-images.githubusercontent.com/41780406/194481751-9ea470e3-2459-4fba-a76b-ab82c197c61b.png" width="400">

Then I find another possible way to set VLAN tags from a pod YAML file. (see the second figure)
<img src="https://user-images.githubusercontent.com/41780406/194484173-3c88b40b-9108-44de-8296-73a4e71fdeaa.png" width="400">

I try to set VLAN tags from a pod YAML file. However, it does not work. 
Is this functionality supported now? or do I miss something?

Any reply would be greatly appreciated!

**Comment by s1061123** [comment]
Hi @JustinHuang402490 

To configure CNI config in pod YAML, multus provides the following mechanisms:

- `runtimeConfig`
- `cni-args`

Hence sr-iov supports one of them for vlan config, then it works, however as far as I see sr-iov config doc [1], it might not supported yet.

[1] https://github.com/k8snetworkplumbingwg/sriov-cni/blob/master/docs/configuration-reference.md#runtime-configuration

Could you please ask sr-iov cni repo to support one of these?
# I will also ask but recommend to ask from you as well.
