### ISSUE TITLE
multus cni issue following k3s upgrade

### ISSUE THREAD

**Issue by liyimeng** [k8snetworkplumbingwg/multus-cni#927]
**What happend**:

I have a k3s distribution which update its cni bin dir by linking to a new dir during upgrade.  But this seems not awared by multus cni and cause error like this 

```
Warning  FailedCreatePodSandBox  52s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "78fe2416c4b0208cc81b485dcc91c1cc9aa3341c0ea858c12658d7696de00687": plugin type="multus" name="multus-cni-network" failed (add): failed to find plugin "multus" in path [/var/lib/rancher/k3s/3ccf8a82/bin]
```

`3ccf8a82/bin` is where multus was located before upgrade.  After upgrade,  cni plugins have move into 433356f/bin, as show below
```
sudo ls -l /var/lib/rancher/k3s/
433356f
3ccf8a82
current -> /var/lib/rancher/k3s/433356f
```
I am wondering if there is a solution to let multus daemonset aware of this change, and update bin dir to the right path. 

**What you expected to happen**:

multus cni should continue to work after k3s upgrade

**How to reproduce it (as minimally and precisely as possible)**:
- deploy a k3s, move its bin to another name, and point to it via a symbol link
- rename bin dir, and update symbol link to point to the new name. 
- kubelete failed to local multus even the symbol link is pointing to the right path.
-  
**Anything else we need to know?**:

**Environment**:

- Multus version : 3.9.1 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`): 1.23
- Primary CNI for Kubernetes cluster: 1.0.0 
- OS (e.g. from /etc/os-release): ubuntu
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by dougbtv** [comment]
Looks like a great community issue to tackle. It's really an integration issue specific to k3s that the bindir changes, I haven't seen that in other k8s distros.

I think if someone from the community can approach this from a deployment standpoint, that might be interesting, especially could be added to the reference deployments: https://github.com/k8snetworkplumbingwg/reference-deployment

**Comment by liyimeng** [comment]
Sorry  to bother everyone, it turns out neigther multus nor k3s issue, it is kata container, who modified cri runtime config, but not update it after k3s upgrade. So I would like to close this one.
