### ISSUE TITLE
v0.0.0 block multus imported by other project

### ISSUE THREAD

**Issue by liyimeng** [k8snetworkplumbingwg/multus-cni#928]
When I try to import multus in my project via `	"gopkg.in/k8snetworkplumbingwg/multus-cni.v3/pkg/multus"`

it failed with 

```
go mod tidy 
go: finding module for package gopkg.in/k8snetworkplumbingwg/multus-cni.v3/pkg/multus
go: found gopkg.in/k8snetworkplumbingwg/multus-cni.v3/pkg/multus in gopkg.in/k8snetworkplumbingwg/multus-cni.v3 v3.9.2
go: gopkg.in/k8snetworkplumbingwg/multus-cni.v3@v3.9.2 requires
        k8s.io/kubelet@v0.0.0: reading k8s.io/kubelet/go.mod at revision v0.0.0: unknown revision v0.0.0
```
I think the problem come from here
https://github.com/k8snetworkplumbingwg/multus-cni/blob/1aac2431b86adea46236fc16bcb100330ca28afb/go.mod#L27

I am wondering why not use 
`	k8s.io/kubelet v0.20.10 ` instead of `	k8s.io/kubelet v0.0.0`

Thanks a lot in advanced!

**Comment by s1061123** [comment]
Hi, thank you for the point the issue. Understood. I will fix it soon.

One workaround could be using `replace` directive as go.mod of multus does.

https://github.com/k8snetworkplumbingwg/multus-cni/blob/1aac2431b86adea46236fc16bcb100330ca28afb/go.mod#L93

**Comment by liyimeng** [comment]
@s1061123 no help, similar problem popup, hope you come back with a solution soon :)
