### ISSUE TITLE
how multus kubeconfig rotated?

### ISSUE THREAD

**Issue by liyimeng** [k8snetworkplumbingwg/multus-cni#929]
Not sure if I am correct. I guess multus use the kubeconfig file to access the cluster resource. There are cert in the file. What if the cert get expired, who is response for rotating the certs?

Thank a lot in advanced!

**Comment by liyimeng** [comment]
4.0+ use service account, eliminating the need of kubeconfig, right?

**Comment by s1061123** [comment]
So it depends of version and deployments, however, it can handle even though < 4.0. In [3.x thick plugin deployment case](https://github.com/k8snetworkplumbingwg/multus-cni/blob/release-v3/deployments/multus-daemonset-thick-plugin.yml), multus-daemonset watches the service account and update the kubeconfig for multus, so it should be updated. In [3.x thin (default) deployment case](https://github.com/k8snetworkplumbingwg/multus-cni/blob/release-v3/deployments/multus-daemonset.yml), it cannot be handled.
