### ISSUE TITLE
According to the e2e/README.md document, the installation error is reported

### ISSUE THREAD

**Issue by yulng** [k8snetworkplumbingwg/multus-cni#933]
According to the e2e/README.md document, the installation error is reported
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/31728060/197195036-02a27931-f2e6-40aa-a6aa-ca4f31bbb9b1.png">

Would like to explain what needs to be installed in the environment

**Comment by yulng** [comment]
https://github.com/k8snetworkplumbingwg/multus-cni/pull/934

**Comment by dougbtv** [comment]
Fixed in #934 (thank you)
