### ISSUE TITLE
Crash PODs added multiple interfaces (Free5GC, UERANSIM, Calico, Multus)

### ISSUE THREAD

**Issue by pinoOgni** [k8snetworkplumbingwg/multus-cni#938]
Hi everybody!

**What happend**:
I'm using the [towards5gs-helm](https://github.com/Orange-OpenSource/towards5gs-helm) project that provide helm charts in order deploy Free5GC and UERASIM. I'm using Calico with Multus. 

**What you expected to happen**:

In brief: there seem to be problems adding multiple (MACVLAN) interfaces in some PODs in some circumstances.

**How to reproduce it (as minimally and precisely as possible)**:

[Here](https://github.com/Orange-OpenSource/towards5gs-helm/issues/55) is the detailed description of the problem  

**Anything else we need to know?**:

I opened the same issue on [Calico](https://github.com/projectcalico/calico/issues/6896).

Do you have any suggestions? Thanks in advance

Giuseppe

**Comment by dougbtv** [comment]
Could you post a reproducer that the maintainer's can use as a reference? Thanks!
