### ISSUE TITLE
NetworkPolicy Support

### ISSUE THREAD

**Issue by feitnomore** [k8snetworkplumbingwg/multus-cni#940]
Hello, I'm using Multus and Cilium on my environment, and I'm struggling getting NetworkPolicies to work, specially egress rules. As far as I can tell, seems like egree policies only works with CIDR blocks. If I use namespaceSelector or podSelector it doesn't work. Are there any known limitations using Network Policies with Multus?
Thanks!

**Comment by s1061123** [comment]
Are you talking about Kubernetes NetworkPolicy? In your case, NetworkPolicy will be done by Cilium, not multus.
Multus just asks to delegated CNI plugin (i.e. cilium in your case) to create interface, hence multus does nothing about actual network, including NetworkPolicy.

**Comment by feitnomore** [comment]
Sure, thanks for the guidance!
