### ISSUE TITLE
Can not ping external network from extra network interface created using multus

### ISSUE THREAD

**Issue by rveerama1** [k8snetworkplumbingwg/multus-cni#945]
**What happend**:
I have created a simple pod with two network interfaces (default eth0 and net1). I can ping external network via _eth0_ but not via _net1_.

**What you expected to happen**:
Expecting similar behavior as eth0. Should be able to ping eternal network via _net1_ interface 

**How to reproduce it (as minimally and precisely as possible)**:

sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

sudo tee /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF

sudo kubeadm init --pod-network-cidr=192.168.0.0/16

kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

kubectl apply -f calico/custom-resources.yaml 

custom-resources.yaml 
```
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    containerIPForwarding: Enabled
---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}

```

./calicoctl get IPPool  default-ipv4-ippool -o yaml
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  creationTimestamp: "2022-10-31T20:12:16Z"
  name: default-ipv4-ippool
  resourceVersion: "636"
  uid: 12762d4d-bef0-46b0-8596-003b5de867e2
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 192.168.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: CrossSubnet

```
kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml

kubectl apply -f macvlan-conf.yaml 
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'

```

kubectl apply -f samplepod.yaml 
```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: praqma/network-multitool

```

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
```
    Image:         ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
    Image ID:      ghcr.io/k8snetworkplumbingwg/multus-cni@sha256:0c1757fbc8160aa04f3d46e3dd2bdb35aaf427135e7798df6f65decec2b36e22

```
- Kubernetes version (use `kubectl version`):
```
 Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

```
- Primary CNI for Kubernetes cluster: Calico
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- File of '/etc/cni/net.d/'
 
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)
  
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if119: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 6a:65:ba:3f:66:0d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.47.203/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::6865:baff:fe3f:660d/64 scope link 
       valid_lft forever preferred_lft forever
5: net1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 46:a9:92:d3:7a:d1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.200/24 brd 192.168.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::44a9:92ff:fed3:7ad1/64 scope link 
       valid_lft forever preferred_lft forever

```

**Comment by dougbtv** [comment]
Can you provide the output `ip route` to check that the routing is correct?

**Comment by dougbtv** [comment]
Can you also provide the destination you're pinging? Or example of it. But, this is likely an issue with macvlan + the host interface you're using as the master interface. And possibly routing somewhere is preventing the ICMP message from reaching the destination.

**Comment by rveerama1** [comment]
@dougbtv 

bash-5.1# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 5a:68:67:17:91:a7 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.47.198/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5868:67ff:fe17:91a7/64 scope link 
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 86:7a:91:2e:86:46 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.0.203/24 brd 192.168.0.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::847a:91ff:fe2e:8646/64 scope link 
       valid_lft forever preferred_lft forever

bash-5.1# ip route
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 
192.168.0.0/24 dev net1 proto kernel scope link src 192.168.0.203 

bash-5.1# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG    0      0        0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 net1

bash-5.1# ping -I eth0 -c 1 10.252.58.149
PING 10.252.58.149 (10.252.58.149) from 192.168.47.198 eth0: 56(84) bytes of data.
64 bytes from 10.252.58.149: icmp_seq=1 ttl=57 time=155 ms

--- 10.252.58.149 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 154.634/154.634/154.634/0.000 ms


bash-5.1# ping -I net1 -c 1 10.252.58.149
PING 10.252.58.149 (10.252.58.149) from 192.168.0.203 net1: 56(84) bytes of data.


--- 10.252.58.149 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
