### ISSUE TITLE
Pod status error after reboot node cause multus cache file damaged

### ISSUE THREAD

**Issue by hangzhouwanjun** [k8snetworkplumbingwg/multus-cni#948]
**What happend**:
Node reboot cause multus cache file damaged,  pod status error while kubelet continuously delete pause failed. And describe pod print "Multus: failed to load netconf: unexpected end of JSON input".
The kubelet log such as:

```
_E0721 03:31:50.263100    1310 cni.go:352] **Error deleting kube-system_harbor-master1-7brdq/bc50ca19f75360f83f91470a39a20ada04170bb4620b3c9ccbcdd3de367b6a95 from network multus/multus-cni-network: Multus: failed to load netconf: unexpected end of JSON input**
E0721 03:32:02.262404    1310 cni.go:352] **Error deleting kube-system_harbor-master1-7brdq/bc50ca19f75360f83f91470a39a20ada04170bb4620b3c9ccbcdd3de367b6a95 from network multus/multus-cni-network: Multus: failed to load netconf: unexpected end of JSON input**
E0721 03:32:13.260088    1310 cni.go:352] **Error deleting kube-system_harbor-master1-7brdq/bc50ca19f75360f83f91470a39a20ada04170bb4620b3c9ccbcdd3de367b6a95 from network multus/multus-cni-network: Multus: failed to load netconf: unexpected end of JSON input**
```

Multus code has some error if multus cache file not JSON format, kubelet continuously delete pause failed.

```
func **cmdDel**(args *skel.CmdArgs, exec invoke.Exec, kubeClient k8s.KubeClient) error {
  …   
   // Read the cache to get delegates json for the pod
   netconfBytes, path, err := consumeScratchNetConf(args.ContainerID, in.CNIDir)
   if err != nil {
      // Fetch delegates again if cache is not exist
      if os.IsNotExist(err) {
         if in.ClusterNetwork != "" {
            err = k8s.GetDefaultNetworks(ctx, k8sArgs, in, kubeClient)
            if err != nil {
               return logging.Errorf("Multus: Failed to get clusterNetwork/defaultNetworks: %v", err)
            }
            // First delegate is always the master plugin
            in.Delegates[0].MasterPlugin = true
         }

         // Get pod annotation and so on
         _, _, err := k8s.TryLoadPodDelegates(ctx, k8sArgs, in, kubeClient)
         if err != nil {
            if len(in.Delegates) == 0 {
               // No delegate available so send error
               return logging.Errorf("Multus: failed to get delegates: %v", err)
            }
            // Get clusterNetwork before, so continue to delete
            logging.Errorf("Multus: failed to get delegates: %v, but continue to delete clusterNetwork", err)
         }
      } else {
         return logging.Errorf("Multus: Err in reading the delegates: %v", err)
      }
   } else {
      **if err := json.Unmarshal(netconfBytes, &in.Delegates); err != nil {
         return logging.Errorf("Multus: failed to load netconf: %v", err)
      }**
      // check plugins field and enable ConfListPlugin if there is
      for _, v := range in.Delegates {
         if len(v.ConfList.Plugins) != 0 {
            v.ConfListPlugin = true
         }
      }
      // First delegate is always the master plugin
      in.Delegates[0].MasterPlugin = true
   }
```

**What you expected to happen**: 
Reboot node even if multus cache file damaged,  pod status Running

**How to reproduce it (as minimally and precisely as possible)**:
Yes, if the /var/lib/cni/multus/bc50ca19f75360f83f91470a39a20ada04170bb4620b3c9ccbcdd3de367b6a95 is empty or not JSON format. Pod status error.
such as:
kube-system    harbor-master1-tw8nt                       0/8     Error              7          131d   <none>            worker   <none>           <none>

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`): v1.15.12
- Primary CNI for Kubernetes cluster: calico
- OS (e.g. from /etc/os-release): redhat 7.6
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by dougbtv** [comment]
Thanks for the great report. This does need to be addressed so that cmdDel exits cleanly for CNI DEL. Appreciate it.

**Comment by fzu-huang** [comment]
> Yes, if the /var/lib/cni/multus/bc50ca19f75360f83f91470a39a20ada04170bb4620b3c9ccbcdd3de367b6a95 is empty or not JSON format. Pod status error.

How are empty files generated? I think there might be a more reasonable way to handle it here:

If an empty file appears, try to use kubeClient to obtain the cniConf of the pod. If obtained, the Delete delegate will be processed according to the content of this cni conf (the Pod should be blocked in the Terminating state at this time, and its cniConf can usually be obtained). If it cannot be obtained, print the log and return nil directly.
