### ISSUE TITLE
How to use full-fledged third party cni plugin along with default cni plugin using multus

### ISSUE THREAD

**Issue by PS-14** [k8snetworkplumbingwg/multus-cni#950]
Hi Team,

I want to use kube-router cni plugin in DSR mode along with cilium using multus. I haven't found a way to add third party cni plugin using multus. Please help to provide a way if any. Thanks

@s1061123 @tedyu @PrashantSunkari @micw

**Comment by dougbtv** [comment]
Hey @PS-14 can you give some more details?

Generally, just copy the CNI plugin into the CNI binary directory. Then, create a CNI configuration for that CNI plugin, and keep it in a NetworkAttachmentDefinition. 

Any plugin that follows the CNI specification should be API-compatible with Multus, so give it a shot and update the issue with your experience.
