### ISSUE TITLE
Using the calico IPAM module

### ISSUE THREAD

**Issue by gavol** [k8snetworkplumbingwg/multus-cni#962]
Hello,

may I ask whether it is possible to use ```calico-ipam``` as an IPAM plug-in with ```multus``` (i.e., in order to pair it with a CNI like ```macvlan``` or ```bridge```).

I am looking for an IPAM plug-in working well across several PODs. ```whereabouts``` is already a good option; at the same time, the additional flexibility offered by ```calico-cni``` (e.g., topology-based IP assignment) will be a perfect solution for my case.

I was wondering whether anybody has any experience with that.

Thanks in advance.

**Comment by dougbtv** [comment]
In theory it should work! I'm unsure of the dependencies of calico-ipam, but if it follow the CNI spec for ipam plugins, it should work with any plugin that accepts an ipam plugin

**Comment by dougbtv** [comment]
The details are probably relative to the calico project, so I'll close with that -- regarding their dependencies. But I believe you should try it and see how it goes

**Comment by gavol** [comment]
Thanks a lot for your input.
