### ISSUE TITLE
No multi-arch images of `snapshot-thick`

### ISSUE THREAD

**Issue by samip5** [k8snetworkplumbingwg/multus-cni#974]
**What happend**:

I tried to deploy using snapshot-thick, but I run a mixed-arch cluster so it fails on most of my nodes due to `no match for platform in manifest: not found`

**What you expected to happen**:

I would have expected it to behave like the latest tag does aka having manifests for arm64 and amd64.

**How to reproduce it (as minimally and precisely as possible)**:

Build a mixed-arch cluster and deploy multus or try to.

**Comment by s1061123** [comment]
Currently multus thick daemonset is only for amd64 because we do not verify that thick image work in other platform yet.
If you volunteer to test, please build and test. We're looking forward to hear your feedback.

Thank you in advance.
