### ISSUE TITLE
multus for crio fails if it cannot find systemctl

### ISSUE THREAD

**Issue by telmich** [k8snetworkplumbingwg/multus-cni#975]
**What happend**:

I installed multus using the multus-daemonset-crio.yml and all multus pods are in error state:

```
kube-multus-ds-b97vl                0/1     Error               3 (37s ago)   80s
kube-multus-ds-j5b7w                0/1     Error               1 (28s ago)   80s
kube-multus-ds-jz28z                0/1     Error               3 (42s ago)   80s
kube-multus-ds-lhgsz                0/1     Error               3 (44s ago)   80s

```

Looking at the log of one of them

```
[09:17] server107.ge.nau.so:~# kubectl -n kube-system logs kube-multus-ds-jz28z
2022-11-27T08:17:47+00:00 Generating Multus configuration file using files in /host/etc/cni/net.d...
2022-11-27T08:17:47+00:00 Using MASTER_PLUGIN: 10-calico.conflist
2022-11-27T08:17:48+00:00 Nested capabilities string: "capabilities": {"bandwidth": true, "portMappings": true},
2022-11-27T08:17:48+00:00 Using /host/etc/cni/net.d/10-calico.conflist as a source to generate the Multus configuration
2022-11-27T08:17:48+00:00 Config file created @ /host/etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"bandwidth": true, "portMappings": true}, "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "datastore_type": "kubernetes", "mtu": 0, "nodename_file_optional": false, "log_level": "Info", "log_file_path": "/var/log/calico/cni/cni.log", "ipam": { "type": "calico-ipam", "assign_ipv4" : "false", "assign_ipv6" : "true"}, "container_settings": { "allow_ip_forwarding": false }, "policy": { "type": "k8s" }, "kubernetes": { "k8s_api_root":"https://[2a0a:5480:2::1]:443", "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "bandwidth", "capabilities": {"bandwidth": true} }, {"type": "portmap", "snat": true, "capabilities": {"portMappings": true}} ] } ] }
2022-11-27T08:17:48+00:00 Restarting crio
/entrypoint.sh: line 452: systemctl: command not found

```

The used image is:

```
image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
```

**What you expected to happen**:

multus to not crash

**How to reproduce it (as minimally and precisely as possible)**:

* Install multus with a host OS that does not have systemctl, such as Alpine Linux or Devuan

**Anything else we need to know?**:

You might want to include a flag allowing to specify the restart command.

**Environment**:

- Multus version ghcr.io/k8snetworkplumbingwg/multus-cni:stable
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release): Alpine Linux 3.15
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
@telmich Could you please let me know which yaml file is used to deploy multus for troubleshooting?

**Comment by s1061123** [comment]
@telmich Could you please test with multus-daemonset-crio.yaml without `        - "--restart-crio=true"`
https://github.com/k8snetworkplumbingwg/multus-cni/blob/33ce772b98e55385f27b278a7616cb81d7203b01/deployments/multus-daemonset-crio.yml#L189

**Comment by ma-sattari** [comment]
Hi @telmich,

I had same problem, I set `- "--restart-crio=false"` and then manually run `sudo systemctl restart crio` and didn't get any error.

**Comment by agowa338** [comment]
I made a PR to fix this issue.
However, it requires a rebuild of the docker image.

In the meantime, use this shim and save it as `/usr/bin/systemctl` (0755 root:root): https://github.com/oz123/systemctl-shim/blob/master/systemctl-shim.sh
