### ISSUE TITLE
Multus/service mesh(istio, linkerd and so on) Interworking

### ISSUE THREAD

**Issue by s1061123** [k8snetworkplumbingwg/multus-cni#982]
Currently multus and service mesh, istio, linkerd, open service mesh, does not have interworking appropriately. This issue is parent issue to track the issue.

### Service mesh with secondary network

Currently each service mesh does not recognize secondary network (as far as I know of). Kubernetes Network Plumbing WG is still working on how to integrate service mesh with multus for a while and it is not concluded yet. @plwhite, @dougbtv and @nicklesimba are working on that. 

#### Current activities:

[Service Mesh and Multi-Network enhancements proposal](https://docs.google.com/document/d/1nR8WIzbideTAKUlc89OARrg2pI1E49-oKtKmTyI9-CI/edit#heading=h.fyr6zaogsm3o)

### Provide consistent install/interworking method (e.g. net-attach-def usage)

Currently some service mesh provides a way to interworking with multus, however, these methods are different, not unified. Some method provides a method which is not appropriate way and it could be improved by design.

#971 is the one of the issue.

Hence we need to come up with a optimized way (from multus point of view) and try to propagate to various service mesh projects.

**Comment by s1061123** [comment]
revive

**Comment by ormergi** [comment]
Hi, is there a workaround or planned fix for this?
