### ISSUE TITLE
Slack invite is broken

### ISSUE THREAD

**Issue by taylor** [k8snetworkplumbingwg/multus-cni#991]
The invite link is broken in https://github.com/k8snetworkplumbingwg/multus-cni#contact-us

> For any questions about Multus CNI, feel free to ask a question in #general in the [NPWG Slack](https://npwg-team.slack.com/), or open up a GitHub issue. Request an invite to NPWG slack [here](https://intel-corp.herokuapp.com/).

The heroku app, added in #619, is down.

**Comment by dougbtv** [comment]
temporary invite! https://join.slack.com/t/npwg-team/shared_invite/zt-1m535tc77-J5onxSxpP28ASfL~Rc92YQ
