### ISSUE TITLE
Is there an SVG version of the project logo available?

### ISSUE THREAD

**Issue by leecalcote** [k8snetworkplumbingwg/multus-cni#993]

**Comment by dougbtv** [comment]
We should have a vector graphic of the logo! I don't think we have the original source, it'll have to be redrawn.

**Comment by s1061123** [comment]
Put it in https://raw.githubusercontent.com/wiki/k8snetworkplumbingwg/multus-cni/images/multus_vector_logo.svg

**Comment by leecalcote** [comment]
Thank you much, @dougbtv, @s1061123. 👍

**Comment by s1061123** [comment]
@leecalcote BTW, could you please let me know why you need, if you don't mind it?
